import { describe, it, expect } from 'vitest';
import { SocraticEngine } from '@/infrastructure/services/SocraticEngine';
import { researchErrorCategory } from '@/infrastructure/services/socraticResearchCategory';
import { SESSION1_TASKS, getSessionTasks } from '@/data/sessionTasks';
import { getSessionBranchTasks } from '@/data/sessionBranchTasks';
import MAIN from './fixtures/main-socratic-error-categories.json';

/**
 * Research data (owner's standing rule, 28.9.2026): the error_category a
 * static card records in SOCRATIC_CARD_SHOWN (Module 18's distribution) is
 * the value main recorded for the same exercise and board. The fixture was
 * generated by running SocraticEngine.getSynchronousTaskHint on origin/main
 * (acccee7c, and again on 15499291 after #125 changed the instructions: the
 * same values) over every exercise of meetings 1 and 3–8, both tracks and the
 * choice path, in the board states below.
 *
 * The one approved change (שהB.1): s3_r_t7, null → 'conceptual'.
 */
const P = ['units', 'tens', 'hundreds', 'thousands'] as const;
const std = (n: number) => Object.fromEntries(P.map((p, i) => [p, Math.floor(n / 10 ** i) % 10])) as any;
const Z = { units: 0, tens: 0, hundreds: 0, thousands: 0 };
function statesFor(t: any): Record<string, any> {
  const s: Record<string, any> = {
    empty: Z, some: { units: 3, tens: 2, hundreds: 1, thousands: 0 }, u12: { ...Z, units: 12 }, t16: { ...Z, tens: 16 },
    h1: { ...Z, hundreds: 1 }, h1t6: { ...Z, hundreds: 1, tens: 6 }, h12: { ...Z, hundreds: 12 },
  };
  if (typeof t.numberA === 'number') s.a = std(t.numberA);
  if (typeof t.numberA === 'number' && typeof t.numberB === 'number') {
    s.b = std(t.numberB);
    s.sum = std(t.numberA + t.numberB);
    if (t.numberA >= t.numberB) s.diff = std(t.numberA - t.numberB);
    s.aPlus = { ...std(t.numberA), units: std(t.numberA).units + 10, tens: Math.max(0, std(t.numberA).tens - 1) };
  }
  if (t.requiredCounts) s.req = { ...Z, ...t.requiredCounts };
  return s;
}

const tasks: any[] = [...SESSION1_TASKS];
for (const m of [3, 4, 5, 6, 7, 8] as const) for (const path of ['green_path', 'remediation_path'] as const) {
  tasks.push(...getSessionTasks(m, path));
  if (m <= 7) for (const b of ['reinforcement', 'challenge'] as const) tasks.push(...getSessionBranchTasks(m, b, path));
}
const main = MAIN as Record<string, Record<string, string | null>>;
const APPROVED: Record<string, string> = { s3_r_t7: 'conceptual' };

describe('SOCRATIC_CARD_SHOWN.error_category is what main recorded (research data)', () => {
  it('the fixture covers every exercise', () => {
    expect(tasks.length).toBeGreaterThan(120);
    for (const t of tasks) expect(main[t.id], t.id).toBeTruthy();
  });

  it('every exercise, every board state: the card carries main\'s category, except the approved s3_r_t7', () => {
    const diff: string[] = [];
    for (const t of tasks) {
      for (const [name, counts] of Object.entries(statesFor(t))) {
        const want = APPROVED[t.id] ?? main[t.id][name];
        const got = SocraticEngine.getSynchronousTaskHint(t, counts).error_category ?? null;
        if (got !== want) diff.push(`${t.id} ${name}: main ${want}, now ${got}`);
        expect(researchErrorCategory(t, counts), `${t.id} ${name}`).toBe(want);
      }
    }
    expect(diff).toEqual([]);
  });

  it('s3_r_t7 was null on main in the states the child meets first (the approved change)', () => {
    expect(main.s3_r_t7.empty).toBeNull();
    expect(main.s3_r_t7.h1).toBeNull();
  });
});
