import { describe, it, expect } from 'vitest';
import { SocraticEngine } from '@/infrastructure/services/SocraticEngine';
import { researchErrorCategory } from '@/infrastructure/services/socraticResearchCategory';
import { SESSION1_TASKS, getSessionTasks } from '@/data/sessionTasks';
import { getSessionBranchTasks } from '@/data/sessionBranchTasks';
import MAIN from './fixtures/main-socratic-error-categories.json';

/**
 * Research data (owner's standing rule, 28.9.2026): the error_category a
 * static card records in SOCRATIC_CARD_SHOWN (Module 18's distribution) is
 * the value main recorded for the same exercise and board. The fixture was
 * generated by running SocraticEngine.getSynchronousTaskHint on origin/main
 * (acccee7c, and again on 15499291 after #125 changed the instructions: the
 * same values) over every exercise of meetings 1 and 3–8, both tracks and the
 * choice path, in the board states below.
 *
 * The one approved change (שהB.1): s3_r_t7, null → 'conceptual'.
 *
 * Since the owner's decision of 28.9.2026 (X19) this value is no longer what
 * SOCRATIC_CARD_SHOWN records: a static card is recorded with error_category
 * null, and only the engine's classification is stored
 * (SocraticCard_OneFinalCard.test.tsx). The static card's own value is kept
 * as it was.
 */
const P = ['units', 'tens', 'hundreds', 'thousands'] as const;
const std = (n: number) => Object.fromEntries(P.map((p, i) => [p, Math.floor(n / 10 ** i) % 10])) as any;
const Z = { units: 0, tens: 0, hundreds: 0, thousands: 0 };
function statesFor(t: any): Record<string, any> {
  const s: Record<string, any> = {
    empty: Z, some: { units: 3, tens: 2, hundreds: 1, thousands: 0 }, u12: { ...Z, units: 12 }, t16: { ...Z, tens: 16 },
    h1: { ...Z, hundreds: 1 }, h1t6: { ...Z, hundreds: 1, tens: 6 }, h12: { ...Z, hundreds: 12 },
  };
  if (typeof t.numberA === 'number') s.a = std(t.numberA);
  if (typeof t.numberA === 'number' && typeof t.numberB === 'number') {
    s.b = std(t.numberB);
    s.sum = std(t.numberA + t.numberB);
    if (t.numberA >= t.numberB) s.diff = std(t.numberA - t.numberB);
    s.aPlus = { ...std(t.numberA), units: std(t.numberA).units + 10, tens: Math.max(0, std(t.numberA).tens - 1) };
  }
  if (t.requiredCounts) s.req = { ...Z, ...t.requiredCounts };
  return s;
}

const tasks: any[] = [...SESSION1_TASKS];
for (const m of [3, 4, 5, 6, 7, 8] as const) for (const path of ['green_path', 'remediation_path'] as const) {
  tasks.push(...getSessionTasks(m, path));
  if (m <= 7) for (const b of ['reinforcement', 'challenge'] as const) tasks.push(...getSessionBranchTasks(m, b, path));
}
/**
 * Exercises added after the fixture was taken, so main has no value for them.
 * NOT from main: new on 29.9.2026 (owner) — meeting 1's three refresh exercises
 * 368 (the value of a digit), 482 (in words) and 703 (in words, a 0 in the
 * tens; added later the same day). The values are what the
 * engine gives them on the day they were added (null in every state, as for
 * the other representation exercises of meeting 1), locked here so a later
 * change shows up the same way a change to main's values does.
 */
const NONE = { empty: null, some: null, u12: null, t16: null, h1: null, h1t6: null, h12: null, a: null, req: null };
const ADDED_AFTER_MAIN: Record<string, Record<string, string | null>> = {
  s1_r_value368: NONE,
  s1_r_words482: NONE,
  s1_r_words703: NONE,
};
/**
 * Exercises the owner redesigned after the fixture was taken (30.9.2026): the
 * first exercise of station 7, both paths, was "prove that 12 tens and 5 units
 * are 1 hundred, 2 tens and 5 units" with two saved representations; it is now
 * a representation exercise — build the blocks, group ten, write the number
 * (sessionTasks.ts). Main's values belong to the old exercise; these are what
 * the engine gives the new one on the day of the redesign — null on the three
 * boards with ten or more blocks in a column (u12, t16, h12), 'procedural'
 * everywhere else — locked the same way.
 */
const S7_GROUPING = { empty: 'procedural', some: 'procedural', u12: null, t16: null, h1: 'procedural', h1t6: 'procedural', h12: null, a: 'procedural', req: 'procedural' };
const REDESIGNED_AFTER_MAIN: Record<string, Record<string, string | null>> = {
  s7_r_t1: S7_GROUPING,
  s7_g_t1: S7_GROUPING,
};
const main = { ...(MAIN as Record<string, Record<string, string | null>>), ...ADDED_AFTER_MAIN, ...REDESIGNED_AFTER_MAIN };
const APPROVED: Record<string, string> = { s3_r_t7: 'conceptual' };

describe('SOCRATIC_CARD_SHOWN.error_category is what main recorded (research data)', () => {
  it('the fixture covers every exercise', () => {
    expect(tasks.length).toBeGreaterThan(120);
    for (const t of tasks) expect(main[t.id], t.id).toBeTruthy();
  });

  it('the exercises added after main are really new: main never recorded them', () => {
    for (const id of Object.keys(ADDED_AFTER_MAIN)) {
      expect((MAIN as Record<string, unknown>)[id], id).toBeUndefined();
      expect(tasks.some((t) => t.id === id), id).toBe(true);
    }
  });

  it('every exercise, every board state: the card carries main\'s category, except the approved s3_r_t7', () => {
    const diff: string[] = [];
    for (const t of tasks) {
      for (const [name, counts] of Object.entries(statesFor(t))) {
        const want = APPROVED[t.id] ?? main[t.id][name];
        const got = SocraticEngine.getSynchronousTaskHint(t, counts).error_category ?? null;
        if (got !== want) diff.push(`${t.id} ${name}: main ${want}, now ${got}`);
        expect(researchErrorCategory(t, counts), `${t.id} ${name}`).toBe(want);
      }
    }
    expect(diff).toEqual([]);
  });

  it('s3_r_t7 was null on main in the states the child meets first (the approved change)', () => {
    expect(main.s3_r_t7.empty).toBeNull();
    expect(main.s3_r_t7.h1).toBeNull();
  });
});
