// MathmatiCore PRD — batch 4 (9.10.2026) — technical alignment: 37 exact replacements. Safe to run more than once.
// Aligns purely technical statements with what the code does today (owner approval, AGENTS.md Rule 1 way 2).
// Each entry: [old, new, marker, nth, total]. marker = text whose presence means this edit was already applied;
// nth/total = replace the nth of exactly `total` occurrences (used only where the same code line appears twice).
var EDITS = [
  ["active_class_session (שידור מצב סשן פעיל ומצב מקרן כיתתי: projector_mode).", "active_class_session (שידור מצב הסשן הפעיל, מודול 14 §ב0), system_control/projector_mode (מצב המקרן הכיתתי: projector_mode, projector_mode_updated_at ו-updated_by_teacher_id, מודול 15)."],
  ["and active class projector broadcasting (active_class_session).", "the active class session broadcast (active_class_session) and the class projector state (system_control/projector_mode)."],
  ["השדות projector_mode, projector_mode_updated_at ו-updated_by_teacher_id במסמך הכיתה ב-Firestore (מודול 4) משקפים את אותו מצב כרשומה הקנונית.", "מצב המקרן אינו נכתב למסמך הכיתה ב-Firestore: הצומת system_control/projector_mode הוא הרשומה היחידה של המצב, והשדות projector_mode ו-projector_mode_updated_at במסמך הכיתה (מודול 4) אינם מתעדכנים בהפעלת המקרן או בכיבויו."],
  ["exercise_id, operation_type, payload.", "exercise_id, operation_type, payload; ה-payload הוא אירוע הטלמטריה כולו, כולל column_index כשהאירוע נושא אותו, והוא נשלח ל-telemetry_logs כפי שנשמר בתור, בתוספת synced_at."],
  ["עם התרגיל הוא שואל על 425 − 162 בטור העשרות.", "עם התרגיל הוא שואל על 425 − 162 בטור העשרות. בתרגילים שאינם חיבור או חיסור (ייצוג, גמישות, חלק חסר ומשימת החקר של הרכבים משתנים), וכן בתרגיל שאין בו שני מספרים, השדה exercise_context אינו נשלח כלל, והתרגיל מגיע למנוע רק דרך task_context."],
  ["exercise_context: GeminiExerciseContext; // Appendix A §6", "exercise_context?: GeminiExerciseContext; // Appendix A §6; omitted when the exercise is not an addition or a subtraction"],
  ["Carry the exercise itself in every request as exercise_context (operation, both operands, the active column and the sub-problem the learner is on) alongside workspace_state and recent_actions.", "Carry the exercise itself as exercise_context (operation, both operands, the active column and the sub-problem the learner is on) alongside workspace_state and recent_actions in every request about an addition or a subtraction; omit exercise_context for representation, flexibility, missing-part and changing-compositions inquiry exercises and for any exercise without two operands, which reach the engine through task_context only."],
  ["הבקשה נושאת, בנוסף לשדות שלהלן, את התרגיל עצמו בשדה exercise_context, כנדרש במודול 13 §א:", "הבקשה נושאת, בנוסף לשדות שלהלן, את התרגיל עצמו בשדה exercise_context, כנדרש במודול 13 §א (בתרגילי חיבור וחיסור בלבד):"],
  ["// GeminiSocraticRequest carries: exercise_context: GeminiExerciseContext;", "// GeminiSocraticRequest carries: exercise_context?: GeminiExerciseContext; (additions and subtractions only)"],
  ["exercise_context: GeminiExerciseContext; // GeminiExerciseContext is defined above (Module 13 §א)", "exercise_context?: GeminiExerciseContext; // defined above (Module 13 §א); omitted when the exercise is not an addition or a subtraction"],
  ["sessions (מסמכי מפגש קבועים ושער אישור מורה)", "sessions (מסמכי מפגש ושער אישור מורה: מסמך אחד לכל לומד ולכל מפגש, שמזהה המסמך שלו הוא session_0N_student_K; הלקוח כותב מסמך כזה רק למפגש 2, בסיום המפגש, ועליו נקבע שער האישור)"],
  ["Use Cloud Firestore for canonical session documents (sessions),", "Use Cloud Firestore for canonical session documents (sessions: one document per learner and session, id session_0N_student_K, written by the client for session 2 only),"],
  ["export interface SessionDocument {", "export interface SessionDocument { // one per learner and session: sessions/session_0N_student_K (written for session 2)"],
  ["טריגר היסוס (45 שנ') או מחיקות (4) הופעלו.", "אחד מחמשת טריגרי החניכה של מודול 12 §ב הופעל: היסוס של 45 שניות, 4 טעויות או מחיקות ברצף באותו טור, 3 ביטולים רצופים (במפגש 8 בלבד), אי-ביצוע המרה נדרשת, או תשובה שגויה שנייה ברצף באותו תרגיל."],
  ["תרגיל נוכחי, helpRequested (boolean))", "תרגיל נוכחי, helpRequested (boolean); לצדם הרשומה נושאת שדות נוספים, ואין בה רשימת שדות סגורה: פרופיל התמיכה (מודול 19), pendingAdaptation, שער האישור והמסלול (routeStatus, teacher_gate_approved, pedagogicalPath, teacher_selected_path, gate_approved_at, gate_approved_by, מודול 20), שיקוף הציון והמסלול המומלץ של מסמך המפגש (session_score_percent, matrix_recommended_path), workspaceState, sessionState, completedMeetings, highestCompletedMeeting, error_category ו-errorCategoryDistribution (מודול 18), hesitating, isSocraticActive, handRaised, isStruggling, onlineStatus, lastActivityTimestamp, hasJoinedSession, forceReload ו-isBoardLocked. רשומה זו אינה הטיפוס AnonymousStudent של נספח א', המתאר את מסמך הלומד באוסף students ב-Firestore)"],
  ["support_profile_updated_by, active_session_id.", "support_profile_updated_by, active_session_id. The client writes student_id, class_id, school_id, created_at and active_session_id to this document on session activation; the support_profile_* fields are written to and read from the learner's RTDB record users/students/{studentId} (Module 19), a separate live record whose fields are not a closed list."],
  ["שדות התלמיד הרלוונטיים בשרת (חלק מסכימת ה-students הקנונית המלאה במודול 4): student_id (1-12), class_id, school_id, support_profile_id, support_profile_version, support_profile_updated_at, support_profile_updated_by.", "שדות הפרופיל, בשמות של הטיפוס AnonymousStudent שבנספח א' (support_profile_id, support_profile_version, support_profile_updated_at, support_profile_updated_by), נשמרים ברשומת הלומד ב-Realtime Database ‏(users/students/{studentId}, מודול 4): המורה בלבד כותבת אותם, והלקוח של הלומד קורא אותם משם. מסמך הלומד באוסף students ב-Firestore נושא את student_id (1-12), class_id, school_id, created_at ו-active_session_id."],
  ["Store support profile configuration strictly on the student document fields listed in §B (which match Appendix A's AnonymousStudent interface exactly; do not introduce additional or renamed fields).", "Store support profile configuration strictly in the four support_profile_* fields listed in §B, named exactly as in Appendix A's AnonymousStudent, on the learner's RTDB record users/students/{studentId}; do not rename them."],
  ["export interface AnonymousStudent {", "export interface AnonymousStudent { // Firestore students/{id}; the support_profile_* fields live on the RTDB record users/students/{id} (Module 19)"],
  ["קריאה: מורשים לקרוא אך ורק את מסמך התלמיד האישי שלהם (/students/{studentId}).", "קריאה: מורשים לקרוא את מסמך התלמיד האישי שלהם (/students/{studentId}), את מסמכי המפגש שלהם באוסף sessions, את אירועי הטלמטריה, מסמכי הרפלקציה ומצבי העבודה (workspace_states) שלהם, ואת האוספים שאין בהם נתוני לומדים: curriculum_catalog, system_control ו-schools."],
  ["restricting their read access solely to their own student document.", "restricting their read access to their own student document, their own sessions, telemetry_logs, srl_reflections and workspace_states documents, and the learner-free collections curriculum_catalog, system_control and schools."],
  ["ExerciseTemplate הוא מבנה הרשומה של תרגיל באוסף קטלוג תוכנית הלימודים ב-Firestore (מודול 26). מנוע התרגילים בצד הלקוח פועל על הטיפוס SessionTask, המכיל את אותם שדות פדגוגיים (מפגש, סדר, מסלול, סוג, פעולה, מחוברים, תוצאה צפויה, המרות נדרשות וטוריהן, תווית, נראות הלבנים והפעלת כרטיס החניכה) בשמות משלו. שני הטיפוסים מתארים את אותו תרגיל; הקטלוג נשמר במבנה ExerciseTemplate, והריצה נעשית ב-SessionTask.", "מנוע התרגילים בצד הלקוח פועל על הטיפוס SessionTask, שסוגי התרגיל שלו (type) הם session1_intro, addition_simple, place_value_zero, flexible_decomp, vertical_addition, small_change, missing_element ו-representation; הוא מתאר את תרגילי כל התחנות, גם את תחנות 1–2 ואת משימות החקר. גם קטלוג תוכנית הלימודים ב-Firestore (מודול 26) שומר תרגילים במבנה SessionTask: מסמך אחד לכל מאגר (session_1, ולמפגשים 3–8 session_N_green_path ו-session_N_remediation_path), ובו השדות session_number, learning_path, updated_at והמערך tasks. ExerciseTemplate אינו מבנה הרשומה בקטלוג: הוא משמש לתיאור התרגילים שבהם נרשמו שגיאות בבקשת הדוח למנוע (failed_exercises, סעיף 7), והשרת ממיר אליו כל SessionTask (representation ל-'representation', missing_element ל-'inquiry', ושאר הסוגים ל-'addition' או ל-'subtraction')."],
  ["כל תרגיל בקטלוג מוגדר לפי הטיפוס ExerciseTemplate (נספח א', סעיף 2), והוא משויך למסלול למידה יחיד בשדה learning_path.", "כל תרגיל בקטלוג מוגדר לפי הטיפוס SessionTask (נספח א', סעיף 2), והוא שייך למאגר של מסלול למידה יחיד: הקטלוג שומר מסמך אחד לכל מאגר, ובו השדות session_number, learning_path, updated_at והמערך tasks."],
  ["Define every catalog exercise as an ExerciseTemplate (Appendix A §2) bound to exactly one learning_path.", "Define every catalog exercise as a SessionTask (Appendix A §2) in a bank bound to exactly one learning_path: one Firestore document per bank, holding session_number, learning_path, updated_at and the tasks array."],
  ["ומנסח בשפה טבעית תיאור של פערי הידע הספציפיים שאותרו וכן המלצות הוראה מותאמות להמשך העבודה בכיתה הפיזית.", "ומנסח בשפה טבעית תיאור של פערי הידע הספציפיים שאותרו וכן המלצות הוראה מותאמות להמשך העבודה בכיתה הפיזית. במפגש 1, שאין בו ציון, הבקשה נשלחת בלי ציון ובלי מסגרת המלצה (session_score_percent ו-recommendation_tier הם null), ולצדה רשימת פעולות הממשק שהלומד לא ביצע (tools_not_used)."],
  ["  session_score_percent: number;", "  session_score_percent: number | null; // null in session 1, which has no score (Module 23)", "session_score_percent: number | null; // null in session 1, which has no score (Module 23)", 1, 2],
  ["  session_score_percent: number;", "  session_score_percent: number | null; // null in session 1, which has no score (Module 14 §ב)", "session_score_percent: number | null; // null in session 1, which has no score (Module 14 §ב)"],
  ["  recommendation_tier: 'below_50' | 'between_50_75' | 'above_75';", "  recommendation_tier: 'below_50' | 'between_50_75' | 'above_75' | null; // null in session 1; session 1 also sends tools_not_used?: string[] (Module 23)", "| null; // null in session 1; session 1 also sends tools_not_used?: string[] (Module 23)", 1, 2],
  ["  recommendation_tier: 'below_50' | 'between_50_75' | 'above_75';", "  recommendation_tier: 'below_50' | 'between_50_75' | 'above_75' | null; // null in session 1; session 1 also sends tools_not_used?: string[] (Module 14 §ב)", "| null; // null in session 1; session 1 also sends tools_not_used?: string[] (Module 14 §ב)"],
  ["  failed_exercises: ExerciseTemplate[];", "  failed_exercises: ExerciseTemplate[]; // whitelisted fields; operands, expected_result and learning_path may be null (Module 23)", "failed_exercises: ExerciseTemplate[]; // whitelisted fields; operands, expected_result and learning_path may be null (Module 23)", 1, 2],
  ["  failed_exercises: ExerciseTemplate[];", "  failed_exercises: ExerciseTemplate[]; // whitelisted fields; operands, expected_result and learning_path may be null; no blocks_visible or socratic_enabled", "failed_exercises: ExerciseTemplate[]; // whitelisted fields; operands, expected_result and learning_path may be null; no blocks_visible or socratic_enabled", 2, 2],
  ["  telemetry_summary: TelemetryPayload<TelemetryEventType>[];", "  telemetry_summary: TelemetryPayload<TelemetryEventType>[]; // every event of the session as event_type, exercise_id, column_index and whitelisted details; identical consecutive events merged with count (Module 23)", "// every event of the session as event_type, exercise_id, column_index and whitelisted details; identical consecutive events merged with count (Module 23)", 1, 2],
  ["  telemetry_summary: TelemetryPayload<TelemetryEventType>[];", "  telemetry_summary: TelemetryPayload<TelemetryEventType>[]; // every event of the session as event_type, exercise_id, column_index and whitelisted details; identical consecutive events merged with count (Module 23 §ב)", "identical consecutive events merged with count (Module 23 §ב)", 2, 2],
  ["קורא אך ורק ממסמך ה-store_cache וחסום מביצוע שאילתות חיות יקרות ב-Firestore.", "מסך הסקירה קורא את המדדים המצטברים אך ורק ממסמך ה-store_cache, ואינו מריץ שאילתות חיות יקרות על נתוני הלמידה ב-Firestore; לצדם הוא מציג את יומן audit_logs מ-Realtime Database. שאר מסכי המנהל קוראים וכותבים ישירות את הנתונים שהם מנהלים, ואין בהם נתוני למידה: בתי הספר, הכיתות, המורים ומגבלת הלומדים ב-Realtime Database (schools, classes, public_classes, users/teachers, system_control/globalStudentLimit), רשימת המורשים authorizedTeachers ומסמך הכיתה ב-Firestore (מודול 25), הקטלוג curriculum_catalog וכיול הרדאר system_control/trace_calibration (מודול 26), והודעות messages (מודולים 22, 28)."],
  ["מאזין תמונת-מצב ממוקד (Snapshot Listener) למסמך המפגש הפעיל בלבד (ללא קריאות גלובליות יקרות).", "הלובי מאזין בזמן אמת לצמתים ממוקדים ב-Realtime Database בלבד: שידור המפגש הפעיל active_class_session (מודול 14 §ב0), רשומת הלומד users/students/{studentId}, מצב המקרן system_control/projector_mode (מודול 15) ובחירת המורה system_control/teacher_gender; הוא אינו מאזין למסמכי Firestore (ללא קריאות גלובליות יקרות)."],
  ["Render a clean dashboard displaying only the current active session object fetched from the student state database. Use targeted listeners to minimize read costs.", "Render a clean dashboard displaying only the current active session object, read from the Realtime Database broadcast active_class_session. Use targeted RTDB listeners only (active_class_session, the learner's own users/students/{studentId} record, system_control/projector_mode and system_control/teacher_gender) to minimize read costs; the lobby listens to no Firestore document."],
  ["Wait at most 10 seconds for the AI analysis layer, then emit the report with the deterministic layer and the fixed fallback sentence.", "Wait at most 10 seconds for the AI analysis layer of a learner report, and at most 20 seconds for that of a class report, then emit the report with the deterministic layer and the fixed fallback sentence."]
];

function applyEdits() {
  var body = DocumentApp.getActiveDocument().getBody();
  var done = 0, already = 0, skipped = 0;
  EDITS.forEach(function (e) {
    var oldText = e[0], newText = e[1], marker = e[2] || e[1], nth = e[3] || 1, total = e[4] || 1;
    if (body.findText(esc_(marker))) { already++; return; }
    var matches = [], r = body.findText(esc_(oldText));
    while (r) { matches.push(r); r = body.findText(esc_(oldText), r); }
    if (matches.length !== total) {
      skipped++;
      Logger.log('נמצא ' + matches.length + ' פעמים במקום ' + total + ', דולג: ' + oldText.slice(0, 50));
      return;
    }
    var found = matches[nth - 1];
    var t = found.getElement().asText();
    var s = found.getStartOffset();
    t.deleteText(s, found.getEndOffsetInclusive());
    t.insertText(s, newText);
    done++;
    Logger.log('הוחלף: ' + oldText.slice(0, 50));
  });
  Logger.log('הוחלפו: %s. כבר היו מעודכנים: %s. דולגו: %s.', done, already, skipped);
}

function esc_(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
