// MathmatiCore PRD — batch 3 (8.10.2026), part b: 51 exact replacements. Safe to run more than once.
// Run apply_edits_batch3a.gs first; this one assumes it has run.
// Each entry: [old, new, marker, nth, total]. marker = text whose presence means this edit was already applied;
// nth/total = replace the nth of exactly `total` occurrences (used only where the same code line appears twice).
var EDITS = [
  ["העותק השמור של אותו מפגש, סימן הסיום שלו ורישום ההשלמה שלו (מודול 14 §ב0), והמפגש הגבוה ביותר שהושלם יורד למפגש הקודם;", "העותק השמור של אותו מפגש וסימן הסיום שלו, והמפגש הגבוה ביותר שהושלם מחושב מחדש כמפגש הגבוה ביותר שסימן ההשלמה שלו עדיין קיים; רישום ההשלמה של אותו מפגש (מודול 14 §ב0) נשמר ומוצג בדוח בסעיף \"לפני האיפוס\";"],
  ["במפגש 8 גם הרפלקציה. נמחקים רק מסמכי אותו מפגש ב-Cloud Firestore.", "במפגש 8 גם הרפלקציה. ב-Cloud Firestore נמחק רק מסמך אותו מפגש באוסף sessions (ובמפגש 8 גם מסמך הרפלקציה שלו); אירועי הטלמטריה, הדוחות ורישום ההשלמה נשארים, והדוחות סופרים מאז רק את הריצה החדשה (מודול 23)."],
  ["רשימת הפעולות, הדוחות והרפלקציות ב-Cloud Firestore נשמרות בגיבוי ואינן נמחקות.", "רשימת הפעולות, הדוחות והרפלקציות ב-Cloud Firestore נכללות בגיבוי ונשארות במערכת."],
  ["איזה מפגש מאופס.", "איזה מפגש מאופס באיפוס לומד בודד."],
  ["(2) אחרת, המפגש שהלומד נכנס אליו; (3) אחרת אין מפגש לאפס, והאיפוס נדחה בלי למחוק דבר.", "(2) אחרת, המפגש שהלומד נכנס אליו, אלא אם הלומד כבר סיים אותו: אז הלומד נמצא בין מפגשים, והאיפוס נדחה בלי למחוק דבר, בהודעה \"תלמיד N סיים את מפגש M, ועכשיו הוא לא באמצע מפגש. כדי לאפס מפגש שהסתיים, פתחו אותו לכיתה ואפסו אותו בזמן שהוא פתוח, או בחרו איפוס מוחלט של התלמיד.\" (החלטת בעל המוצר, 2.10.2026); מפגש כיתה פתוח מאופס גם ללומד שכבר סיים אותו, וכך המורה מאפסת בכוונה מפגש שהסתיים; (3) אחרת אין מפגש לאפס, והאיפוס נדחה בלי למחוק דבר."],
  ["איזה מפגש מתאפס.", "איזה מפגש מתאפס באיפוס הכיתה."],
  ["אין ברירת מחדל נוספת: באיפוס לומד בודד השרת מאפס את המפגש שרשומת הלומד מצביעה עליו, אך בכיתה", "אין ברירת מחדל נוספת: באיפוס לומד בודד, כשאין מפגש פתוח, השרת מאפס את המפגש שהלומד נמצא בו (ראו \"איזה מפגש מאופס באיפוס לומד בודד\" לעיל), אך בכיתה"],
  ["מפגשים קודמים, הקלטות, הודעות הצ'אט, הטלמטריה, הדוחות והרפלקציות נשארים.", "במפגש 8 נמחקות גם הרפלקציות של המפגש, כמו באיפוס לומד בודד, כדי שהכיתה תוכל לבצע את המפגש מחדש. המפגש הפתוח מתאפס לכל שנים עשר הלומדים, גם למי שכבר סיים אותו; שאר המפגשים אינם משתנים. מפגשים קודמים, הקלטות, הודעות הצ'אט, הטלמטריה והדוחות נשארים."],
  ["סימני הסיום ורישומי ההשלמה, ודוחות הכיתה (מודול 23). מחייב גיבוי מלא לפני הביצוע.", "סימני הסיום ורישומי ההשלמה, ודוחות הכיתה (מודול 23). מחייב גיבוי מלא לפני הביצוע. תופעות הלוואי של איפוס מערכת: המפגש הפעיל נסגר, מצב המקרן כבה, התראות הרדאר נמחקות, הצמתים replays, telemetry_sessions, reflections, approved_tasks ו-ai_pending_approvals ב-Realtime Database נמחקים, ומטמון המנהל (store_cache) מחושב מחדש. האוספים נמחקים במלואם, ללא סינון לפי כיתה (בפיילוט יש כיתה אחת). איפוס מערכת הוא הפעולה היחידה שמוחקת טלמטריה, ותמיד אחרי גיבוי."],
  ["אינו נוגע בשום נתון למידה, טלמטריה או מסמך סשן. אינו מחייב גיבוי.", "אינו נוגע בשום נתון למידה, טלמטריה או מסמך סשן. אינו מחייב גיבוי. איפוס התראות חל תמיד על כל הכיתה, ואין לו יעד של לומד בודד."],
  ["אם הגיבוי נכשל מכל סיבה, המחיקה אינה מתבצעת כלל", "אם הגיבוי נכשל גם בדרייב וגם ב-Cloud Storage (ראו להלן), המחיקה אינה מתבצעת כלל"],
  ["הגיבוי מיוצא כקובץ אל הדרייב, לתיקייה `03 גיבויי איפוס` (הנוצרת מאליה בכתיבה הראשונה, בנפרד מדוחות הלומדים, מנתוני המחקר ומדוחות המנהל), באמצעות Cloud Function ייעודית, בהתאם לתשתית הקיימת ב-exportAdminReportToDrive.", "הגיבוי מיוצא כקובץ אל הדרייב, לתיקייה `3 גיבויים` (מודול 23, \"תיקיות הדרייב\"), באמצעות Cloud Function ייעודית, בהתאם לתשתית הקיימת ב-exportAdminReportToDrive. השרת ממתין לכתיבה לדרייב עד 90 שניות. אם הכתיבה לדרייב נכשלה או לא הסתיימה בתוך 90 שניות, הגיבוי נכתב ל-Cloud Storage, לנתיב backups/{class_id}/ שהמורה של הכיתה יכולה לקרוא, והאיפוס ממשיך; גיבוי גדול מ-30MB נכתב ל-Cloud Storage ישירות. רישום האיפוס מציין היכן נשמר הגיבוי (backup_channel: 'drive' או 'storage'). פעם ביום משימת שרת מעתיקה לתיקייה `3 גיבויים` בדרייב כל גיבוי שנשמר רק ב-Cloud Storage, מעדכנת את הקישור ברישום האיפוס ומשאירה את העותק ב-Cloud Storage; הדשבורד מסמן איפוס שהגיבוי שלו עוד לא הגיע לדרייב."],
  ["הקובץ כולל את כלל נתוני הטלמטריה, מסמכי הסשן, מצבי מרחב העבודה ונתוני הרפלקציה של הלומדים הנמחקים, תחת מזהים אנונימיים 1 עד 12 בלבד.", "הקובץ כולל את כל מה שבהיקף האיפוס כפי שהיה ברגע הגיבוי: רשומות הלומדים במלואן (כולל ההגדרות: פרופיל התמיכה ומצב השקט החזותי), נתוני הטלמטריה שהגיעו לשרת, מסמכי הסשן, מצבי מרחב העבודה, הרפלקציות, הצ'אט, הקלטות השחזור, רישומי ההשלמה והדוחות. הלומדים מזוהים בו במזהים 1 עד 12 בלבד; הקובץ כולל גם את טקסט הצ'אט כפי שנכתב ואת מזהה המורה שביצעה את האיפוס. אירועים שעדיין המתינו בתור של מכשיר בזמן האיפוס מגיעים אחריו ואינם בגיבוי. הקובץ הוא קובץ JSON (mathmaticore-reset-backup, גרסה 2), ושמו לפי סוג האיפוס: \"גיבוי DD.MM.YYYY HH-mm - תלמיד NN מפגש M.json\" (איפוס מפגש של לומד), \"גיבוי DD.MM.YYYY HH-mm - תלמיד NN מוחלט.json\" (איפוס מוחלט של לומד), \"גיבוי DD.MM.YYYY HH-mm - כל הכיתה מפגש M.json\" (איפוס המפגש לכל הכיתה) ו-\"גיבוי DD.MM.YYYY HH-mm - מערכת.json\" (איפוס מערכת). אין שחזור אוטומטי מגיבוי; הגיבוי הוא ראיה מחקרית לקריאה."],
  ["קובץ הגיבוי של פעולה זו נקרא Backup_class_active_session_ ואחריו חותמת הזמן.", "קובץ הגיבוי של פעולה זו נקרא \"גיבוי DD.MM.YYYY HH-mm - כל הכיתה מפגש M.json\" (סעיף ג)."],
  ["רישום זה אינו נמחק על ידי אף פעולת איפוס, לרבות איפוס מערכת.", "רישום זה אינו נמחק על ידי אף פעולת איפוס, לרבות איפוס מערכת. ביומן נרשמים גם ייצוא נתוני המחקר (מודול 24) והורדת המפגש (מודול 21), עם reset_level: 'export', באותו מבנה ResetAuditEntry: affected_student_ids של הלומדים שבייצוא, backup_file_url המצביע על הקבצים שנוצרו (או null בהורדה למחשב), backup_status: 'not_required', reset_reason: 'other' עם reason_note המתאר את הייצוא, ו-records_deleted_count: 0. כתובת הדוא\"ל של מי שביצעה פעולה אינה נשמרת בשום רישום. הרישום נכתב לפני המחיקה עם deletion_status: 'in_progress', ומתעדכן בסופה ל-'completed', או ל-'partial' אם חלק מהמחיקה נכשל. מחיקה שנעצרה באמצע אינה מוחזרת לאחור, והרישום נשאר 'in_progress' או 'partial'; איפוס חוזר מגבה את המצב החלקי בקובץ גיבוי נוסף. רק איפוס שה-deletion_status שלו 'completed' נחשב איפוס בדוחות ובייצוא. בכל רגע מתבצע לכל היותר איפוס אחד לכל כיתה: בקשת איפוס נוספת לאותה כיתה בזמן שאיפוס מתבצע נדחית לפני הגיבוי, בהודעה \"איפוס אחר של הכיתה מתבצע כעת. נסו שוב בעוד רגע. לא נמחקו נתונים.\""],
  ["השדה records_deleted_count סופר רק רשומות שנמחקו; רשומה שאופסה במקומה אינה נספרת.", "השדה records_deleted_count סופר רק רשומות שנמחקו, כלומר מסמכי Cloud Firestore וצמתי Realtime Database; רשומה שאופסה במקומה אינה נספרת. created_at הוא שעת השרת שבה נכתב הרישום. reason_note מוגבלת ל-500 תווים ועוברת בשרת את סינון ה-PII (מודול 22 §ב)."],
  ["reset_level: 'alerts' | 'single_student' | 'system';", "reset_level: 'alerts' | 'single_student' | 'system' | 'export';"],
  ["session_number?: number | null; // level 2 with 'active_session': the session that was restarted", "session_number?: number | null; // level 2 with 'active_session': the session that was restarted  \n  created_at: number; // server time the entry was written  \n  backup_channel?: 'drive' | 'storage' | null; // where the backup was written (Module 23א §ג)  \n  backup_drive_copied_at?: number | null; // set by the daily job when a Storage-only backup reaches Drive  \n  deletion_status?: 'not_required' | 'in_progress' | 'completed' | 'partial'; // only 'completed' counts as a reset in reports and exports", "// only 'completed' counts as a reset in reports and exports"],
  ["המורה מבצעת איפוס מערכת בעוד חיבור הרשת אינו יציב והכתיבה לדרייב נכשלת.", "שני תרחישים נפרדים. (1) המורה מאשרת איפוס מערכת, וחיבור הרשת שלה נופל מיד אחרי האישור. (2) המורה מבצעת איפוס מערכת, והכתיבה של השרת לדרייב נכשלת."],
  ["אף נתון אינו נמחק, נרשם ב-reset_audit_log רישום עם backup_status: 'failed', והמורה מקבלת הודעה שהאיפוס בוטל.", "(1) האיפוס מתבצע כולו בשרת ואינו תלוי בחיבור המורה: השרת משלים את הגיבוי ואת המחיקה, ותוצאת האיפוס מוצגת למורה כשהחיבור שלה חוזר. (2) אחרי 90 שניות לכל היותר הגיבוי נכתב ל-Cloud Storage (backups/{class_id}/), הרישום נושא backup_channel: 'storage', והאיפוס ממשיך; משימת השרת היומית מעתיקה את הגיבוי לדרייב. רק אם גם הכתיבה ל-Cloud Storage נכשלת, אף נתון אינו נמחק, נרשם ב-reset_audit_log רישום עם backup_status: 'failed', והמורה מקבלת הודעה שהאיפוס בוטל."],
  ["מנהל מערכת חסום מביצוע איפוס נתוני למידה, בהתאם לעקרון בידוד הכיתות.", "מנהל מערכת חסום מביצוע איפוס נתוני למידה, בהתאם לעקרון בידוד הכיתות. יומן האיפוסים (reset_audit_log) נקרא על ידי המורה של הכיתה בלבד; מנהל המערכת אינו קורא אותו."],
  ["write backup file to the Drive folder `03 גיבויי איפוס` via Cloud Function, await write acknowledgment, and only then delete. If the backup write fails or times out, abort the deletion entirely and surface a silent message.", "write the backup file to the flat Drive folder `3 גיבויים` via Cloud Function, waiting up to 90 seconds for Drive; if Drive fails or does not finish in time, or the backup exceeds 30MB, write it to Cloud Storage under backups/{class_id}/ (readable by the class teacher), record backup_channel ('drive' or 'storage') and proceed; only then delete. If both Drive and Storage fail, abort the deletion entirely and surface the silent message. A daily server job copies Storage-only backups to the Drive folder, updates the audit entry's link and keeps the Storage copy; the dashboard marks resets whose backup has not reached Drive yet. There is no automatic restore from a backup."],
  ["(board state, session state, that session's completion flag, saved per-session copy, completion mark and catch-up record; highest completed session steps back;", "(board state, session state, that session's completion flag, saved per-session copy and completion mark; recompute the highest completed session as the highest session whose completion mark is still set; keep that session's catch-up record and show it under \"לפני האיפוס\";"],
  ["while preserving the action log, reports and reflections in the backup", "while including the action log, reports and reflections in the backup and keeping them in the system"],
  ["show the target session in the confirmation dialog and in the post-reset message.", "show the target session in the confirmation dialog and in the post-reset message. With no session open, refuse to reset a session the learner already finished. Offer a whole-class target within level 2, only while a class session is open: reset that session's fields for all twelve learners (including those who finished it), delete only that session's documents (and in session 8 its reflections), keep everything else, and refuse with no deletion when no session is open. Allow at most one reset per class at a time."],
  ["this collection must be excluded from all deletion operations including system reset.", "this collection must be excluded from all deletion operations including system reset. Make it readable by the class teacher only. Log research exports and meeting downloads with reset_level: 'export' in the same ResetAuditEntry shape, never storing an e-mail address. Write the entry before deleting with deletion_status 'in_progress' and update it to 'completed' or 'partial'."],
  ["מחשבת מדדים מצטברים (אחוזי השלמת מפגשים, סך תרגילים שנפתרו, מדדי שגיאות גלובליים)", "מחשבת מדדים מצטברים (אחוזי השלמת מפגשים, סך תרגילים שנפתרו, מדדי שגיאות גלובליים; לכל מפגש ובסך הכול: לומד התחיל מפגש אם יש לו בו אירועים או מסמך מפגש, והשלים אותו אם מסמך המפגש מסומן is_completed או שהמפגש הגבוה ביותר שהשלים הגיע אליו; אחוז ההשלמה = מי שהשלים ÷ מי שהתחיל; תרגילים שנפתרו = תרגילים שונים שיש להם PROBLEM_COMPLETE; שיעור שגיאות הספרות = ספרות שגויות ÷ ספרות שהוקלדו; לצדם סך המחיקות, ביטולי הפעולה, ההיסוסים וכרטיסי החניכה, וממוצע ציון הניסיון הראשון של מי שהשלים, ללא מפגש 1)"],
  ["העמודה learning_path היא המסלול שהלומד עבד בו באותו מפגש, הנקראת מהרשומה הקנונית של הלומד.", "העמודה learning_path היא המסלול שהלומד עבד בו באותו מפגש, כהגדרתו במודול 23: המאגר שממנו נפתחו רוב התרגילים של הלומד באותו מפגש, ובהיעדר תרגיל שנפתח, המסלול שברשומה הקנונית; במפגשים 1 ו-2 העמודה ריקה."],
  ["שמות הקבצים בעברית, בקידוד שנפתח נכון באקסל.", "שמות הקבצים בעברית, בקידוד שנפתח נכון באקסל. חוזה העמודות. יחידת השורה בכל קובץ: פעולות — שורה לכל אירוע טלמטריה (כולל client_timestamp, sequence_number, device_id ו-server_received_at); מפגשים — שורה לכל לומד × מפגש; הקלטות — שורה לכל הקלטת שחזור של לומד במפגש; רפלקציות — שורה לכל רפלקציה; יומן איפוסים — שורה לכל רישום ב-reset_audit_log, כולל ייצואים. עמודות קובץ המפגשים, בסדר הזה: student_id, session_number, was_reset, reset_count, reset_times_iso, first_event_iso, last_event_iso, active_minutes, events, exercises_attempted, exercises_completed, compulsory_total, correct_first_attempt, first_attempt_score_percent, digits_entered, wrong_digits, deletions, undos, hesitations, hesitation_seconds_total, regroupings, socratic_cards, grid_openings, grid_reopenings, keyboard_lock_blocks, help_requests, fading_pairs, fading_accuracy_with_blocks, fading_accuracy_without_blocks, fading_seconds_with_blocks, fading_seconds_without_blocks, fading_guessed, fading_unpaired, self_correction_undos, self_correction_wrong_digits, self_correction_wrong_options, self_correction_percent, flexibility_completed, flexibility_first_try, flexibility_percent, flexibility_cumulative_completed, flexibility_cumulative_first_try, flexibility_cumulative_percent, mediation_cards, mediation_effective, mediation_percent, mediation_not_needed, mediation_cumulative_cards, mediation_cumulative_effective, mediation_cumulative_percent, reflection_submitted, recording_minutes, recording_truncated, learning_path, session_doc_score_percent, session_doc_recommended_path, session_doc_teacher_path, teacher_gate_approved, tool_drag, tool_decompose, tool_compose, tool_type, tool_undo, tool_trash, place_cue_scaffolds, persistence_exercises_with_errors, persistence_solved_without_help, persistence_without_help_percent, help_withdrawals, chat_help_requests, ואחריהן 11 עמודות הריצה שמאז האיפוס ו-4 עמודות זמן ההשלמה, בסדר שפורט לעיל. was_reset (\"כן\" או ריק), reset_count ו-reset_times_iso מתארים את האיפוסים שהושלמו וחלו על המפגש: איפוס של המפגש עצמו, ואיפוס מוחלט של הלומד או איפוס מערכת, שחלים על כל שמונת המפגשים. סדר העמודות קבוע: עמודה חדשה נוספת רק בסוף השורה, ועמודה קיימת אינה זזה ואינה משנה משמעות."],
  ["וחל איסור מוחלט על ייצוא מידע מזהה כלשהו.", "וחל איסור מוחלט על ייצוא מידע מזהה כלשהו. שער ה-PII של הייצוא בודק את כל הקבצים לכתובות דוא\"ל, למספרי טלפון ולמספרים בני תשע ספרות, ודוחה את הייצוא כולו אם נמצא אחד מהם; הוא אינו מזהה שמות, ולכן שם שנכתב בטקסט חופשי של המורה (הערת איפוס, הערת השלמה) אינו נחסם."],
  ["הקבצים נכתבים לדרייב במבנה תיקיות קשיח: `02 נתוני מחקר / כל המפגשים / תאריך` (ובייצוא של מפגש בודד, תיקיית המפגש במקום \"כל המפגשים\"), ובתוכה תיקייה לכל תאריך ייצוא. ייצוא חוזר אינו דורס קבצים קיימים אלא נשמר כתיקיית תאריך חדשה.", "הקבצים נכתבים לתיקייה השטוחה `2 נתוני מחקר` בדרייב (מודול 23, \"תיקיות הדרייב\"), בלי תיקיות משנה, בשמות כגון \"ייצוא 08.10.2026 14-30 - פעולות.csv\": התאריך והשעה של הייצוא לפי שעון ישראל, ואחריהם שם הקובץ. ייצוא חוזר, גם באותו יום, אינו דורס קבצים קיימים אלא נשמר כקבצים חדשים."],
  ["כל ייצוא נרשם ב-reset_audit_log עם reset_level: 'export' לצורך מעקב, ללא מחיקת נתונים כלשהם.", "כל ייצוא נרשם ב-reset_audit_log עם reset_level: 'export' לצורך מעקב, ללא מחיקת נתונים כלשהם וללא כתובת דוא\"ל (מודול 23א §ד)."],
  ["דוח המנהל המיוצא לדרייב נכתב לתיקייה `04 דוחות מנהל`, בנפרד מחומר המחקר.", "דוח המנהל המיוצא לדרייב נכתב לתיקייה `4 מנהל` (למשל \"דוח מנהל 08.10.2026.pdf\"), בנפרד מחומר המחקר. הדוח מכיל ספירות בלבד (בתי ספר, מורים, לומדים והתראות רדאר פעילות), ואינו מכיל כתובת דוא\"ל, לא של מנהל ולא של חשבון שירות."],
  ["Write to Drive under `02 נתוני מחקר / כל המפגשים / <date>`, creating the named folders on first write. Never overwrite an existing export; always create a new dated folder. Write the admin report under `04 דוחות מנהל`.", "Write the files to the flat Drive folder `2 נתוני מחקר` with names such as \"ייצוא 08.10.2026 14-30 - פעולות.csv\" (Israel time), creating the folder on first write. Never overwrite an existing export; a re-export, even on the same day, writes new files. Keep the sessions file's column order fixed and append new columns only at the end. Write the admin report, counts only and with no e-mail address, to the flat Drive folder `4 מנהל`."],
  ["המערכת מייצרת אוטומטית מזהים מספריים 1–12 בלבד עם הסיסמה הקבועה 10203040.", "המערכת מייצרת אוטומטית מזהים מספריים 1–12 בלבד, ולכל לומד קוד גישה אישי בן 4 ספרות: מספרו בכיתה בשתי ספרות (01–12) ואחריו שתי ספרות אקראיות, שאינן זוג ספרות זהות או עוקבות. רשימת הקודים גלויה למורה ולמנהל המערכת, וכל אחד מהם יכול לשנות קוד של לומד. כתובות הדוא\"ל של אנשי הצוות נשמרות רק לצורך הזדהות, ברשימת המורשים (authorizedTeachers) וב-Firebase Auth; יומן האיפוסים, הדוחות, דוח המנהל וקובצי המחקר אינם שומרים כתובת דוא\"ל."],
  ["(1–12, סיסמה 10203040)", "(1–12, לכל לומד קוד הגישה האישי שלו)"],
  ["כתיבה: מורשים לכתוב במסמכי telemetry_logs ו-workspace_states אך ורק אם מזהה התלמיד במסמך (student_id) תואם במדויק את מזהה ה-Auth המאומת שלהם (1–12), והמטען עומד בסכימת TelemetryDetailsMap (כולל כלל ה-column_index ממודול 5).", "כתיבה: מורשים ליצור מסמכים ב-telemetry_logs, לכתוב ב-workspace_states, ליצור ולעדכן את מסמך המפגש שלהם באוסף sessions (שדות המורה, כגון שער האישור והמסלול, נעולים בפניהם) וליצור מסמכי רפלקציה ב-srl_reflections, אך ורק אם מזהה התלמיד במסמך (student_id) תואם במדויק את מזהה ה-Auth המאומת שלהם (1–12). באירוע טלמטריה חוקי האבטחה בודקים את רשימת השדות המותרים וטיפוסיהם, את student_id, את מזהה המסמך מול idempotency_key, את server_received_at מול זמן הבקשה ואת כלל ה-column_index ממודול 5; את details הם בודקים כמפה בלבד, לא לפי הסכימה של כל סוג אירוע."],
  ["מורשים לקרוא נתוני טלמטריה ומצבי עבודה של תלמידי הכיתה המשויכת אליהם בלבד (class_id).", "מורשים לקרוא נתוני טלמטריה ומצבי עבודה של תלמידי הכיתה המשויכת אליהם בלבד (class_id). בפיילוט יש כיתה אחת, ולכן חוקי הקריאה בודקים את תפקיד המורה בלבד, ובדיקת class_id נעשית בפונקציות השרת ובדוחות; פריסה ליותר מכיתה אחת מחייבת להוסיף את בדיקת class_id לכל חוק קריאה. רישומי ההשלמה (catchup_records) ויומן האיפוסים (reset_audit_log) נקראים על ידי המורה של הכיתה בלבד; מסמך store_cache נקרא על ידי מנהל המערכת בלבד."],
  ["מנהל המערכת חסום מכל גישה, קריאה או כתיבה, לצומת זה.", "מנהל המערכת חסום מכל גישה, קריאה או כתיבה, לצומת זה. הצמתים schools, public_classes ו-classes ב-Realtime Database קריאים לכל זהות מאומתת, כי מסך הכניסה בונה מהם את הרשימות הנפתחות; אין בהם נתוני לומדים."],
  ["מפתחות API פרטיים והגדרות AI שמורים ב-Google Cloud Secret Manager בלבד ואינם נחשפים ללקוח.", "מפתחות API פרטיים והגדרות AI שמורים ב-Google Cloud Secret Manager בלבד ואינם נחשפים ללקוח. מנוע הבינה (Gemini) מופעל דרך ה-API בתשלום, שבתנאיו Google אינה משתמשת בבקשות לאימון מודלים. הבקשות למנוע מכילות מספרים, מזהים 1–12 ונוסחי תרגילים מהקטלוג בלבד; טקסט שכתב לומד אינו נשלח לעולם. מלאי הנתונים (לוועדת האתיקה). המערכת שומרת נתונים במקומות הבאים: Cloud Firestore (טלמטריה, מסמכי מפגש, רפלקציות, דוחות, רישומי השלמה, יומן האיפוסים, הודעות מורה–הנהלה, קטלוג והגדרות); Realtime Database (רשומות הלומדים ומצב מרחב העבודה, הקלטות השחזור עד 50MB ללומד למפגש, הצ'אט בין לומד למורה, המפגש הפעיל, ורשומות ישנות של לומדים והקלטות); Cloud Storage (קובצי PDF ו-CSV של הדוחות וגיבויי איפוס); Google Drive (התיקיות של מודול 23); Cloud Logging (יומני השרת, הכוללים כתובות דוא\"ל של אנשי צוות, למשך 30 יום); IndexedDB במכשירי הלומדים (תור הטלמטריה ומטמון הקטלוג); משתמשים אנונימיים ב-Firebase Auth; והבקשות ל-Gemini בצד Google. תקופת השמירה: נתוני המחקר נשמרים עד החלטת החוקר, ככל הנראה כשנה אחרי סיום הפיילוט. אין מחיקה מתוזמנת: הטלמטריה נמחקת רק באיפוס מערכת (רמה 3), ורק אחרי גיבוי."],
  ["and the payload matches the per-event-type schema in TelemetryDetailsMap.", "and the payload passes the field allowlist, type, idempotency-key, server_received_at and column_index checks (details is checked as a map only). Allow learners to create and update their own sessions document with staff fields frozen, and to create their own srl_reflections documents. Restrict catchup_records and reset_audit_log to the class teacher and store_cache to the admin."],
  ["Architect admin supports ticketing dashboard", "Architect admin support ticketing dashboard", "Architect admin support ticketing dashboard"],
  ["Filter and sanitize ticket contents via Cloud Functions, displaying strictly anonymous student IDs (1-12) linked to school_id and class_name.", "Display strictly anonymous student IDs (1-12) linked to school_id and class_name. The hub's feed is the teacher chat messages, already sanitized server-side by sendTeacherAdminMessage (Module 22); support_tickets documents, where used, are written directly by staff under the Security Rules schema check and the client-side PII check, with no Cloud Function in the path."],
  ["ברשת פעילה, הסנכרון ל-Firestore מתבצע ברקע לפי סדר FIFO קשוח.", "כל אירוע עובר תמיד דרך התור, גם ברשת פעילה, והסנכרון ל-Firestore מתבצע ברקע לפי סדר FIFO קשוח."],
  ["| 'PLACE_CUES_SHOWN';", "| 'PLACE_CUES_SHOWN'  \n  | 'CHAT_HELP_REQUESTED'  \n  | 'BOARD_CLEARED'  \n  | 'BRANCH_SELECTED';", "| 'BRANCH_SELECTED';"],
  ["is_correct: boolean | null; // null when the exercise defines no target digit for that column", "is_correct: boolean | null; // null when the exercise defines no target digit for that column  \n  input_target?: 'carry_circle'; // set when the digit was typed in a memory circle; absent for the result and operand rows", "input_target?: 'carry_circle'; // set when the digit was typed in a memory circle"],
  ["export interface DigitDeletedDetails { deleted_digit_value: number | null; }", "export interface DigitDeletedDetails { deleted_digit_value: number | null; input_target?: 'carry_circle'; } // input_target: set when the digit was deleted from a memory circle"],
  ["export interface HelpWithdrawnDetails {} // the learner cancelled a help call; not part of any formula (Module 23)", "export interface HelpWithdrawnDetails { help_count: number; } // the learner cancelled a help call; help_count is this exercise's count of help calls (0 when the call was made in an earlier exercise); not part of any formula (Module 23)  \nexport interface ChatHelpRequestedDetails { kind: 'call' | 'ready_message'; } // a help request from the chat: \"קראו למורה\" or the ready message; help in measure 2א (Module 23)  \nexport interface BoardClearedDetails { units: number; tens: number; hundreds: number; thousands: number; blocks_removed: number; } // the trash button cleared the whole board; blocks removed per column (Module 8)  \nexport interface BranchSelectedDetails { branch: 'reinforcement' | 'challenge'; } // the learner's choice after the 7 compulsory exercises, sessions 3–7 (Module 14 §ג)", "export interface BranchSelectedDetails"],
  ["error_category: 'calculation' | 'procedural' | 'conceptual' | null;", "error_category: 'calculation' | 'procedural' | 'conceptual' | null;  \n  card_source?: 'ai' | 'static'; // the engine's card or the static card  \n  model_id?: string | null; // the model that wrote the card  \n  card_situation?: string; // the situation the static selection recognised (the card's frame)  \n  card_level?: 1 | 2 | 3; // 1 general, 2 names the column, 3 names the action  \n  card_question_he?: string; // the guiding question as the child saw it  \n  card_options_he?: string[]; // the three options, in id order  \n  card_fallback_reason?: 'offline' | 'timeout' | 'server_failed' | 'schema_rejected' | 'rule_rejected' | 'board_changed' | 'not_coached' | 'error'; // static card only: why the engine's card was not shown  \n  card_fallback_detail?: string; // a short code beside the reason  \n  card_wait_ms?: number; // how long the hourglass turned before the card appeared", "card_wait_ms?: number;"],
  ["HELP_WITHDRAWN: HelpWithdrawnDetails;", "HELP_WITHDRAWN: HelpWithdrawnDetails;  \n  CHAT_HELP_REQUESTED: ChatHelpRequestedDetails;  \n  BOARD_CLEARED: BoardClearedDetails;  \n  BRANCH_SELECTED: BranchSelectedDetails;", "BRANCH_SELECTED: BranchSelectedDetails;"],
  ["details: TelemetryDetailsMap[T];", "details: TelemetryDetailsMap[T];  \n  server_received_at: Timestamp; // set by the server (Firestore serverTimestamp); the Security Rules require it to equal request.time  \n  sequence_number: number; // per device per sign-in, increasing; orders events with the same client_timestamp  \n  device_id: string; // random per browser, created on first use; no PII  \n  synced_at: number; // device time when the event was sent from the queue", "sequence_number: number; // per device per sign-in"]
];

function applyEdits() {
  var body = DocumentApp.getActiveDocument().getBody();
  var done = 0, already = 0, skipped = 0;
  EDITS.forEach(function (e) {
    var oldText = e[0], newText = e[1], marker = e[2] || e[1], nth = e[3] || 1, total = e[4] || 1;
    if (body.findText(esc_(marker))) { already++; return; }
    var matches = [], r = body.findText(esc_(oldText));
    while (r) { matches.push(r); r = body.findText(esc_(oldText), r); }
    if (matches.length !== total) {
      skipped++;
      Logger.log('נמצא ' + matches.length + ' פעמים במקום ' + total + ', דולג: ' + oldText.slice(0, 50));
      return;
    }
    var found = matches[nth - 1];
    var t = found.getElement().asText();
    var s = found.getStartOffset();
    t.deleteText(s, found.getEndOffsetInclusive());
    t.insertText(s, newText);
    done++;
    Logger.log('הוחלף: ' + oldText.slice(0, 50));
  });
  Logger.log('הוחלפו: %s. כבר היו מעודכנים: %s. דולגו: %s.', done, already, skipped);
}

function esc_(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
