// MathmatiCore PRD — batch 3 (8.10.2026), part a: 61 exact replacements. Safe to run more than once.
// Run this one first; then run apply_edits_batch3b.gs.
// Each entry: [old, new, marker, nth, total]. marker = text whose presence means this edit was already applied;
// nth/total = replace the nth of exactly `total` occurrences (used only where the same code line appears twice).
var EDITS = [
  ["גרסה 7.6 | עודכן 8 באוקטובר 2026", "גרסה 7.7 | עודכן 8 באוקטובר 2026"],
  ["מתבצע אימות אטומי (Atomic Validation) מול הקוד הקבוע 10203040.", "מתבצע אימות אטומי (Atomic Validation) מול קוד הגישה האישי של הלומד: לכל לומד קוד בן 4 ספרות, ששתי הראשונות בו הן מספרו בכיתה בשתי ספרות (01–12) ושתי האחרונות ספרות אקראיות, שאינן זוג ספרות זהות (כמו 11) ואינן זוג ספרות עוקבות (כמו 34). רשימת הקודים, וגם הגיבוי שלה, גלויים למורה ולמנהל המערכת, וכל אחד מהם יכול לשנות את הקוד של לומד. האפיון אינו מציג אף קוד."],
  ["הקלדת קוד הגישה 10203040 בשדה", "הקלדת קוד הגישה האישי בן 4 הספרות בשדה"],
  ["תוך מתן משוב פדגוגי מינימלי.", "תוך מתן משוב פדגוגי מינימלי. כניסה שנייה באותו מזהה ממכשיר אחר אפשרית, והשרת אינו חוסם אותה: המכשיר שנכנס אחרון הוא הפעיל, והמכשיר הקודם עובר למצב קריאה בלבד עם ההודעה \"המשכתם במכשיר אחר\". התור של המכשיר הקודם ממשיך לשלוח את מה שנאסף בו (מודול 17), וכל אירוע נושא device_id (נספח א' §3), כדי שאפשר יהיה להבחין בנתונים בין המכשירים."],
  ["תוך שמירה על נתוני שרת קבועים (Persistent Server Data) במידת הצורך.", "תוך שמירה על נתוני שרת קבועים (Persistent Server Data) במידת הצורך. האיפוס אינו מוחק את תור הטלמטריה שב-IndexedDB: מה שלא נשלח נשאר בתור ונשלח רק בשם הזהות שיצרה אותו (סעיף ג). כתובת של מנהל מערכת רשאית להיכנס גם כמורה; בכל כניסה פעיל תפקיד אחד בלבד."],
  ["מחיקת אסמכתת ההזדהות, איפוס Zustand ואיפוס ה-IndexedDB עבור הסשן הנוכחי.", "מחיקת אסמכתת ההזדהות ואיפוס Zustand. תור הטלמטריה שב-IndexedDB אינו נמחק: לפני ההתנתקות המערכת מנסה עד 4 שניות לשלוח את מה שבתור, ומה שלא נשלח נשאר בתור, מתויג לזהות שיצרה אותו, ונשלח בכניסה הבאה של אותה זהות באותו מכשיר. אף פריט בתור אינו מושלך. מטמון קטלוג תוכנית הלימודים אינו נמחק."],
  ["עם חלוף 8 השעות מתבצעת ההתנתקות השקטה המתוארת לעיל, ללא הודעה למשתמש.", "עם חלוף 8 השעות מתבצעת ההתנתקות השקטה המתוארת לעיל, ללא הודעה למשתמש. תוקף 8 השעות נאכף בצד הלקוח בלבד; השרת אינו בודק את גיל הכניסה. בנוסף, מורה ומנהל מערכת מנותקים אחרי 30 דקות ללא פעילות, ולומד שחלון הדפדפן שלו נסגר בפועל (לא ברענון) נדרש להיכנס מחדש אם חלפו יותר מ-5 דקות עד שנפתח שוב."],
  ["ניקוי מלא של הזיכרון המקומי וניתוב הביתה.", "ניקוי מצב הסשן המקומי וניתוב הביתה; תור הטלמטריה ומטמון הקטלוג נשמרים."],
  ["Upon role switching, perform a hard wipe of all local session context and Zustand state buffers to prevent privilege escalation. Execute silent logout upon JWT expiration, clearing all caches and IndexedDB.", "Upon role switching, perform a hard wipe of all local session context and Zustand state buffers to prevent privilege escalation; the wipe never deletes the offline telemetry queue, whose items are sent only under the identity that produced them. Execute silent logout upon JWT expiration: clear the auth token and Zustand state, try for up to 4 seconds to flush the offline queue, and keep whatever is unsent in IndexedDB tagged to its identity, to be sent on that identity's next sign-in on the same device. Never discard a queued item, and never clear the curriculum catalog cache. The 8-hour expiry is checked on the client only. Sign staff out after 30 minutes of inactivity; require a learner whose browser window was really closed (not reloaded) for more than 5 minutes to sign in again."],
  ["telemetry_logs (שמירת מטעני טלמטריה מוקלדים המסונכרנים מתור האופליין)", "telemetry_logs (מטעני הטלמטריה המסונכרנים מתור האופליין: מסמך אחד לכל אירוע, שמזהה המסמך שלו הוא idempotency_key של האירוע, UUID v4; הלקוח יוצר מסמכים בלבד ואינו מעדכן או מוחק; לצד שדות TelemetryPayload נשמר synced_at, שעת המכשיר בשליחה מהתור)"],
  ["support_tickets (ניהול פניות תמיכה אנונימיות)", "support_tickets (פניות תמיכה אנונימיות, שמורה או מנהל כותבים ישירות, בבדיקת המבנה של חוקי האבטחה ובבדיקת PII בצד הלקוח בלבד; אין פונקציית ענן בדרך)"],
  ["messages (ארכיון הודעות שיח מורה-הנהלה, Zero PII).", "messages (ארכיון הודעות שיח מורה-הנהלה, Zero PII), reports (דוחות הלומד שהופקו, מודול 23), class_reports (דוחות הכיתה, מודול 23), catchup_records (רישומי זמן ההשלמה, מודול 14 §ב0), srl_reflections (רפלקציות מפגש 8, מודול 16), store_cache (מטמון סקירת המנהל, מודול 24) ו-reset_audit_log (יומן האיפוסים והייצואים, מודול 23א)."],
  ["and the master curriculum catalog collection (curriculum_catalog) to allow asynchronous exercise template updates.", "and the master curriculum catalog collection (curriculum_catalog) to allow asynchronous exercise template updates, plus reports, class_reports, catchup_records, srl_reflections, store_cache and reset_audit_log. Store telemetry_logs as one document per event, whose document id is the event's idempotency_key (UUID v4), create-only for the client, with synced_at beside the TelemetryPayload fields."],
  ["גודל מטען מרבי לבקשה: ≤50KB. שימוש בתור מקומי (Queue) ב-IndexedDB במקרה של אופליין.", "גודל מטען מרבי: ≤50KB לכל מנה שנשלחת מהתור לשרת (עד 20 אירועים במנה) ולכל עדכון של מצב מרחב העבודה ב-Realtime Database; אירוע בודד קטן בהרבה מהתקרה. כל אירוע עובר תמיד דרך התור המקומי (Queue) ב-IndexedDB, גם ברשת פעילה: הוא נכתב לתור ונשלח ממנו (מודול 17). לכל אירוע שלוש חותמות: client_timestamp (שעון המכשיר), sequence_number (מונה עולה לכל מכשיר ולכל כניסה) ו-server_received_at (שעת הקבלה בשרת, שהשרת קובע וחוקי האבטחה מחייבים שתהיה שווה לזמן הבקשה), וכן device_id, מזהה אקראי של הדפדפן שאין בו פרט מזהה. סדר האירועים בכל קריאה, חישוב ותצוגה: לפי client_timestamp בסדר עולה, ובשוויון לפי sequence_number."],
  ["HESITATION_DETECTED, SOCRATIC_CARD_SHOWN. השדה", "HESITATION_DETECTED, SOCRATIC_CARD_SHOWN, KEYBOARD_LOCK_BLOCKED. השדה"],
  ["עבור אירועי סשן, תרגיל ורפלקציה: SESSION_START, PROBLEM_LOAD, UNDO_EXECUTED (למעט כאשר הפעולה שבוטלה הייתה מוגבלת לטור ספציפי), SOCRATIC_OPTION_SELECTED, PROBLEM_COMPLETE, REFLECTION_SUBMITTED. כלל זה נאכף ב-Firestore Security Rules (מודול 27) לצד בדיקת סכמת ה-details.", "עבור אירועי סשן, תרגיל, עזרה, לוח ורפלקציה: SESSION_START, PROBLEM_LOAD, UNDO_EXECUTED (למעט כאשר הפעולה שבוטלה הייתה מוגבלת לטור ספציפי), SOCRATIC_OPTION_SELECTED, PROBLEM_COMPLETE, REFLECTION_SUBMITTED, ADAPTIVE_GRID_TOGGLED, HELP_REQUESTED, HELP_WITHDRAWN, CHAT_HELP_REQUESTED, BOARD_CLEARED, PLACE_CUES_SHOWN, BRANCH_SELECTED. השלכת לבנה לפח האשפה נרשמת כ-BLOCK_DRAG_COMPLETE שבו column_index שווה ל-source_column_index (הטור שהלבנה עזבה); ניקוי הלוח כולו בלחיצה על הפח נרשם כ-BOARD_CLEARED. כלל זה נאכף ב-Firestore Security Rules (מודול 27); חוקי האבטחה בודקים את details כמפה בלבד, לא לפי הסכימה של כל סוג אירוע."],
  ["every one of the 13 event types has its own required field set now.", "every event type in Appendix A §3 has its own required field set."],
  ["Validate payload size (≤50KB) before every update.", "Validate size (≤50KB) for every batch sent from the queue and every workspace-state update. Send every event through the IndexedDB queue, online or offline. Stamp each event with client_timestamp, a per-device per-sign-in sequence_number and a random per-browser device_id; the server sets server_received_at (rule-enforced equal to request.time). Order events by client_timestamp ascending, ties by sequence_number."],
  ["ממשק: עמעום טורים שאינם במוקד החישוב הנוכחי (brightness: 0.6).", "ממשק: עמעום טורים (brightness: 0.6), לפי החלטת בעל המוצר מ-7.10.2026. טורים מעומעמים רק כשהמיקוד של הלומד נמצא בתיבה (תיבה בשורת התוצאה או תיבת ספרה חסרה) או בעיגול זיכרון; אז מוארים הטור של התיבה והטורים שהחישוב בה תלוי בהם (הטור שממנו פורטים, הטור שאליו מקבצים, והטורים שמהתיבה הריקה הנמוכה ביותר ועד הטור שבמיקוד), ושאר הטורים מעומעמים. כשאף תיבה ואף עיגול זיכרון אינם במיקוד, אף טור אינו מעומעם, בכל המפגשים. בזמן בניית המספרים בלבנים אין עמעום. במפגש 1 עיגול זיכרון אינו מעמעם. העמעום קיים רק בתרגילי חישוב במאונך; בתרגילים שבהם עובדים על הלוח כולו (כגון תרגילי ייצוג) אף טור אינו מעומעם."],
  ["Implement CSS filter properties for brightness control (brightness(0.6) for inactive columns).", "Dim columns with a CSS brightness(0.6) filter only while the learner's focus is in a box (a result-row box or a missing-digit box) or a memory circle, in vertical calculation exercises only: light the focused box's column together with the columns its calculation depends on (the column decomposed from, the column grouped into, and every column from the lowest empty box up to the focus) and dim the rest. With no box and no memory circle focused, dim nothing, in every session; never dim while the numbers are being built with blocks; in session 1 a memory circle does not dim."],
  ["עם התרגיל הוא שואל על 425 − 162 בטור העשרות.", "עם התרגיל הוא שואל על 425 − 162 בטור העשרות. לצד אלה הבקשה נושאת את task_context: סוג התרגיל שעל המסך ונוסח ההנחיה שלו, הלבנים שההנחיה מבקשת (להשוואה בלבד) והמספרים שאסור לכרטיס להציג (לבדיקת הדליפה בלבד); השרת בודק אותו, ואין בו טקסט של הלומד. ולצד הבקשה נשלח anchor: הכרטיס הסטטי שהלומד היה רואה (שאלה מנחה, שלוש אפשרויות ונכונותן), שהמנוע משפר ואינו סותר."],
  ["הממפות את ארבעת עמודי התווך של המטריקס: המבנה העשרוני והאפס, הקבצה, פריטה, וחישוב במאונך.", "הממפות את שלושת התחומים של המטריקס: המבנה העשרוני והאפס, הקבצה ופריטה, וחישוב במאונך (החלטת בעל המוצר, 26.9.2026). שיוך המשימות לתחומים: משימות 1, 2 ו-4 — המבנה העשרוני והאפס; משימה 3 — חישוב במאונך, והקבצה ופריטה (פריטה); משימה 5 — הקבצה ופריטה (הקבצה); משימה 6 — חישוב במאונך, והקבצה ופריטה (הקבצה); משימה 7 — המבנה העשרוני והאפס, חישוב במאונך, והקבצה ופריטה (פריטה). התוצאות לפי תחום מוצגות למורה בלשונית \"מיפוי מיומנויות כיתתי\"."],
  ["המלצת המסלול (מודול 20) נגזרת מהציון.", "המלצת המסלול (מודול 20) נגזרת מהציון. הרישום במפגש 2: במשימות 3 עד 7 כל ספרה שהוקלדה נבדקת מול הטור שלה ונרשמת כ-DIGIT_ENTERED עם is_correct, וספרה שגויה נספרת גם אם תוקנה; במשימות 1 ו-2, שבהן תיבת תשובה אחת, ההקשות נרשמות עם is_correct: null, והתשובה נבדקת בלחיצה על \"ממשיכים\". תשובה סופית נכונה בסבב הראשון נרשמת כ-PROBLEM_COMPLETE. תשובה סופית שגויה אינה שולחת אירוע טלמטריה: היא נרשמת בתיוג האבחוני של המשימה וביומן הרדאר של הלומד. בסבב התיקונים לא נשלח PROBLEM_COMPLETE."],
  ["לומד שהושלם בסגירה וסיים אחר כך את המפגש שנפתח שוב מקבל ציון מחדש.", "לומד שהושלם בסגירה וסיים אחר כך את המפגש שנפתח שוב מקבל ציון מחדש. המשימה שהייתה פתוחה בסגירה וכל המשימות שאחריה אינן נספרות כנכונות: הן מתויגות 'not_answered' ומוצגות למורה כ\"דרוש חיזוק\", ומקבלות ציון אם הלומד עונה עליהן במפגש שנפתח שוב."],
  ["המורה מוסיפה סבב השלמה; ללומדים אין גישה לאוסף.", "המורה מוסיפה סבב השלמה; ללומדים ולמנהל המערכת אין גישה לאוסף, ורק המורה של הכיתה קוראת אותו."],
  ["באותו מפגש (active_minutes).", "באותו מפגש (active_minutes). זו ההגדרה היחידה של דקות פעילות במערכת, גם בדוחות ובייצוא המחקר (מודולים 23 ו-24)."],
  ["איפוס מפגש (מודול 23א) מוחק, לאחר גיבוי, את העותק השמור של אותו מפגש, את סימן הסיום שלו ואת רישום ההשלמה שלו; איפוס מוחלט של לומד ואיפוס מערכת מוחקים את כולם.", "איפוס מפגש (מודול 23א) מוחק, לאחר גיבוי, את העותק השמור של אותו מפגש ואת סימן הסיום שלו; רישום ההשלמה של אותו מפגש נשמר, ומוצג בדוח בסעיף \"לפני האיפוס\". איפוס מוחלט של לומד ואיפוס מערכת מוחקים את כולם, כולל רישומי ההשלמה."],
  ["משימות חזרה וייצוגים לא סטנדרטיים.", "הכפתור שהלומד רואה: \"חיזוק וחזרה על החומר\". שני תרגילים נוספים ברמת המפגש (מודול 26)."],
  ["משימות חקר מורכבות בתחום הרבבה, המרות מרובות וספרות חסרות.", "הכפתור שהלומד רואה: \"אתגר\". תרגיל אחד קשה יותר (מודול 26)."],
  ["תרגילי הבחירה אינם נכללים במדדי השליטה הרשמיים של 7 תרגילי החובה.", "תרגילי הבחירה אינם נכללים במדדי השליטה הרשמיים של 7 תרגילי החובה. המילה \"מסלול\" אינה מופיעה במסך הבחירה: היא שמורה למסלול שהמורה קובעת (מודול 20). הלומד בוחר נתיב אחד בלבד; אם סיים אותו לפני תום הזמן, הוא ממתין במסך הסיום השקט. הבחירה נרשמת כאירוע BRANCH_SELECTED (נספח א' §3)."],
  ["ב. מצב המערכת וחישוב מדד ההתמדה", "ב. מצב המערכת וחישוב מדד התיקון העצמי (מדד 2ב)"],
  ["נוסחת מדד ההתמדה (Persistence Index):", "נוסחת מדד התיקון העצמי (מדד 2ב; בנתונים persistence_index):"],
  ["idempotency_key, client_timestamp, session_id, student_id, exercise_id, operation_type, payload.", "idempotency_key, client_timestamp, session_id, student_id, exercise_id, operation_type, payload. כל אירוע טלמטריה עובר תמיד דרך התור, גם ברשת פעילה. מאחר שכל פעולה נשמרת ב-IndexedDB לפני שליחתה, סגירת לשונית או חלון אינה מאבדת דבר, ומה שלא נשלח נשלח בפתיחה הבאה; ניקוי נתוני האתר בדפדפן מוחק את התור, ואין לו גיבוי. אף פריט בתור אינו מושלך לעולם, גם לא בהגעה לתקרת הנפח של התור (50,000 פריטים): הגעה לתקרה היא תקלה, לא סיבה להשליך. אירוע שהשרת דוחה אינו נמחק: אחרי 5 דחיות הוא מושהה בתור, ובכל טעינת דף הוא מקבל סדרת ניסיונות חדשה. האירועים המושהים נספרים בחיווי הענן (סעיף ד), והמורה רואה את מספרם בכרטיס הלומד תחת \"אירועים שנדחו\"."],
  ["שליפת מצב סמכותי עדכני מ-Firestore ועדכון Zustand.", "פריטים שנעצרו בגלל תקלת רשת מקבלים ניסיון נוסף מיד עם חידוש החיבור; מצב מרחב העבודה אינו נשלף מחדש בשלב זה."],
  ["השרת אוכף עיבוד אידמפוטנטי (Idempotent Execution) למניעת כפילויות.", "כפילויות נמנעות במבנה הנתונים (Idempotent Execution): מזהה המסמך ב-telemetry_logs הוא idempotency_key של האירוע, וחוקי האבטחה מתירים יצירה בלבד; שליחה חוזרת של אירוע שכבר נשמר נדחית, והלקוח מתייחס לדחייה זו כאישור ומוחק את הפריט מהתור."],
  ["executing atomic deletes from IndexedDB strictly upon server acknowledgment.", "executing atomic deletes from IndexedDB strictly upon server acknowledgment. Never discard a queued item; park an item after 5 refusals, retry it on every page load, and count parked items in the sync indicator and on the teacher's learner card as \"אירועים שנדחו\"."],
  ["נגן וידאו ממוקד המריץ צילום מסך מקומי מקוודד (Encrypted) של קנבס העבודה", "נגן ממוקד המריץ הקלטת שחזור של קנבס העבודה (הקלטת DOM, הנשמרת כ-JSON ב-Realtime Database ומוגנת בהצפנה הסטנדרטית של הפלטפורמה בלבד, ללא הצפנה נוספת)"],
  ["המערכת טוענת את קובץ הוידאו המוצפן ואת טבלת ה-VRA התואמת.", "המערכת טוענת את הקלטת השחזור ואת טבלת ה-VRA התואמת."],
  ["שני הכיוונים חייבים להיות פעילים.", "שני הכיוונים חייבים להיות פעילים. הורדת המפגש. בעמוד המסע של הלומד, הכפתור \"הורדת המפגש\" מוריד למחשב המורה קובץ HTML אחד של המפגש: כל הפעולות המתועדות של המפגש, האיפוסים שחתכו אותו, הפרקים והקלטת השחזור עצמה, עם נגן שנפתח בלי אינטרנט ובלי כניסה. הלומד מזוהה בקובץ במזהה 1–12 בלבד. כל הורדה נרשמת ב-reset_audit_log עם reset_level: 'export' (מודול 23א §ד)."],
  ["פונקציית ענן סורקת את הטקסט, מצליבה מול רשימת שמות הכיתה ומחליפה כל שם פרטי במזהה האנונימי התואם (לדוגמה: \"דניאל\" ← \"תלמיד 4\").", "פונקציית ענן (sendTeacherAdminMessage) סורקת את הטקסט: מסירה שם שבא אחרי \"תלמיד N המכונה\" ומשאירה \"תלמיד N\", ומחליפה בסימון מוסתר כתובות דוא\"ל, מספרי טלפון, מספרי תעודת זהות, שם שבא אחרי ביטוי היכרות (\"קוראים לו\", \"שמו\" וכדומה) וסיסמאות. אין במערכת רשימת שמות של הכיתה (Zero PII), ולכן השרת אינו מצליב מול שמות, ושם פרטי שנכתב לבדו אינו מוחלף."],
  ["השרת ממיר את ההודעה ל-\"תלמיד 3 המכונה תלמיד 4 מתקשה בפריטה\" לפני השמירה במסד הנתונים.", "השרת ממיר את ההודעה ל-\"תלמיד 3 מתקשה בפריטה\" לפני השמירה במסד הנתונים."],
  ["ונשלחת רק לאחר חידוש החיבור וביצוע האנונימיזציה בשרת.", "ונשלחת רק לאחר חידוש החיבור וביצוע האנונימיזציה בשרת. הצ'אט בין הלומד למורה (chat_messages ב-Realtime Database) מוגן בסינון ה-PII שבצד הלקוח בלבד (מודול 3 §א); אין לו שכבת שרת."],
  ["המורה מקבלת דוח ניתוח על תפקוד הלומד", "המורה יכולה להפיק דוח ניתוח על תפקוד הלומד"],
  ["השמור ב-Cloud Storage ומקושר למסמך המורה.", "השמור ב-Cloud Storage, והקישור אליו נשמר במסמך הדוח באוסף reports. הפקה חוזרת יוצרת קובץ חדש ואינה דורסת את הקודם."],
  ["עם הנימוק: \"מאז האיפוס עוד לא נרשמה לו אף תשובה\".", "עם הנימוק: \"מאז האיפוס עוד לא נרשמה לו אף תשובה\". הריצה שמאז האיפוס נקבעת לפי client_timestamp של כל אירוע מול performed_at של רישום האיפוס: אירוע שנוצר במכשיר לפני האיפוס שייך ל\"לפני האיפוס\" גם אם הגיע לשרת אחריו. בסעיף \"לפני האיפוס\" מוצג גם רישום זמן ההשלמה של אותו מפגש. דוח שהופק לפני האיפוס נשמר ומסומן \"לפני האיפוס\"; דוח שמופק אחרי האיפוס הוא קובץ חדש ואינו מחליף אותו. רק איפוס שהושלם (deletion_status: 'completed', מודול 23א §ד) נחשב איפוס בדוחות ובייצוא."],
  ["ייצוא המחקר ו-CSV דוח הכיתה מכילים עמודות tool_* לכל המפגשים, בסוף השורה, כך שכל עמודה קיימת נשארת במקומה.", "ייצוא המחקר ו-CSV דוח הכיתה מכילים עמודות tool_* לכל המפגשים, במקומן הקבוע בסדר העמודות (מודול 24 §ב); עמודה חדשה נוספת תמיד בסוף השורה, כך שכל עמודה קיימת נשארת במקומה."],
  ["אירועים שבהם is_correct === null מתעלמים מהם לחלוטין ואינם נחשבים לא כנכונים ולא כשגויים.", "אירועים שבהם is_correct === null מתעלמים מהם לחלוטין ואינם נחשבים לא כנכונים ולא כשגויים. רק ספרה שגויה שוברת ניסיון ראשון בציון: בדיקת לוח שנכשלה ובחירה שגויה בכרטיס החניכה אינן שוברות אותו (במדד 3 ניסיון ראשון מוגדר אחרת, לפי error_count, כמפורט שם). \"תרגילי החובה\" הם התרגילים שה-path_type שלהם 'compulsory' במאגר של המפגש והמסלול (מודול 26), ו\"השלים\" פירושו אירוע PROBLEM_COMPLETE הראשון של התרגיל. כל אחוז בדוחות מעוגל לאחוז שלם; ממוצע וחציון בדוח הכיתה מעוגלים לעשירית."],
  ["מדד 1, עצמאות מושגית:", "מדד 1, ציון ניסיון ראשון:"],
  ["session_score_percent, כמוגדר לעיל.", "session_score_percent, כמוגדר לעיל. זה שמו היחיד בכל דוח ובכל מסך: \"ציון ניסיון ראשון (מדד 1)\"."],
  ["בכמה מהם לא לחץ על \"קריאה לעזרה\".", "בכמה מהם לא ביקש עזרה."],
  ["עזרה היא אך ורק לחיצת הלומד על \"קריאה לעזרה\" (HELP_REQUESTED);", "עזרה היא לחיצת הלומד על \"קריאה לעזרה\" (HELP_REQUESTED) או בקשת עזרה בצ'אט (CHAT_HELP_REQUESTED: \"קראו למורה\" או ההודעה המוכנה \"אפשר עזרה בתרגיל?\");"],
  ["מדד 2ב הוא גם המדד שלפיו נבחר משפט העידוד של הלומד (מודול 16 §ב).", "מדד 2ב הוא גם המדד שלפיו נבחר משפט העידוד של הלומד (מודול 16 §ב). ערך המחקר של מדד 2ב הוא הערך שהשרת מחשב מאירועי הטלמטריה (self_correction_percent); הערך persistence_index שנשמר ברפלקציה של מפגש 8 משמש לבחירת המשפט בלבד."],
  ["בתרגילי ייצוג, error_count סופר כל בדיקת לוח שנכשלה.", "בתרגילי ייצוג, error_count סופר כל בדיקת לוח שנכשלה. בכל תרגיל אחר error_count סופר את הלחיצות על \"ממשיכים\" באותו תרגיל שבהן התשובה הייתה שגויה; תשובה ריקה או שאלה שלא נענתה אינן נספרות."],
  ["מספר הכרטיסים שאחריהם התשובה הבאה של הלומד באותו exercise_id הייתה נכונה: אירוע DIGIT_ENTERED הראשון שבו is_correct אינו null הוא is_correct === true, ובתרגיל ללא הקלדת ספרות, אירוע PROBLEM_COMPLETE שהגיע לפני כרטיס חניכה נוסף.", "מספר הכרטיסים שאחריהם התשובה הבאה של הלומד באותו exercise_id הייתה נכונה. אחרי כל כרטיס מכריע האירוע הראשון באותו exercise_id מבין שניים: DIGIT_ENTERED שבו is_correct אינו null (הכרטיס נספר ב-S אם is_correct === true), או PROBLEM_COMPLETE של אותו תרגיל (הכרטיס נספר ב-S). בחירת אפשרות בכרטיס עצמו (SOCRATIC_OPTION_SELECTED) אינה תשובה לעניין זה. כרטיס שנפתח באותו תרגיל לפני שהקודם הוכרע מחליף אותו, והקודם אינו נספר ב-S; כרטיס שלא בא אחריו אף אחד משני האירועים אינו נספר ב-S."],
  ["תוצאה בכל תרגיל (ניסיון ראשון / אחרי תיקון / לא הושלם), דקות פעילות, דקות הקלטה, רפלקציה, מסלול ומסמך המפגש.", "תוצאה בכל תרגיל (ניסיון ראשון / אחרי תיקון / לא הושלם), דקות פעילות, דקות הקלטה, רפלקציה, מסלול ונתוני מסמך המפגש (SessionDocument: ציון, מסלול מומלץ ומסלול שבחרה המורה). המונים נספרים מאירועים: ספרות שגויות = DIGIT_ENTERED עם is_correct === false; מחיקות = DIGIT_DELETED; ביטולי פעולה = UNDO_EXECUTED; היסוסים = HESITATION_DETECTED, ומשך השניות = סכום hesitation_seconds; המרות = REGROUPING_SUCCESS; כרטיסי חניכה = SOCRATIC_CARD_SHOWN; רפלקציה = האם נשלח REFLECTION_SUBMITTED; דקות הקלטה = משך הקלטות השחזור של המפגש (מודול 21); דקות פעילות = מספר הדקות השלמות שבהן הגיע מהלומד לפחות אירוע טלמטריה אחד במפגש, אותה הגדרה כמו בזמן ההשלמה (מודול 14 §ב0)."],
  ["שניהם נשמרים ב-Cloud Storage ובדרייב בתיקייה `05 דוחות כיתה / מפגש N`,", "שניהם נשמרים ב-Cloud Storage ובדרייב בתיקייה `1 דוחות` (ראו \"תיקיות הדרייב\" להלן); הקישורים להורדתם בתוקף לשעה אחת מרגע יצירתם, כמו הקישור לדוח הלומד;"],
  ["המסלול בדוח הכיתה (learning_path) הוא המסלול שבו הלומד עבד באותו מפגש.", "המסלול בדוח הכיתה (learning_path) הוא המסלול שבו הלומד עבד באותו מפגש: המאגר שממנו נפתחו רוב התרגילים של הלומד באותו מפגש, וכשלא נפתח אף תרגיל, המסלול שברשומה הקנונית של הלומד. במפגשים 1 ו-2 אין מסלול, והערך ריק. זו ההגדרה בכל דוח ובייצוא המחקר."],
  ["קבצי המערכת בדרייב מופרדים לפי סוג, לתיקיות בשם קבוע הנוצרות מאליהן בכתיבה הראשונה: `01 דוחות תלמידים / מפגש N` (דוחות הלומד של מודול זה), `02 נתוני מחקר / … / תאריך` (ייצוא נתוני המחקר, מודול 24), `03 גיבויי איפוס` (מודול 23א), `04 דוחות מנהל` (מודול 24), ו-`05 דוחות כיתה / מפגש N` (דוחות הכיתה). חומר המחקר ודוח המנהל אינם נכתבים לאותה תיקייה.", "קבצי המערכת בדרייב נכתבים לארבע תיקיות שטוחות בתוך התיקייה הראשית של החוקר, בלי תיקיות משנה, בשם קבוע, הנוצרות מאליהן בכתיבה הראשונה: `1 דוחות` (דוחות הלומד ודוחות הכיתה, למשל \"מפגש 3 - תלמיד 01 - 08.10.2026.pdf\" ו-\"מפגש 3 - כיתה - 08.10.2026.pdf\"), `2 נתוני מחקר` (ייצוא נתוני המחקר, מודול 24, למשל \"ייצוא 08.10.2026 14-30 - פעולות.csv\"), `3 גיבויים` (גיבויי האיפוס, מודול 23א, למשל \"גיבוי 08.10.2026 14-30 - תלמיד 04 מפגש 3.json\") ו-`4 מנהל` (דוח המנהל, מודול 24, למשל \"דוח מנהל 08.10.2026.pdf\"). בשמות הקבצים מספר הלומד נכתב בשתי ספרות, התאריך בתבנית DD.MM.YYYY והשעה בתבנית HH-mm לפי שעון ישראל. הפקה חוזרת אינה דורסת קובץ: היא יוצרת קובץ חדש, והקודם נשמר. קבצים שכבר נמצאים בדרייב אינם מועברים. חבר התיקייה הראשית הוא החוקר בלבד (בפיילוט החוקר הוא גם המורה); אדם אחר מקבל גישה רק אם החוקר מוסיף אותו ידנית. הכותב לתיקיות הוא חשבון השירות של Cloud Functions, ואף קובץ אינו משותף בנפרד."],
  ["המכיל ניתוח פערי ידע, מדדי שליטה, מדד התמדה SRL והנחיות דידקטיות.", "המכיל ניתוח פערי ידע, ציון ניסיון ראשון (מדד 1), מדדי המחקר 2א–4 והנחיות דידקטיות."],
  ["stored in Storage, in Drive under `05 דוחות כיתה / מפגש N`, and in class_reports/class_1_session_N.", "stored in Storage (download links valid for one hour), in the flat Drive folder `1 דוחות`, and in class_reports/class_1_session_N."],
  ["Write learner reports to Drive under `01 דוחות תלמידים / מפגש N`.", "Write learner and class reports to the flat Drive folder `1 דוחות` (file names such as \"מפגש 3 - תלמיד 01 - 08.10.2026.pdf\" and \"מפגש 3 - כיתה - 08.10.2026.pdf\"); a regenerated report is a new file and never overwrites the previous one."]
];

function applyEdits() {
  var body = DocumentApp.getActiveDocument().getBody();
  var done = 0, already = 0, skipped = 0;
  EDITS.forEach(function (e) {
    var oldText = e[0], newText = e[1], marker = e[2] || e[1], nth = e[3] || 1, total = e[4] || 1;
    if (body.findText(esc_(marker))) { already++; return; }
    var matches = [], r = body.findText(esc_(oldText));
    while (r) { matches.push(r); r = body.findText(esc_(oldText), r); }
    if (matches.length !== total) {
      skipped++;
      Logger.log('נמצא ' + matches.length + ' פעמים במקום ' + total + ', דולג: ' + oldText.slice(0, 50));
      return;
    }
    var found = matches[nth - 1];
    var t = found.getElement().asText();
    var s = found.getStartOffset();
    t.deleteText(s, found.getEndOffsetInclusive());
    t.insertText(s, newText);
    done++;
    Logger.log('הוחלף: ' + oldText.slice(0, 50));
  });
  Logger.log('הוחלפו: %s. כבר היו מעודכנים: %s. דולגו: %s.', done, already, skipped);
}

function esc_(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
