import * as logger from "firebase-functions/logger";
import * as admin from "firebase-admin";
import { onCall, HttpsError } from "firebase-functions/v2/https";
import { GEMINI_SECRETS, getGeminiKeyStatus } from "./geminiConfig";

/**
 * Operational monitoring for every Gemini call the platform makes.
 *
 * Two sinks, both PII-free:
 *   1. A structured Cloud Logging entry per call (feature, outcome, latency,
 *      anonymous student id 1-12, session/exercise ids) — this is what an
 *      engineer greps when "the AI stopped answering".
 *   2. Aggregate counters in Firestore store_cache/ai_monitoring, the document
 *      the admin console already has read access to (firestore.rules,
 *      Module 24 store cache). Per feature and per day: calls, each outcome,
 *      summed latency, last error code. Written fire-and-forget so a slow
 *      Firestore can never delay a learner's card.
 *
 * Outcomes are the only vocabulary: "ok" means a validated answer reached the
 * learner; every other value means the static fallback was served instead and
 * says why. The ratio of ok to everything else IS the health of the engine.
 */
export type AiFeature = "socratic" | "socratic_legacy" | "report_analysis" | "class_report";

export type AiOutcome =
  | "ok"
  | "invalid_request"
  | "timeout"
  | "schema_reject"
  | "answer_leak"
  | "forbidden_term"
  | "not_json"
  | "auth"
  | "quota"
  | "network"
  | "safety"
  | "misconfigured"
  | "unknown";

export interface AiCallRecord {
  feature: AiFeature;
  outcome: AiOutcome;
  latency_ms: number;
  model_id: string;
  /** Anonymous learner id 1-12 (never a uid, never a name). */
  student_id?: number;
  session_id?: string;
  exercise_id?: string;
  trigger_reason?: string;
  error_category?: string;
  attempts?: number;
  /** Validator reason or classified error code — short, generated by us, never model text. */
  detail?: string;
}

export const AI_MONITORING_DOC = "ai_monitoring";

function dayKey(now = new Date()): string {
  // Israel local day, so the admin console's "today" matches the teacher's.
  const il = new Date(now.toLocaleString("en-US", { timeZone: "Asia/Jerusalem" }));
  const y = il.getFullYear();
  const m = String(il.getMonth() + 1).padStart(2, "0");
  const d = String(il.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

let firestoreDisabled = false;

/**
 * Records one Gemini call. Never throws, never awaits Firestore on the caller's
 * critical path.
 */
export function recordAiCall(rec: AiCallRecord): void {
  const level = rec.outcome === "ok" ? "info" : rec.outcome === "timeout" || rec.outcome === "schema_reject" ? "warn" : "error";
  logger[level]("[ai-monitor] gemini call", rec);

  if (firestoreDisabled) return;
  try {
    const db = admin.firestore();
    const inc = admin.firestore.FieldValue.increment;
    const day = dayKey();
    const f = rec.feature;
    const update: Record<string, unknown> = {
      updated_at: Date.now(),
      model_id: rec.model_id,
      [`totals.${f}.calls`]: inc(1),
      [`totals.${f}.${rec.outcome}`]: inc(1),
      [`totals.${f}.latency_sum_ms`]: inc(rec.latency_ms),
      [`daily.${day}.${f}.calls`]: inc(1),
      [`daily.${day}.${f}.${rec.outcome}`]: inc(1),
      [`daily.${day}.${f}.latency_sum_ms`]: inc(rec.latency_ms),
      [`last_call.${f}`]: { at: Date.now(), outcome: rec.outcome, latency_ms: rec.latency_ms },
    };
    if (rec.outcome !== "ok") {
      update[`last_failure.${f}`] = { at: Date.now(), outcome: rec.outcome, detail: rec.detail ?? null };
    }
    db.collection("store_cache").doc(AI_MONITORING_DOC).set(update, { merge: true }).catch((err) => {
      // A rules or connectivity problem must not spam every call; log once and go quiet.
      firestoreDisabled = true;
      logger.warn("[ai-monitor] counter write failed; disabling counters for this instance", { error: String(err) });
    });
  } catch (err) {
    logger.warn("[ai-monitor] counter write skipped", { error: String(err) });
  }
}

/** Test seam. */
export function resetAiMonitoringState(): void {
  firestoreDisabled = false;
}

function callerIsStaff(token: Record<string, unknown> | undefined): boolean {
  if (!token) return false;
  const roles: string[] = Array.isArray(token.roles) ? (token.roles as string[]) : token.role ? [String(token.role)] : [];
  const lowered = roles.map((r) => r.toLowerCase());
  return lowered.includes("admin") || lowered.includes("teacher") || token.admin === true || token.teacher === true;
}

/**
 * getAiServiceStatus — the admin console's view of the AI engine: whether the
 * key is bound (and where), whether it looks well-formed, which model is in
 * use, and the aggregate counters. Staff only; the key itself is never
 * returned, only its last four characters.
 */
export const getAiServiceStatus = onCall(GEMINI_SECRETS, async (request) => {
  if (!request.auth) throw new HttpsError("unauthenticated", "Authentication required.");
  if (!callerIsStaff(request.auth.token as Record<string, unknown>)) {
    throw new HttpsError("permission-denied", "Staff role required.");
  }

  const key = getGeminiKeyStatus();

  let counters: Record<string, unknown> | null = null;
  try {
    const snap = await admin.firestore().collection("store_cache").doc(AI_MONITORING_DOC).get();
    counters = snap.exists ? (snap.data() as Record<string, unknown>) : null;
  } catch (err) {
    logger.warn("[ai-monitor] status read failed", { error: String(err) });
  }

  return {
    checked_at: Date.now(),
    key,
    counters,
    today: dayKey(),
  };
});
