import * as logger from "firebase-functions/logger";
import { FieldValue, getFirestore } from "firebase-admin/firestore";
import { onCall, HttpsError } from "firebase-functions/v2/https";
import { GEMINI_MODEL_ID, GEMINI_SECRETS, SOCRATIC_PRIMARY_MODEL, classifyGeminiError, generateGeminiText, getGeminiKeyStatus } from "./geminiConfig";

/**
 * Operational monitoring for every Gemini call the platform makes.
 *
 * Two sinks, both PII-free:
 *   1. A structured Cloud Logging entry per call (feature, outcome, latency,
 *      anonymous student id 1-12, session/exercise ids) — this is what an
 *      engineer greps when "the AI stopped answering".
 *   2. Aggregate counters in Firestore store_cache/ai_monitoring, the document
 *      the admin console already has read access to (firestore.rules,
 *      Module 24 store cache). Per feature and per day: calls, each outcome,
 *      summed latency, last error code. Written fire-and-forget so a slow
 *      Firestore can never delay a learner's card.
 *
 * Outcomes are the only vocabulary: "ok" means a validated answer reached the
 * learner; every other value means the static fallback was served instead and
 * says why. The ratio of ok to everything else IS the health of the engine.
 */
export type AiFeature = "socratic" | "report_analysis" | "class_report";

export type AiOutcome =
  | "ok"
  | "invalid_request"
  | "timeout"
  | "schema_reject"
  | "answer_leak"
  | "forbidden_term"
  /** The card broke a writing, style, screen or counting rule (socraticLanguage.ts). */
  | "language_reject"
  /** The card left its frame (a level-1 card that names a column). */
  | "frame_reject"
  /** A report's analysis came back well-formed with nothing to report: the fallback sentence ships, but nothing failed. */
  | "empty"
  | "not_json"
  | "auth"
  | "quota"
  | "network"
  | "safety"
  | "misconfigured"
  | "unknown";

export interface AiCallRecord {
  feature: AiFeature;
  outcome: AiOutcome;
  latency_ms: number;
  model_id: string;
  /** Anonymous learner id 1-12 (never a uid, never a name). */
  student_id?: number;
  session_id?: string;
  exercise_id?: string;
  trigger_reason?: string;
  error_category?: string;
  attempts?: number;
  /** Validator reason or classified error code — short, generated by us, never model text. */
  detail?: string;
}

export const AI_MONITORING_DOC = "ai_monitoring";

function dayKey(now = new Date()): string {
  // Israel local day, so the admin console's "today" matches the teacher's.
  const il = new Date(now.toLocaleString("en-US", { timeZone: "Asia/Jerusalem" }));
  const y = il.getFullYear();
  const m = String(il.getMonth() + 1).padStart(2, "0");
  const d = String(il.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

let firestoreDisabled = false;

/**
 * Records one Gemini call. Never throws, never awaits Firestore on the caller's
 * critical path.
 */
export function recordAiCall(rec: AiCallRecord): void {
  const level = rec.outcome === "ok" || rec.outcome === "empty" ? "info" : rec.outcome === "timeout" || rec.outcome === "schema_reject" ? "warn" : "error";
  logger[level]("[ai-monitor] gemini call", rec);

  if (firestoreDisabled) return;
  try {
    // The modular import: the namespaced admin.firestore.FieldValue read back
    // undefined inside the Functions emulator, so every counter write was
    // skipped there ("Cannot read properties of undefined (reading
    // 'increment')", audit of 1.10.2026) and the console showed no calls.
    const inc = (n: number) => FieldValue.increment(n);
    const day = dayKey();
    const f = rec.feature;
    // A model id's dots and dashes become underscores in the map key.
    const model = rec.model_id.replace(/[^A-Za-z0-9_]/g, "_");
    // Nested maps, not "totals.socratic.calls" keys: set(…, { merge: true })
    // takes a dotted key as ONE field name, so every counter was written as a
    // flat field the console never reads (it reads totals.socratic.calls as a
    // path) and the console showed no calls at all (found 1.10.2026).
    const counters = () => ({ calls: inc(1), [rec.outcome]: inc(1), latency_sum_ms: inc(rec.latency_ms) });
    const update: Record<string, unknown> = {
      updated_at: Date.now(),
      model_id: rec.model_id,
      totals: { [f]: counters() },
      daily: { [day]: { [f]: counters() } },
      by_model: { [model]: { [f]: counters() } },
      last_call: { [f]: { at: Date.now(), outcome: rec.outcome, latency_ms: rec.latency_ms, model_id: rec.model_id } },
    };
    if (rec.outcome !== "ok" && rec.outcome !== "empty") {
      update.last_failure = { [f]: { at: Date.now(), outcome: rec.outcome, detail: rec.detail ?? null, model_id: rec.model_id } };
    }
    // After the answer has left: the first write of an instance builds the
    // Firestore client and loads its gRPC stack, synchronously — 0.3–0.4 s on
    // a warm disk, seconds on a cold one — and the card waited for it. In the
    // acceptance run of 2.10.2026 the first card after the warm-up spent
    // ~3.8 s outside the model; measured locally with a stubbed model, this
    // write was all of the first call's extra time. setImmediate runs after
    // the callable has sent its response (the promise chain returning from
    // the handler sends it first).
    setImmediate(() => {
      try {
        getFirestore().collection("store_cache").doc(AI_MONITORING_DOC).set(update, { merge: true }).catch((err) => {
          // A rules or connectivity problem must not spam every call; log once and go quiet.
          firestoreDisabled = true;
          logger.warn("[ai-monitor] counter write failed; disabling counters for this instance", { error: String(err) });
        });
      } catch (err) {
        logger.warn("[ai-monitor] counter write skipped", { error: String(err) });
      }
    });
  } catch (err) {
    logger.warn("[ai-monitor] counter write skipped", { error: String(err) });
  }
}

/**
 * The teacher's warm-up ping (TeacherDashboard, on activating a meeting)
 * builds the Firestore client and opens its channel with one read, so the
 * first child's card finds it ready. Reads only; never throws; bounded.
 */
export async function warmAiMonitoring(timeoutMs = 3000): Promise<void> {
  let timer: NodeJS.Timeout | undefined;
  try {
    await Promise.race([
      getFirestore().collection("store_cache").doc(AI_MONITORING_DOC).get(),
      new Promise((resolve) => { timer = setTimeout(resolve, timeoutMs); }),
    ]);
  } catch (err) {
    logger.warn("[ai-monitor] warm-up read failed", { error: String(err) });
  } finally {
    if (timer) clearTimeout(timer);
  }
}

/** Test seam. */
export function resetAiMonitoringState(): void {
  firestoreDisabled = false;
}

function callerIsStaff(token: Record<string, unknown> | undefined): boolean {
  if (!token) return false;
  const roles: string[] = Array.isArray(token.roles) ? (token.roles as string[]) : token.role ? [String(token.role)] : [];
  const lowered = roles.map((r) => r.toLowerCase());
  return lowered.includes("admin") || lowered.includes("teacher") || token.admin === true || token.teacher === true;
}

/** One live test call at most this often, for the whole project (it costs a model call). */
export const AI_TEST_CALL_MIN_INTERVAL_MS = 30_000;
/** The test call waits as long as a learner's card may: the client's 8 s. */
export const AI_TEST_CALL_TIMEOUT_MS = 8000;

export interface AiTestCallResult {
  at: number;
  model_id: string;
  ok: boolean;
  latency_ms: number;
  /** null when ok; else the classified code (timeout, misconfigured, auth, quota, network, safety, unknown). */
  error_code: string | null;
  /** A short, key-free excerpt of the error, for the owner to read. */
  error_detail: string | null;
}

let lastTestInThisInstance: AiTestCallResult | null = null;

/** The error text without anything that could be a key, and short. */
function safeErrorDetail(err: unknown): string {
  return String((err as { message?: unknown })?.message ?? err ?? "")
    .replace(/AIza[0-9A-Za-z_-]{10,}/g, "[key]")
    .replace(/key=[^&\s]+/gi, "key=[key]")
    .slice(0, 240);
}

/**
 * One real, tiny model call with the production key, model and SDK: the only
 * way to know that the coach answers right now. The counters only say how it
 * went for the learners who happened to ask.
 */
export async function runAiTestCall(): Promise<AiTestCallResult> {
  const started = Date.now();
  try {
    const res = await generateGeminiText({
      systemInstruction: 'Answer with the JSON object {"ok": true} and nothing else.',
      prompt: "ping",
      temperature: 0,
      json: true,
      // The coaching card's own model and thinking (gemini-3.8-flash refuses "minimal").
      model: SOCRATIC_PRIMARY_MODEL.id,
      thinking: SOCRATIC_PRIMARY_MODEL.thinking,
      timeoutMs: AI_TEST_CALL_TIMEOUT_MS,
    });
    let ok = false;
    try {
      ok = (JSON.parse(res.text) as { ok?: unknown })?.ok === true;
    } catch {
      ok = false;
    }
    return { at: started, model_id: GEMINI_MODEL_ID, ok, latency_ms: res.latency_ms, error_code: ok ? null : "not_json", error_detail: ok ? null : "the model answered, but not with the expected JSON" };
  } catch (err) {
    return { at: started, model_id: GEMINI_MODEL_ID, ok: false, latency_ms: Date.now() - started, error_code: classifyGeminiError(err), error_detail: safeErrorDetail(err) };
  }
}

/**
 * getAiServiceStatus — the admin console's view of the AI engine: whether the
 * key is bound (and where), which model is in use, and the aggregate counters
 * per feature and per model. Staff only; the key itself is never returned,
 * only its last four characters.
 *
 * With `{ test_call: true }` it also makes ONE real short model call and
 * reports ok / latency / error, so the owner can check at any time that the
 * coach answers. Rate-limited for the whole project: within
 * AI_TEST_CALL_MIN_INTERVAL_MS of the last test the last result comes back
 * (marked rate_limited) instead of a new call.
 */
export const getAiServiceStatus = onCall({ ...GEMINI_SECRETS, timeoutSeconds: 30 }, async (request) => {
  if (!request.auth) throw new HttpsError("unauthenticated", "Authentication required.");
  if (!callerIsStaff(request.auth.token as Record<string, unknown>)) {
    throw new HttpsError("permission-denied", "Staff role required.");
  }

  const key = getGeminiKeyStatus();
  const wantsTest = (request.data as { test_call?: unknown } | null)?.test_call === true;

  let counters: Record<string, unknown> | null = null;
  try {
    const snap = await getFirestore().collection("store_cache").doc(AI_MONITORING_DOC).get();
    counters = snap.exists ? (snap.data() as Record<string, unknown>) : null;
  } catch (err) {
    logger.warn("[ai-monitor] status read failed", { error: String(err) });
  }

  let test: (AiTestCallResult & { rate_limited?: boolean; in_progress?: boolean }) | null = null;
  if (wantsTest) {
    const stored = (counters?.last_test ?? null) as AiTestCallResult | null;
    const last = [stored, lastTestInThisInstance].filter((t): t is AiTestCallResult => Boolean(t && typeof t.at === "number"))
      .sort((a, b) => b.at - a.at)[0] ?? null;
    if (last && Date.now() - last.at < AI_TEST_CALL_MIN_INTERVAL_MS) {
      // A click while the previous test still runs is not a failed test: the
      // console says a test is already running (review of 1.10.2026: it showed
      // "המנוע לא ענה: in_progress").
      test = { ...last, rate_limited: true, ...(last.error_code === "in_progress" ? { in_progress: true } : {}) };
    } else if (!key.configured) {
      test = { at: Date.now(), model_id: GEMINI_MODEL_ID, ok: false, latency_ms: 0, error_code: "misconfigured", error_detail: key.problem };
    } else {
      // Claim the slot before the call, so two clicks a second apart make one call.
      lastTestInThisInstance = { at: Date.now(), model_id: GEMINI_MODEL_ID, ok: false, latency_ms: 0, error_code: "in_progress", error_detail: null };
      test = await runAiTestCall();
      lastTestInThisInstance = test;
      logger.info("[ai-monitor] live test call", { ok: test.ok, latency_ms: test.latency_ms, error_code: test.error_code, model_id: test.model_id });
      try {
        await getFirestore().collection("store_cache").doc(AI_MONITORING_DOC).set({ last_test: test }, { merge: true });
      } catch (err) {
        logger.warn("[ai-monitor] test result not stored", { error: String(err) });
      }
    }
  }

  return {
    checked_at: Date.now(),
    key,
    counters,
    today: dayKey(),
    ...(test ? { test } : {}),
  };
});
