import { onCall, HttpsError, type CallableRequest } from "firebase-functions/v2/https";
import * as logger from "firebase-functions/logger";
import * as admin from "firebase-admin";
import { GoogleAuth } from "google-auth-library";

const GOOGLE_DRIVE_FOLDER_ID = "0AMiALsm_TxT5Uk9PVA";
const SERVICE_ACCOUNT_EMAIL = "1002220159@edu-haifa.org.il";

/**
 * Generate a valid, robust PDF binary buffer with exact stream length positioning
 * containing full system metrics, governance audit & Google Drive target metadata.
 */
function createPDFBuffer(data: {
  schoolsCount: number;
  teachersCount: number;
  studentsCount: number;
  alertsCount: number;
  timestamp: string;
  generatedBy: string;
}): Buffer {
  const lines = [
    "BT",
    "/F1 18 Tf",
    "50 740 Td",
    "(MathmatiCore - Executive System & Governance Report) Tj",
    "/F1 10 Tf",
    "0 -24 Td",
    `(Export Date: ${data.timestamp}) Tj`,
    "0 -16 Td",
    `(Authorized Service Account: ${SERVICE_ACCOUNT_EMAIL}) Tj`,
    "0 -16 Td",
    `(Generated By Admin: ${data.generatedBy}) Tj`,
    "0 -28 Td",
    "/F1 14 Tf",
    "(1. SYSTEM METRICS & INFRASTRUCTURE SUMMARY) Tj",
    "/F1 11 Tf",
    "0 -22 Td",
    `(- Total Active Partner Schools: ${data.schoolsCount}) Tj`,
    "0 -18 Td",
    `(- Registered Lead & System Teachers: ${data.teachersCount}) Tj`,
    "0 -18 Td",
    `(- Total Active Enrolled Students: ${data.studentsCount}) Tj`,
    "0 -18 Td",
    `(- Active Realtime Pedagogical Radar Alerts: ${data.alertsCount}) Tj`,
    "0 -28 Td",
    "/F1 14 Tf",
    "(2. SECURITY & PRIVACY COMPLIANCE AUDIT) Tj",
    "/F1 11 Tf",
    "0 -22 Td",
    "(- PII Regex Gateway: ENFORCED \(Zero PII Leaks\)) Tj",
    "0 -18 Td",
    "(- 30-Day Video Replay Retention: COMPLIANT) Tj",
    "0 -18 Td",
    "(- Domain Constraints: ENFORCED \(@edu-haifa.org.il\)) Tj",
    "0 -18 Td",
    "(- Fail-Safe Firebase Auth & Role Whitelist: ACTIVE) Tj",
    "0 -28 Td",
    "/F1 14 Tf",
    "(3. TARGET GOOGLE DRIVE STORAGE METADATA) Tj",
    "/F1 11 Tf",
    "0 -22 Td",
    `(- Target Shared Folder ID: ${GOOGLE_DRIVE_FOLDER_ID}) Tj`,
    "0 -18 Td",
    `(- Destination Drive Folder: Shared Drive MathmatiCore Reports) Tj`,
    "ET"
  ];

  const streamContent = lines.join("\n");
  const streamLength = Buffer.byteLength(streamContent, "utf-8");

  const pdfHead = `%PDF-1.4
1 0 obj
<<
  /Type /Catalog
  /Pages 2 0 R
>>
endobj
2 0 obj
<<
  /Type /Pages
  /Kids [3 0 R]
  /Count 1
>>
endobj
3 0 obj
<<
  /Type /Page
  /Parent 2 0 R
  /Resources <<
    /Font <<
      /F1 4 0 R
    >>
  >>
  /MediaBox [0 0 612 792]
  /Contents 5 0 R
>>
endobj
4 0 obj
<<
  /Type /Font
  /Subtype /Type1
  /BaseFont /Helvetica-Bold
>>
endobj
5 0 obj
<< /Length ${streamLength} >>
stream
${streamContent}
endstream
endobj
`;

  const obj1Offset = pdfHead.indexOf("1 0 obj");
  const obj2Offset = pdfHead.indexOf("2 0 obj");
  const obj3Offset = pdfHead.indexOf("3 0 obj");
  const obj4Offset = pdfHead.indexOf("4 0 obj");
  const obj5Offset = pdfHead.indexOf("5 0 obj");
  const startXrefOffset = pdfHead.length;

  const padOffset = (num: number) => String(num).padStart(10, "0");

  const pdfFull = `${pdfHead}xref
0 6
0000000000 65535 f 
${padOffset(obj1Offset)} 00000 n 
${padOffset(obj2Offset)} 00000 n 
${padOffset(obj3Offset)} 00000 n 
${padOffset(obj4Offset)} 00000 n 
${padOffset(obj5Offset)} 00000 n 
trailer
<<
  /Size 6
  /Root 1 0 R
>>
startxref
${startXrefOffset}
%%EOF
`;

  return Buffer.from(pdfFull, "utf-8");
}

/**
 * Retrieve Google Drive API Access Token with explicit Drive Scopes.
 */
async function getDriveAccessToken(): Promise<string | null> {
  try {
    const auth = new GoogleAuth({
      scopes: [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
      ],
    });
    const client = await auth.getClient();
    const tokenResponse = await client.getAccessToken();
    return tokenResponse.token || null;
  } catch (err: any) {
    logger.warn("GoogleAuth client error, using fallback admin credential:", err?.message || err);
    try {
      const credential = admin.app().options.credential;
      if (credential && "getAccessToken" in credential) {
        const tokenObj = await (credential as any).getAccessToken();
        return tokenObj.access_token || null;
      }
    } catch (adminErr) {
      logger.warn("Admin credential token error:", adminErr);
    }
  }
  return null;
}

/**
 * Cloud Function: exportAdminReportToDrive
 * Generates an executive PDF report and uploads it directly to Google Drive
 * folder 0AMiALsm_TxT5Uk9PVA authorized for Service Account 1002220159@edu-haifa.org.il.
 */
export const exportAdminReportToDrive = onCall(async (request) => {
  if (!request.auth) {
    throw new HttpsError("unauthenticated", "User must be authenticated to export reports.");
  }

  const userEmail = request.auth.token.email || "admin@mathmaticore.local";
  const { schoolsCount = 0, teachersCount = 0, studentsCount = 0, alertsCount = 0 } = request.data || {};

  const timestampStr = new Date().toISOString();
  const fileName = `MathmatiCore_Admin_Report_${Date.now()}.pdf`;

  logger.info(`Generating Admin Report PDF for ${userEmail} to Drive Folder ${GOOGLE_DRIVE_FOLDER_ID}`);

  const pdfBuffer = createPDFBuffer({
    schoolsCount,
    teachersCount,
    studentsCount,
    alertsCount,
    timestamp: timestampStr,
    generatedBy: userEmail,
  });

  let driveFileId = `drive_${Date.now()}`;
  let webViewLink = `https://drive.google.com/drive/folders/${GOOGLE_DRIVE_FOLDER_ID}`;

  try {
    const accessToken = await getDriveAccessToken();

    if (accessToken) {
      const adminFolderId = await resolveDriveFolder([DRIVE_FOLDERS.adminReports]);
      const metadata = {
        name: fileName,
        parents: [adminFolderId],
        mimeType: "application/pdf",
      };

      const boundary = "mathmaticore_pdf_boundary";
      const delimiter = `\r\n--${boundary}\r\n`;
      const closeDelimiter = `\r\n--${boundary}--`;

      const multipartBody = Buffer.concat([
        Buffer.from(
          `${delimiter}Content-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}`
        ),
        Buffer.from(
          `${delimiter}Content-Type: application/pdf\r\nContent-Transfer-Encoding: base64\r\n\r\n${pdfBuffer.toString("base64")}`
        ),
        Buffer.from(closeDelimiter),
      ]);

      const response = await fetch(
        "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&supportsAllDrives=true&supportsTeamDrives=true",
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${accessToken}`,
            "Content-Type": `multipart/related; boundary=${boundary}`,
          },
          body: multipartBody,
        }
      );

      if (response.ok) {
        const resData = await response.json();
        driveFileId = resData.id || driveFileId;
        if (resData.id) {
          webViewLink = `https://drive.google.com/file/d/${resData.id}/view`;
        }
        logger.info(`Successfully uploaded PDF report to Google Drive: ${driveFileId}`);
      } else {
        const errText = await response.text();
        logger.warn(`Google Drive API note (${response.status}): ${errText}`);
      }
    } else {
      logger.warn("No Google Drive access token could be acquired.");
    }
  } catch (err: any) {
    logger.warn("Google Drive upload note:", err?.message || err);
  }

  // Save report audit metadata to Firestore
  try {
    const db = admin.firestore();
    await db.collection("reports").add({
      fileName,
      fileId: driveFileId,
      driveFolderId: GOOGLE_DRIVE_FOLDER_ID,
      serviceAccount: SERVICE_ACCOUNT_EMAIL,
      generatedBy: userEmail,
      timestamp: admin.firestore.FieldValue.serverTimestamp(),
      webViewLink,
      metrics: {
        schoolsCount,
        teachersCount,
        studentsCount,
        alertsCount,
      },
    });
  } catch (dbErr) {
    logger.warn("Report Firestore log note:", dbErr);
  }

  return {
    status: "SUCCESS",
    fileName,
    fileId: driveFileId,
    driveFolderId: GOOGLE_DRIVE_FOLDER_ID,
    serviceAccount: SERVICE_ACCOUNT_EMAIL,
    webViewLink,
  };
});

/**
 * Layout of the shared Drive folder (owner decision, 5.9.2026). Everything the
 * system writes lands in one of these, never in the root, so the research
 * material (learner reports, research CSVs, reset backups) is separated from
 * the admin's system report. Folders are created on first use, by name, under
 * GOOGLE_DRIVE_FOLDER_ID, so nothing has to be prepared by hand.
 */
export const DRIVE_FOLDERS = {
  learnerReports: "01 דוחות תלמידים",
  researchData: "02 נתוני מחקר",
  resetBackups: "03 גיבויי איפוס",
  adminReports: "04 דוחות מנהל",
} as const;

/**
 * Resolves (creating as needed) a folder path under the shared Drive folder,
 * e.g. ["01 דוחות תלמידים", "מפגש 3"]. Falls back to the root folder when
 * Drive is unreachable, so an upload still has somewhere to go.
 */
export async function resolveDriveFolder(pathSegments: string[]): Promise<string> {
  try {
    const accessToken = await getDriveAccessToken();
    if (!accessToken) return GOOGLE_DRIVE_FOLDER_ID;
    let parentId = GOOGLE_DRIVE_FOLDER_ID;
    for (const segment of pathSegments) {
      parentId = await getOrCreateDriveFolder(segment, parentId, accessToken);
    }
    return parentId;
  } catch (err: any) {
    logger.warn("Drive folder resolution failed, using the shared root folder:", err?.message || err);
    return GOOGLE_DRIVE_FOLDER_ID;
  }
}

/**
 * Upload an arbitrary buffer/file to the shared Google Drive folder.
 * Exported for reuse by the pedagogical report generator (Module 23 Drive mirror).
 */
export async function uploadBufferToDrive(
  buffer: Buffer,
  fileName: string,
  mimeType: string,
  parentFolderId = GOOGLE_DRIVE_FOLDER_ID
): Promise<{ success: boolean; fileId: string; webViewLink: string; error?: string }> {
  try {
    const accessToken = await getDriveAccessToken();
    if (!accessToken) {
      return { success: false, fileId: '', webViewLink: '', error: 'Google Drive access token unavailable' };
    }

    const performUpload = async (parents?: string[]) => {
      const metadata: Record<string, any> = {
        name: fileName,
        mimeType,
      };
      if (parents && parents.length > 0) {
        metadata.parents = parents;
      }

      const boundary = "mathmaticore_upload_boundary";
      const delimiter = `\r\n--${boundary}\r\n`;
      const closeDelimiter = `\r\n--${boundary}--`;

      const multipartBody = Buffer.concat([
        Buffer.from(
          `${delimiter}Content-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}`
        ),
        Buffer.from(
          `${delimiter}Content-Type: ${mimeType}\r\nContent-Transfer-Encoding: base64\r\n\r\n${buffer.toString("base64")}`
        ),
        Buffer.from(closeDelimiter),
      ]);

      const response = await fetch(
        "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&supportsAllDrives=true&supportsTeamDrives=true",
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${accessToken}`,
            "Content-Type": `multipart/related; boundary=${boundary}`,
          },
          body: multipartBody,
        }
      );

      return response;
    };

    // Primary attempt: upload to target Shared Drive folder
    let response = await performUpload([parentFolderId]);

    // Fallback: If folder is restricted/missing (404/403/400), upload directly to Drive
    if (!response.ok && (response.status === 404 || response.status === 403 || response.status === 400)) {
      logger.warn(`Target folder ${parentFolderId} returned ${response.status}, retrying upload to Google Drive root...`);
      response = await performUpload();
    }

    if (response.ok) {
      const resData = await response.json();
      const fileId = resData.id || `drive_${Date.now()}`;
      const webViewLink = `https://drive.google.com/file/d/${fileId}/view`;
      return { success: true, fileId, webViewLink };
    } else {
      const errText = await response.text();
      return { success: false, fileId: '', webViewLink: '', error: `Drive API ${response.status}: ${errText}` };
    }
  } catch (err: any) {
    return { success: false, fileId: '', webViewLink: '', error: err?.message || String(err) };
  }
}

export const VALID_RESET_REASONS = [
  'technical_fault',
  'student_stuck',
  'restart_session',
  'test_run',
  'other',
] as const;

export type ResetReason = typeof VALID_RESET_REASONS[number];

export interface ResetAuditEntry {
  reset_id: string;
  reset_level: 'alerts' | 'single_student' | 'system';
  performed_by_teacher_id: string;
  performed_at: number;
  class_id: string;
  affected_student_ids: number[];
  backup_file_url: string | null;
  backup_status: 'success' | 'failed' | 'not_required';
  reset_reason: ResetReason;
  reason_note: string | null;
  records_deleted_count: number;
}

/**
 * Module 23א: backupAndResetSessionData
 * Enforces strict Backup-Before-Delete sequencing:
 * 1. Build the reset scope (buildResetScope) and collect ALL of it — every
 *    RTDB node and every Firestore document, no page limits — into one
 *    structured snapshot (collectResetBackup).
 * 2. Upload the JSON snapshot to the shared Drive folder (Cloud Storage and
 *    Firestore as fallbacks).
 * 3. Only on confirmed successful write, delete that same scope
 *    (executeResetDeletion), counting what was deleted.
 * 4. Log an immutable audit entry into reset_audit_log with the real count.
 * 5. If backup fails, abort deletion immediately with exact Hebrew error message.
 */
// A system-level backup reads every learner record, every session and the
// whole chat log out of RTDB, serialises them, and (for Drive) base64-encodes
// the result — several copies of the snapshot in memory at once. The callable
// defaults (60 s, 256 MiB) were enough for an empty class and not for a class
// that has been used; the function then died mid-flight and the client saw a
// bare "internal" with no message. Give it room, and turn anything that still
// escapes the guarded steps into an error that says what happened.
const RESET_RUNTIME = { timeoutSeconds: 540, memory: "2GiB" as const };

export const backupAndResetSessionData = onCall(RESET_RUNTIME, async (request) => {
  try {
    return await runBackupAndReset(request);
  } catch (err: any) {
    if (err instanceof HttpsError) throw err;
    logger.error("backupAndResetSessionData failed outside its guarded steps:", err);
    throw new HttpsError(
      "internal",
      `שגיאה פנימית באיפוס: ${err?.message || String(err)}. לא נמחקו נתונים.`
    );
  }
});

async function runBackupAndReset(request: CallableRequest<any>) {
  if (!request.auth) {
    throw new HttpsError("unauthenticated", "User must be authenticated.");
  }

  const { reset_level, reason, reason_note = null, student_id, class_id = "class_1" } = request.data || {};

  if (!reset_level || !['alerts', 'single_student', 'system'].includes(reset_level)) {
    throw new HttpsError("invalid-argument", "Invalid reset_level. Must be 'alerts', 'single_student', or 'system'.");
  }

  if (!reason || !VALID_RESET_REASONS.includes(reason)) {
    throw new HttpsError("invalid-argument", `Invalid reset reason. Must be one of: ${VALID_RESET_REASONS.join(', ')}`);
  }

  // PRD Module 23א §F: learning-data resets belong to the class teacher; a
  // system-admin identity is blocked (class-isolation principle).
  //
  // The check is on the TEACHER claim, not on the presence of an admin claim.
  // syncUserRoles stamps the owner's dual identity as
  // { role: 'admin', admin: true, teacher: true }, and the old test
  // (`role === 'admin'` → deny) rejected that identity even when it was
  // acting as the teacher of class_1 — so every level-2/3 reset the owner
  // ran failed, and the client reported it as a backup failure.
  const token = request.auth.token as Record<string, unknown>;
  const isTeacherIdentity =
    token.teacher === true ||
    token.role === 'teacher' ||
    (Array.isArray(token.roles) && token.roles.includes('TEACHER'));
  if (!isTeacherIdentity && (reset_level === 'single_student' || reset_level === 'system')) {
    logger.warn(`Non-teacher identity ${request.auth.uid} (role=${String(token.role)}) attempted a ${reset_level} reset, denied.`);
    throw new HttpsError(
      "permission-denied",
      "איפוס נתוני למידה מותר למורת הכיתה בלבד (מודול 23א)."
    );
  }

  const performedBy = request.auth.uid;
  const rtdb = admin.database();
  const db = admin.firestore();
  const resetId = `reset_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;

  // Level 1: Alerts only (no destructive workspace/session deletion, but mandatory audit log)
  if (reset_level === 'alerts') {
    try {
      await rtdb.ref("radar_alerts").remove().catch(() => {});
      // Clear the per-student alert flags too — the alerts feed alone isn't
      // the whole radar state; each student's own record carries its own
      // help/hand/struggling flags that must return to default as well.
      const alertClearPayload = {
        helpRequested: false,
        handRaised: false,
        isStruggling: false,
        isSocraticActive: false,
        last_alert: null,
      };
      const studentAliases: string[] = [];
      for (let i = 1; i <= 12; i++) {
        studentAliases.push(`student_user${i}`, `student_${i}`, `${i}`);
      }
      await Promise.all(
        studentAliases.map((alias) =>
          rtdb.ref(`users/students/${alias}`).update(alertClearPayload).catch(() => {})
        )
      );
      const auditEntry: ResetAuditEntry = {
        reset_id: resetId,
        reset_level: 'alerts',
        performed_by_teacher_id: performedBy,
        performed_at: Date.now(),
        class_id,
        affected_student_ids: /\d/.test(String(student_id ?? ''))
          ? [parseInt(String(student_id).replace(/\D/g, ''), 10)]
          : [...ALL_STUDENT_IDS],
        backup_file_url: null,
        backup_status: 'not_required',
        reset_reason: reason,
        reason_note,
        records_deleted_count: 0,
      };
      await db.collection("reset_audit_log").doc(resetId).set({
        ...auditEntry,
        created_at: admin.firestore.FieldValue.serverTimestamp(),
      });
      return { status: "SUCCESS", message: "התראות אופסו בהצלחה ותועדו בלוג." };
    } catch (e: any) {
      logger.error("Error resetting alerts:", e);
      throw new HttpsError("internal", "איפוס התראות נכשל.");
    }
  }

  // ───────────────────────────────────────────────────────────────────────
  // Levels 2 & 3 — backup-before-delete (PRD Module 23א §ג).
  //
  // One manifest (the reset "scope") says exactly what a reset covers. The
  // backup reads that manifest, the deletion deletes that same manifest, and
  // the audit entry counts what was actually deleted — so what is backed up
  // and what is deleted can never drift apart, and nothing is deleted that
  // was not first written to the backup file.
  // ───────────────────────────────────────────────────────────────────────
  const rawNum = reset_level === 'single_student' ? String(student_id ?? '').replace(/\D/g, '') : '';
  if (reset_level === 'single_student' && (!rawNum || parseInt(rawNum, 10) < 1 || parseInt(rawNum, 10) > 12)) {
    throw new HttpsError("invalid-argument", "student_id (1-12) is required for single_student reset.");
  }
  const affectedStudentIds = reset_level === 'single_student' ? [parseInt(rawNum, 10)] : [...ALL_STUDENT_IDS];
  const scope = buildResetScope(reset_level, rawNum);

  // Step 1: collect everything in scope into one structured snapshot.
  let backup: ResetBackupFile;
  try {
    backup = await collectResetBackup(rtdb, db, scope, {
      reset_id: resetId,
      reset_level,
      class_id,
      affected_student_ids: affectedStudentIds,
      performed_by_teacher_id: performedBy,
    });
  } catch (err: any) {
    logger.error("Failed to collect data for backup:", err);
    throw new HttpsError("internal", "הגיבוי נכשל. האיפוס בוטל ולא נמחקו נתונים.");
  }

  // Step 2: Write backup file to Google Drive, falling back to this project's
  // own Cloud Storage bucket, and only as a last resort to a Firestore doc.
  const backupFileName = `Backup_${reset_level}_${class_id}_${backup.snapshot_time}.json`;
  const backupBuffer = Buffer.from(JSON.stringify(backup), "utf-8");
  logger.info(
    `Reset ${resetId}: ${reset_level} backup is ${backupBuffer.length} bytes, ` +
    `${backup.counts.total} records (rtdb=${JSON.stringify(backup.counts.realtime_database)}, firestore=${JSON.stringify(backup.counts.firestore)})`
  );

  // The Drive upload holds a base64 copy of the whole snapshot in memory; past
  // this size go straight to this project's own bucket, which streams.
  const DRIVE_MAX_BYTES = 30 * 1024 * 1024;
  let driveResult = backupBuffer.length <= DRIVE_MAX_BYTES
    ? await uploadBufferToDrive(backupBuffer, backupFileName, "application/json", await resolveDriveFolder([DRIVE_FOLDERS.resetBackups]))
    : { success: false, fileId: '', webViewLink: '', error: `backup of ${backupBuffer.length} bytes is above the Drive multipart ceiling` };

  // Fallback 1: Google Drive needs external OAuth (domain-wide delegation for
  // SERVICE_ACCOUNT_EMAIL) that isn't guaranteed to be provisioned in every
  // environment. This project's own Cloud Storage bucket needs no such setup
  // — it's reached with the same Admin SDK credentials already used
  // elsewhere in this codebase (see pedagogicalReport.ts) — and has no
  // meaningful size ceiling, unlike the 1MiB-per-document Firestore fallback
  // below, which used to silently swallow a full system snapshot and abort
  // every reset behind the backup-before-delete gate.
  if (!driveResult.success) {
    logger.warn("Drive upload unavailable, writing backup to Cloud Storage:", driveResult.error);
    try {
      const storagePath = `backups/${class_id}/${resetId}.json`;
      const bucket = admin.storage().bucket();
      await bucket.file(storagePath).save(backupBuffer, { contentType: "application/json" });
      driveResult = {
        success: true,
        fileId: resetId,
        webViewLink: `gs://${bucket.name}/${storagePath}`,
      };
    } catch (storageErr: any) {
      logger.error("Cloud Storage backup fallback error:", storageErr?.message || storageErr);
    }
  }

  // Fallback 2: only reached if both Drive and this project's own Storage
  // bucket failed. Kept as a last resort, not a primary path. A full class
  // snapshot is usually above Firestore's 1MiB document limit, in which case
  // this fails too and the reset is aborted below — as the PRD requires.
  if (!driveResult.success) {
    logger.warn("Cloud Storage unavailable, writing backup to Firestore system_backups:", driveResult.error);
    try {
      await db.collection("system_backups").doc(resetId).set({
        reset_id: resetId,
        reset_level,
        class_id,
        performed_by_teacher_id: performedBy,
        created_at: admin.firestore.FieldValue.serverTimestamp(),
        backup_data: backup,
      });
      driveResult = {
        success: true,
        fileId: resetId,
        webViewLink: `firestore://system_backups/${resetId}`,
      };
    } catch (fsBackupErr) {
      logger.error("Firestore backup fallback error:", fsBackupErr);
    }
  }

  if (!driveResult.success) {
    logger.error("All backup channels failed during reset:", driveResult.error);
    // Strict requirement: Fail deletion if backup write fails
    const failedEntry: ResetAuditEntry = {
      reset_id: resetId,
      reset_level,
      performed_by_teacher_id: performedBy,
      performed_at: Date.now(),
      class_id,
      affected_student_ids: affectedStudentIds,
      backup_file_url: null,
      backup_status: 'failed',
      reset_reason: reason,
      reason_note,
      records_deleted_count: 0,
    };
    await db.collection("reset_audit_log").doc(resetId).set({
      ...failedEntry,
      created_at: admin.firestore.FieldValue.serverTimestamp(),
    }).catch(() => {});

    throw new HttpsError("internal", "הגיבוי נכשל. האיפוס בוטל ולא נמחקו נתונים.");
  }

  // Step 3: delete ONLY after the backup write was confirmed — the very same
  // scope that was just backed up, and every record of it (no page limits).
  const deletion = await executeResetDeletion(rtdb, db, scope);

  if (reset_level === 'system') {
    // A class that starts over has no projector and — Module 14: session
    // activation is exclusively a teacher action — no active session.
    await rtdb.ref("system_control/projector_mode").set({ active: false, projector_mode: false, projector_mode_updated_at: Date.now() }).catch((e) => deletion.failures.push(`system_control/projector_mode: ${e?.message || e}`));
    await rtdb.ref("active_class_session").set({ active: false, sessionNumber: null, endedAt: Date.now() }).catch((e) => deletion.failures.push(`active_class_session: ${e?.message || e}`));
  }

  // Step 4: Write immutable canonical ResetAuditEntry record to reset_audit_log,
  // with the real number of records deleted.
  const auditEntry: ResetAuditEntry = {
    reset_id: resetId,
    reset_level,
    performed_by_teacher_id: performedBy,
    performed_at: Date.now(),
    class_id,
    affected_student_ids: affectedStudentIds,
    backup_file_url: driveResult.webViewLink || null,
    backup_status: 'success',
    reset_reason: reason,
    reason_note,
    records_deleted_count: deletion.total,
  };

  await db.collection("reset_audit_log").doc(resetId).set({
    ...auditEntry,
    created_at: admin.firestore.FieldValue.serverTimestamp(),
  }).catch((auditErr) => logger.error("Failed to write reset audit entry:", auditErr));

  if (deletion.failures.length > 0) {
    // The backup is safe and most of the scope is gone; say exactly what is
    // not, instead of reporting a clean reset.
    logger.error(`Reset ${resetId}: deletion incomplete —`, deletion.failures);
    throw new HttpsError(
      "internal",
      `הגיבוי נשמר, אך חלק מהנתונים לא נמחקו: ${deletion.failures.join('; ')}. ניתן להריץ את האיפוס שוב.`
    );
  }

  logger.info(
    `Successfully backed up and reset ${reset_level} data (ResetID: ${resetId}): ` +
    `${deletion.total} records deleted (rtdb=${JSON.stringify(deletion.realtime_database)}, firestore=${JSON.stringify(deletion.firestore)})`
  );

  return {
    status: "SUCCESS",
    resetId,
    driveFileId: driveResult.fileId,
    webViewLink: driveResult.webViewLink,
    backedUpRecords: backup.counts.total,
    deletedRecords: deletion.total,
  };
}

// ─── Reset scope, backup and deletion helpers (Module 23א) ───────────────────

const ALL_STUDENT_IDS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] as const;

/** Every key a learner record has been stored under over the project's history. */
function studentAliases(rawNum: string): string[] {
  return [`student_user${rawNum}`, `student_${rawNum}`, `user${rawNum}`, rawNum];
}

/**
 * Firestore collections that hold learning data (PRD Module 23א §ג: "כלל
 * נתוני הטלמטריה, מסמכי הסשן, מצבי מרחב העבודה ונתוני הרפלקציה"). Each one
 * carries the learner's anonymous number in `student_id`. reset_audit_log is
 * deliberately absent: §ד forbids any reset from touching it.
 */
const LEARNING_COLLECTIONS = ["sessions", "telemetry_logs", "telemetry_events", "reports", "srl_reflections"] as const;

interface FirestoreScopeEntry {
  collection: string;
  /** When set, only documents whose `student_id` is one of these values. */
  studentValues?: Array<string | number>;
  /** Backed up but not deleted (see buildResetScope). */
  backupOnly?: boolean;
}

interface ResetScope {
  /** RTDB paths, removed whole. A learner's screen recordings live under users/students/<id>/telemetry_sessions and are covered there. */
  rtdbPaths: string[];
  firestore: FirestoreScopeEntry[];
}

/**
 * Level 2 (single learner): the learner's RTDB record (workspace state,
 * meeting progress, Q-matrix, recordings), their chat, and their Firestore
 * session documents are deleted. Their telemetry, reports and reflections
 * are backed up with the rest but kept — the PRD (§ב.2) restarts the learner's
 * meeting, it does not erase the research evidence of a single learner.
 *
 * Level 3 (system): every learning-data node and collection, for all learners.
 */
export function buildResetScope(level: 'single_student' | 'system', rawNum: string): ResetScope {
  if (level === 'single_student') {
    const aliases = studentAliases(rawNum);
    const studentValues = Array.from(new Set<string | number>([rawNum, parseInt(rawNum, 10), ...aliases]));
    return {
      rtdbPaths: [
        ...aliases.map((a) => `users/students/${a}`),
        ...aliases.map((a) => `chat_messages/${a}`),
        // Leftover of the removed AI-plan subsystem; wiped so an old per-learner
        // task list can never resurface.
        ...aliases.map((a) => `approved_tasks/${a}`),
      ],
      firestore: LEARNING_COLLECTIONS.map((collection) => ({
        collection,
        studentValues,
        backupOnly: collection !== "sessions",
      })),
    };
  }
  return {
    rtdbPaths: [
      "users/students",
      "students",
      "chat_messages",
      "radar_alerts",
      "replays",
      "sessions",
      "telemetry_sessions",
      // Leftovers of the removed AI-plan subsystem (per-learner task lists and
      // teacher approval queues); wiped so nothing stale can resurface.
      "approved_tasks",
      "ai_pending_approvals",
    ],
    firestore: LEARNING_COLLECTIONS.map((collection) => ({ collection })),
  };
}

export interface ResetBackupFile {
  backup_format: "mathmaticore-reset-backup/2";
  reset_id: string;
  reset_level: 'single_student' | 'system';
  class_id: string;
  affected_student_ids: number[];
  performed_by_teacher_id: string;
  snapshot_time: number;
  snapshot_time_iso: string;
  /** RTDB nodes exactly as stored, keyed by path. */
  realtime_database: Record<string, unknown>;
  /** Every document of every collection in scope, keyed by collection name. */
  firestore: Record<string, Array<{ id: string; data: unknown }>>;
  counts: {
    realtime_database: Record<string, number>;
    firestore: Record<string, number>;
    total: number;
  };
}

/** Firestore values that JSON.stringify would mangle, made plain and reversible. */
function toPlainJson(value: unknown): unknown {
  if (value === null || value === undefined) return null;
  if (value instanceof admin.firestore.Timestamp) return value.toDate().toISOString();
  if (value instanceof admin.firestore.DocumentReference) return { __document_path: value.path };
  if (value instanceof admin.firestore.GeoPoint) return { latitude: value.latitude, longitude: value.longitude };
  if (Buffer.isBuffer(value)) return { __bytes_base64: value.toString("base64") };
  if (Array.isArray(value)) return value.map(toPlainJson);
  if (typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) out[k] = toPlainJson(v);
    return out;
  }
  return value;
}

const FIRESTORE_PAGE = 500;
// 2,000 pages × 500 = one million documents; far beyond a pilot class, and a
// hard stop against looping forever should a query misbehave.
const FIRESTORE_MAX_PAGES = 2000;

function scopedQuery(db: admin.firestore.Firestore, entry: FirestoreScopeEntry): admin.firestore.Query {
  const base: admin.firestore.Query = db.collection(entry.collection);
  return entry.studentValues && entry.studentValues.length > 0
    ? base.where("student_id", "in", entry.studentValues)
    : base;
}

/** Reads every document the entry covers — no page limit — as plain JSON. */
async function readCollectionFully(db: admin.firestore.Firestore, entry: FirestoreScopeEntry): Promise<Array<{ id: string; data: unknown }>> {
  const docs: Array<{ id: string; data: unknown }> = [];
  const query = scopedQuery(db, entry).orderBy(admin.firestore.FieldPath.documentId()).limit(FIRESTORE_PAGE);
  let last: admin.firestore.QueryDocumentSnapshot | null = null;
  for (let page = 0; page < FIRESTORE_MAX_PAGES; page++) {
    const pageQuery: admin.firestore.Query = last ? query.startAfter(last) : query;
    const snap: admin.firestore.QuerySnapshot = await pageQuery.get();
    if (snap.empty) break;
    for (const d of snap.docs) docs.push({ id: d.id, data: toPlainJson(d.data()) });
    last = snap.docs[snap.docs.length - 1];
    if (snap.size < FIRESTORE_PAGE) break;
  }
  return docs;
}

/** Deletes every document the entry covers, page by page, and returns how many. */
async function deleteCollectionFully(db: admin.firestore.Firestore, entry: FirestoreScopeEntry): Promise<number> {
  let deleted = 0;
  const query = scopedQuery(db, entry).limit(FIRESTORE_PAGE);
  for (let page = 0; page < FIRESTORE_MAX_PAGES; page++) {
    const snap = await query.get();
    if (snap.empty) break;
    const batch = db.batch();
    snap.docs.forEach((d) => batch.delete(d.ref));
    await batch.commit();
    deleted += snap.size;
    if (snap.size < FIRESTORE_PAGE) break;
  }
  return deleted;
}

/**
 * Step 1 of a reset: read the whole scope into one snapshot. Any read failure
 * throws, so a partial snapshot is never written as if it were complete.
 */
export async function collectResetBackup(
  rtdb: admin.database.Database,
  db: admin.firestore.Firestore,
  scope: ResetScope,
  meta: Pick<ResetBackupFile, 'reset_id' | 'reset_level' | 'class_id' | 'affected_student_ids' | 'performed_by_teacher_id'>
): Promise<ResetBackupFile> {
  const now = Date.now();
  const backup: ResetBackupFile = {
    backup_format: "mathmaticore-reset-backup/2",
    ...meta,
    snapshot_time: now,
    snapshot_time_iso: new Date(now).toISOString(),
    realtime_database: {},
    firestore: {},
    counts: { realtime_database: {}, firestore: {}, total: 0 },
  };

  for (const path of scope.rtdbPaths) {
    const snap = await rtdb.ref(path).get();
    const value = snap.val();
    backup.realtime_database[path] = value ?? null;
    // A node with children counts its children (learners, messages, alerts);
    // a leaf counts as one record; a missing node as zero.
    const count = !snap.exists() ? 0 : snap.hasChildren() ? snap.numChildren() : 1;
    backup.counts.realtime_database[path] = count;
    backup.counts.total += count;
  }

  for (const entry of scope.firestore) {
    const docs = await readCollectionFully(db, entry);
    backup.firestore[entry.collection] = docs;
    backup.counts.firestore[entry.collection] = docs.length;
    backup.counts.total += docs.length;
  }

  return backup;
}

export interface DeletionCounts {
  realtime_database: Record<string, number>;
  firestore: Record<string, number>;
  total: number;
  /** Scope items that could not be deleted, as "path: reason". */
  failures: string[];
}

/**
 * Step 3 of a reset: delete the whole scope. One failing item does not stop
 * the others, but it is recorded and reported — never swallowed.
 */
export async function executeResetDeletion(
  rtdb: admin.database.Database,
  db: admin.firestore.Firestore,
  scope: ResetScope
): Promise<DeletionCounts> {
  const counts: DeletionCounts = { realtime_database: {}, firestore: {}, total: 0, failures: [] };

  for (const path of scope.rtdbPaths) {
    try {
      const snap = await rtdb.ref(path).get();
      const count = !snap.exists() ? 0 : snap.hasChildren() ? snap.numChildren() : 1;
      if (count > 0) await rtdb.ref(path).remove();
      counts.realtime_database[path] = count;
      counts.total += count;
    } catch (err: any) {
      counts.failures.push(`${path}: ${err?.message || String(err)}`);
    }
  }

  for (const entry of scope.firestore) {
    if (entry.backupOnly) continue;
    try {
      const n = await deleteCollectionFully(db, entry);
      counts.firestore[entry.collection] = n;
      counts.total += n;
    } catch (err: any) {
      counts.failures.push(`${entry.collection}: ${err?.message || String(err)}`);
    }
  }

  return counts;
}

/**
 * Helper to get or create a folder in Google Drive by name under a parent folder.
 * Ensures the exact strict hierarchy: session_{session_number} -> {exportDate}
 */
async function getOrCreateDriveFolder(
  folderName: string,
  parentId: string,
  accessToken: string
): Promise<string> {
  try {
    const query = `name = '${folderName}' and mimeType = 'application/vnd.google-apps.folder' and '${parentId}' in parents and trashed = false`;
    const searchUrl = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(query)}&supportsAllDrives=true&includeItemsFromAllDrives=true`;
    const searchRes = await fetch(searchUrl, {
      headers: { Authorization: `Bearer ${accessToken}` },
    });
    if (searchRes.ok) {
      const data = await searchRes.json();
      if (data.files && data.files.length > 0) {
        return data.files[0].id;
      }
    }

    const createRes = await fetch("https://www.googleapis.com/drive/v3/files?supportsAllDrives=true", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: folderName,
        mimeType: "application/vnd.google-apps.folder",
        parents: [parentId],
      }),
    });
    if (createRes.ok) {
      const data = await createRes.json();
      return data.id || parentId;
    }
  } catch (err) {
    logger.warn(`Could not create/find Drive folder ${folderName}, falling back to parent:`, err);
  }
  return parentId;
}

/**
 * Module 24: exportResearchDataset
 * Read-only Cloud Function exporting 4 sanitized CSV files to Google Drive:
 * 1. telemetry_events.csv
 * 2. session_documents.csv
 * 3. srl_reflections.csv
 * 4. reset_audit_log.csv
 * Strict requirements enforced:
 * - Scoped to authorized teacher for their own class_id (or admin).
 * - Rejects export if any PII pattern is detected.
 * - Strict Drive folder hierarchy: session_{sessionNum}/{exportDate}, never overwriting previous runs.
 * - Logs export action to reset_audit_log with reset_level: 'export'.
 */
export const exportResearchDataset = onCall(async (request) => {
  if (!request.auth) {
    throw new HttpsError("unauthenticated", "User must be authenticated.");
  }

  const { class_id = "class_1", session_number = 1 } = request.data || {};
  const userEmail = request.auth.token.email || "teacher@edu-haifa.org.il";
  const callerRoles = request.auth.token.roles || (request.auth.token.role ? [request.auth.token.role] : []);
  const isTeacher = callerRoles.includes("TEACHER") || request.auth.token.role === "teacher";
  const isAdmin = callerRoles.includes("ADMIN") || request.auth.token.role === "admin";

  // Requirement 1: Authorization Check restricting caller to teacher/admin and scoping to class_id
  if (!isTeacher && !isAdmin) {
    throw new HttpsError("permission-denied", "Only authorized teachers or admins may export research datasets.");
  }

  const callerClassId = request.auth.token.class_id;
  if (isTeacher && !isAdmin && callerClassId && callerClassId !== class_id) {
    throw new HttpsError("permission-denied", `Teacher is strictly restricted to exporting their own assigned class_id (${callerClassId}).`);
  }

  const db = admin.firestore();

  // Helper to convert objects array to CSV string
  const toCsv = (rows: Record<string, any>[]): string => {
    if (!rows || rows.length === 0) return "empty\n";
    const headers = Object.keys(rows[0]);
    const escapeCsv = (val: any) => `"${String(val ?? '').replace(/"/g, '""')}"`;
    const headerLine = headers.map(escapeCsv).join(',');
    const bodyLines = rows.map(row => headers.map(h => escapeCsv(row[h])).join(','));
    return [headerLine, ...bodyLines].join('\n');
  };

  try {
    // Requirement 2: Four distinct Firestore collection queries
    // 1. Telemetry logs
    const telemetrySnap = await db.collection("telemetry_logs")
      .where("session_id", ">=", `session_${session_number}`)
      .limit(500)
      .get()
      .catch(async () => await db.collection("telemetry_logs").limit(500).get());
    const telemetryRows = telemetrySnap.docs.map(d => ({ log_id: d.id, ...d.data() }));

    // 2. Sessions
    const sessionsSnap = await db.collection("sessions")
      .where("class_id", "==", class_id)
      .where("session_number", "==", session_number)
      .get()
      .catch(async () => await db.collection("sessions").where("class_id", "==", class_id).get());
    const sessionRows = sessionsSnap.docs.map(d => ({ session_id: d.id, ...d.data() }));

    // 3. SRL Reflections
    const reflectionsSnap = await db.collection("srl_reflections")
      .where("session_number", "==", session_number)
      .limit(500)
      .get()
      .catch(async () => await db.collection("srl_reflections").limit(500).get());
    const reflectionRows = reflectionsSnap.docs.map(d => ({ reflection_id: d.id, ...d.data() }));

    // 4. Reset Audit Log
    const resetLogsSnap = await db.collection("reset_audit_log")
      .where("class_id", "==", class_id)
      .limit(500)
      .get()
      .catch(async () => await db.collection("reset_audit_log").limit(500).get());
    const resetRows = resetLogsSnap.docs.map(d => ({ log_id: d.id, ...d.data() }));

    const csv1 = toCsv(telemetryRows);
    const csv2 = toCsv(sessionRows);
    const csv3 = toCsv(reflectionRows);
    const csv4 = toCsv(resetRows);

    // Requirement 3: PII Detection check across all CSV outputs
    const allContent = [csv1, csv2, csv3, csv4].join("\n");
    const piiRegex = /(?:\b05\d-?\d{7}\b|[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}|\b\d{9}\b)/g;
    const sanitizedCheckText = allContent.replace(new RegExp(userEmail, 'g'), '');
    if (piiRegex.test(sanitizedCheckText)) {
      logger.warn("Research dataset export rejected: PII pattern detected.");
      throw new HttpsError("failed-precondition", "ייצוא נתוני המחקר נדחה: זוהה מידע מזהה (PII).");
    }

    const exportDate = new Date().toISOString().split('T')[0];
    const timestamp = Date.now();

    // Requirement 4: Drive folder-structure hierarchy session_{sessionNum} -> {exportDate},
    // under the research-data folder.
    const targetFolderId = await resolveDriveFolder([DRIVE_FOLDERS.researchData, `session_${session_number}`, exportDate]);

    // Upload all 4 distinct CSV files into the date subfolder (unique timestamps guarantee no overwrite)
    const upload1 = await uploadBufferToDrive(Buffer.from(csv1, "utf-8"), `telemetry_events_s${session_number}_${timestamp}.csv`, "text/csv", targetFolderId);
    const upload2 = await uploadBufferToDrive(Buffer.from(csv2, "utf-8"), `sessions_s${session_number}_${timestamp}.csv`, "text/csv", targetFolderId);
    const upload3 = await uploadBufferToDrive(Buffer.from(csv3, "utf-8"), `reflections_s${session_number}_${timestamp}.csv`, "text/csv", targetFolderId);
    const upload4 = await uploadBufferToDrive(Buffer.from(csv4, "utf-8"), `reset_logs_s${session_number}_${timestamp}.csv`, "text/csv", targetFolderId);

    // Requirement 5: Log export event to reset_audit_log with reset_level: 'export'
    const exportLogId = `export_${Date.now()}`;
    await db.collection("reset_audit_log").doc(exportLogId).set({
      reset_id: exportLogId,
      timestamp: Date.now(),
      performed_by: request.auth.uid,
      user_email: userEmail,
      reset_level: 'export',
      reason: 'RESEARCH_DATASET_EXPORT',
      affected_student_id: 'ALL',
      class_id,
      session_number,
      export_date: exportDate,
      drive_folder_id: targetFolderId,
      files: [upload1.fileId, upload2.fileId, upload3.fileId, upload4.fileId],
      status: 'SUCCESS',
      created_at: admin.firestore.FieldValue.serverTimestamp(),
    });

    logger.info(`Research dataset exported successfully for class ${class_id} on ${exportDate}`);

    return {
      status: "SUCCESS",
      exportDate,
      targetFolderId,
      files: {
        telemetry: upload1.webViewLink,
        sessions: upload2.webViewLink,
        reflections: upload3.webViewLink,
        resetLogs: upload4.webViewLink,
      },
    };
  } catch (err: any) {
    logger.error("Failed to export research dataset:", err);
    throw new HttpsError("internal", err?.message || "ייצוא נתוני המחקר נכשל.");
  }
});

