import { test, expect } from '@playwright/test';

test.describe('Class Management Rendering', () => {
  test('Class management grid renders properly without crashing', async ({ page }) => {
    // Login Teacher
    await page.goto('/');
    await page.getByText('מורה').click();
    await page.getByPlaceholder('תעודת זהות').fill('039604483');
    await page.getByPlaceholder('תאריך לידה (DDMMYY)').fill('290984');
    await page.getByRole('button', { name: 'התחבר למערכת' }).click();

    // Go to class management
    await page.getByText('ניהול כיתה').first().click();

    // Verify it doesn't crash (white screen). If it doesn't crash, the table headers should exist.
    await expect(page.getByText('שם תלמיד')).toBeVisible();
    await expect(page.getByText('מפגש 2')).toBeVisible();

    // Verify at least one student is rendered (e.g., student_user1 or user1)
    // We can count the number of rows in the tbody
    const rows = page.locator('tbody tr');
    const count = await rows.count();
    
    // There should be at least 30 students generated by useStore
    expect(count).toBeGreaterThanOrEqual(30);
  });
});
