$f = "react-ts-version/src/presentation/pages/TeacherDashboard.tsx"
$c = Get-Content $f -Raw

# Target: the two dead UdlButtons (mic + image) — replace with wired image button + file input
$oldBlock = "                   <div className=`"p-4 bg-white/80  backdrop-blur-xl border-t border-ws-surface2 `">`r`n                     <div className=`"flex gap-3 items-center`">`r`n                       <UdlButton`r`n                         semanticColor=`"neutral`"`r`n                         className=`"hidden md:flex rounded-full w-12 h-12 p-0 items-center justify-center bg-ws-bg/80  hover:bg-slate-200  text-ws-soft  transition-all shadow-sm`"`r`n                       >`r`n                         <svg`r`n                           xmlns=`"http://www.w3.org/2000/svg`"`r`n                           width=`"20`"`r`n                           height=`"20`"`r`n                           viewBox=`"0 0 24 24`"`r`n                           fill=`"none`"`r`n                           stroke=`"currentColor`"`r`n                           strokeWidth=`"2`"`r`n                           strokeLinecap=`"round`"`r`n                           strokeLinejoin=`"round`"`r`n                           className=`"lucide lucide-mic`"`r`n                         >`r`n                           <path d=`"M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z`" />`r`n                           <path d=`"M19 10v2a7 7 0 0 1-14 0v-2`" />`r`n                           <line x1=`"12`" x2=`"12`" y1=`"19`" y2=`"22`" />`r`n                         </svg>`r`n                       </UdlButton>`r`n                       <UdlButton`r`n                         semanticColor=`"neutral`"`r`n                         className=`"hidden md:flex rounded-full w-12 h-12 p-0 items-center justify-center bg-ws-bg/80  hover:bg-slate-200  text-ws-soft  transition-all shadow-sm`"`r`n                       >`r`n                         <svg`r`n                           xmlns=`"http://www.w3.org/2000/svg`"`r`n                           width=`"20`"`r`n                           height=`"20`"`r`n                           viewBox=`"0 0 24 24`"`r`n                           fill=`"none`"`r`n                           stroke=`"currentColor`"`r`n                           strokeWidth=`"2`"`r`n                           strokeLinecap=`"round`"`r`n                           strokeLinejoin=`"round`"`r`n                           className=`"lucide lucide-image`"`r`n                         >`r`n                           <rect`r`n                             width=`"18`"`r`n                             height=`"18`"`r`n                             x=`"3`"`r`n                             y=`"3`"`r`n                             rx=`"2`"`r`n                             ry=`"2`"`r`n                           />`r`n                           <circle cx=`"9`" cy=`"9`" r=`"2`" />`r`n                           <path d=`"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21`" />`r`n                         </svg>`r`n                       </UdlButton>"

$newBlock = "                  <div className=`"p-4 bg-white/80 backdrop-blur-xl border-t border-ws-surface2`">`r`n                    <input`r`n                      ref={teacherFileInputRef}`r`n                      type=`"file`"`r`n                      accept=`"image/*`"`r`n                      className=`"hidden`"`r`n                      onChange={handleTeacherImageSelect}`r`n                    />`r`n                    <div className=`"flex gap-3 items-center`">`r`n                      <button`r`n                        type=`"button`"`r`n                        onClick={() => teacherFileInputRef.current?.click()}`r`n                        disabled={sendingImage || !selectedStudentId}`r`n                        title=`"שלח תמונה`"`r`n                        className=`"hidden md:flex rounded-full w-12 h-12 p-0 items-center justify-center bg-ws-bg/80 hover:bg-slate-200 text-ws-soft transition-all shadow-sm disabled:opacity-40`"`r`n                      >`r`n                        {sendingImage ? (`r`n                          <span className=`"w-5 h-5 border-2 border-cyan-500 border-t-transparent rounded-full animate-spin`" />`r`n                        ) : (`r`n                          <svg xmlns=`"http://www.w3.org/2000/svg`" width=`"20`" height=`"20`" viewBox=`"0 0 24 24`" fill=`"none`" stroke=`"currentColor`" strokeWidth=`"2`" strokeLinecap=`"round`" strokeLinejoin=`"round`">`r`n                            <rect width=`"18`" height=`"18`" x=`"3`" y=`"3`" rx=`"2`" ry=`"2`" />`r`n                            <circle cx=`"9`" cy=`"9`" r=`"2`" />`r`n                            <path d=`"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21`" />`r`n                          </svg>`r`n                        )}`r`n                      </button>"

if ($c.Contains($oldBlock)) {
    $newContent = $c.Replace($oldBlock, $newBlock)
    Set-Content $f $newContent -NoNewline -Encoding UTF8
    Write-Host "SUCCESS: replaced image button block"
} else {
    Write-Host "BLOCK NOT FOUND - searching for partial match..."
    if ($c.Contains("lucide lucide-mic")) { Write-Host "Found mic" }
    if ($c.Contains("lucide lucide-image")) { Write-Host "Found image" }
    if ($c.Contains("p-4 bg-white/80  backdrop-blur-xl border-t border-ws-surface2")) { Write-Host "Found div wrapper" }
}
