import { useEffect, useRef } from "react";
import rrwebPlayer from "rrweb-player";
import "rrweb-player/dist/style.css";

interface ReplayViewerProps {
  events: any[];
  seekToTime?: number;
}

export function ReplayViewer({ events, seekToTime }: ReplayViewerProps) {
  const playerRef = useRef<HTMLDivElement>(null);
  const instanceRef = useRef<any>(null);

  useEffect(() => {
    if (!events || events.length <= 1) {
      if (playerRef.current) {
        playerRef.current.innerHTML = "";
      }
      if (instanceRef.current && typeof instanceRef.current.$destroy === 'function') {
        try { instanceRef.current.$destroy(); } catch(e){}
      }
      instanceRef.current = null;
      return;
    }

    if (playerRef.current) {
      // Cleanup previous instance before recreating
      if (instanceRef.current && typeof instanceRef.current.$destroy === 'function') {
        try { instanceRef.current.$destroy(); } catch(e){}
      }
      playerRef.current.innerHTML = "";
      
      try {
        const metaEvent = events.find((e: any) => e.type === 4);
        const originalWidth = metaEvent?.data?.width || 1280;
        const originalHeight = metaEvent?.data?.height || 720;
        
        // Target width for the dashboard player container
        const targetWidth = 900;
        const scale = targetWidth / originalWidth;

        const Player = (rrwebPlayer as any).default || rrwebPlayer;
        instanceRef.current = new Player({
          target: playerRef.current,
          props: {
            events,
            width: originalWidth,
            height: originalHeight,
            autoPlay: false,
            showController: true,
            mouseTail: false,
          },
        });

        // Apply scale to the wrapper generated by rrweb
        setTimeout(() => {
            const rrwebWrapper = playerRef.current?.querySelector('.replayer-wrapper') as HTMLElement;
            if (rrwebWrapper && playerRef.current) {
              rrwebWrapper.style.transform = `scale(${scale})`;
              rrwebWrapper.style.transformOrigin = 'top center';
              // Adjust the container height so it doesn't leave huge empty space
              playerRef.current.style.height = `${originalHeight * scale}px`;
              playerRef.current.style.width = `${originalWidth * scale}px`;
              playerRef.current.style.overflow = 'hidden';
              playerRef.current.style.display = 'flex';
              playerRef.current.style.justifyContent = 'center';
            }
        }, 10);
      } catch (err) {
        console.error("Failed to initialize rrweb-player:", err);
      }
    }

    return () => {
      if (instanceRef.current && typeof instanceRef.current.$destroy === 'function') {
        try { instanceRef.current.$destroy(); } catch(e){}
      }
      if (playerRef.current) {
        playerRef.current.innerHTML = "";
      }
      instanceRef.current = null;
    };
  }, [events]);

  useEffect(() => {
    if (seekToTime && instanceRef.current && events && events.length > 0) {
      const firstEventTime = events[0].timestamp;
      // Seek slightly before the event (e.g. 2 seconds before) to give context
      const offset = Math.max(0, seekToTime - firstEventTime - 2000);
      try {
        if (typeof instanceRef.current.goto === 'function') {
          instanceRef.current.goto(offset, true);
        } else if (instanceRef.current.play) {
          // Playback might need to be triggered if goto isn't available
          instanceRef.current.play();
        }
      } catch (e) {
        console.warn("Failed to seek rrweb player", e);
      }
    }
  }, [seekToTime, events]);

  if (!events || events.length < 2) {
    return (
      <div className="flex items-center justify-center h-[500px] glass-card rounded-3xl overflow-hidden w-full">
        <div className="text-center space-y-4">
          <div className="w-16 h-16 bg-slate-100 dark:bg-slate-800 rounded-full flex items-center justify-center mx-auto mb-4 animate-pulse">
            <svg className="w-8 h-8 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" />
            </svg>
          </div>
          <p className="text-ws-soft font-medium text-lg">אין מספיק נתוני הקלטה כדי להציג את השחזור</p>
          <p className="text-ws-soft/70 text-sm">(נדרשים לפחות 2 אירועים מוקלטים)</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex justify-center glass-card p-6 rounded-3xl overflow-hidden w-full" dir="ltr">
      <div ref={playerRef} className="rrweb-player-container rounded-2xl overflow-hidden shadow-2xl bg-white w-full flex justify-center"></div>
    </div>
  );
}
