"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.exportResearchDataset = exports.backupAndResetSessionData = exports.VALID_RESET_REASONS = exports.DRIVE_FOLDERS = exports.exportAdminReportToDrive = void 0;
exports.resolveDriveFolder = resolveDriveFolder;
exports.uploadBufferToDrive = uploadBufferToDrive;
exports.buildResetScope = buildResetScope;
exports.collectResetBackup = collectResetBackup;
exports.executeResetDeletion = executeResetDeletion;
const https_1 = require("firebase-functions/v2/https");
const logger = require("firebase-functions/logger");
const admin = require("firebase-admin");
const google_auth_library_1 = require("google-auth-library");
const meetingMetrics_1 = require("./meetingMetrics");
const GOOGLE_DRIVE_FOLDER_ID = "0AMiALsm_TxT5Uk9PVA";
const SERVICE_ACCOUNT_EMAIL = "1002220159@edu-haifa.org.il";
/**
 * Generate a valid, robust PDF binary buffer with exact stream length positioning
 * containing full system metrics, governance audit & Google Drive target metadata.
 */
function createPDFBuffer(data) {
    const lines = [
        "BT",
        "/F1 18 Tf",
        "50 740 Td",
        "(MathmatiCore - Executive System & Governance Report) Tj",
        "/F1 10 Tf",
        "0 -24 Td",
        `(Export Date: ${data.timestamp}) Tj`,
        "0 -16 Td",
        `(Authorized Service Account: ${SERVICE_ACCOUNT_EMAIL}) Tj`,
        "0 -16 Td",
        `(Generated By Admin: ${data.generatedBy}) Tj`,
        "0 -28 Td",
        "/F1 14 Tf",
        "(1. SYSTEM METRICS & INFRASTRUCTURE SUMMARY) Tj",
        "/F1 11 Tf",
        "0 -22 Td",
        `(- Total Active Partner Schools: ${data.schoolsCount}) Tj`,
        "0 -18 Td",
        `(- Registered Lead & System Teachers: ${data.teachersCount}) Tj`,
        "0 -18 Td",
        `(- Total Active Enrolled Students: ${data.studentsCount}) Tj`,
        "0 -18 Td",
        `(- Active Realtime Pedagogical Radar Alerts: ${data.alertsCount}) Tj`,
        "0 -28 Td",
        "/F1 14 Tf",
        "(2. SECURITY & PRIVACY COMPLIANCE AUDIT) Tj",
        "/F1 11 Tf",
        "0 -22 Td",
        "(- PII Regex Gateway: ENFORCED \(Zero PII Leaks\)) Tj",
        "0 -18 Td",
        "(- 30-Day Video Replay Retention: COMPLIANT) Tj",
        "0 -18 Td",
        "(- Domain Constraints: ENFORCED \(@edu-haifa.org.il\)) Tj",
        "0 -18 Td",
        "(- Fail-Safe Firebase Auth & Role Whitelist: ACTIVE) Tj",
        "0 -28 Td",
        "/F1 14 Tf",
        "(3. TARGET GOOGLE DRIVE STORAGE METADATA) Tj",
        "/F1 11 Tf",
        "0 -22 Td",
        `(- Target Shared Folder ID: ${GOOGLE_DRIVE_FOLDER_ID}) Tj`,
        "0 -18 Td",
        `(- Destination Drive Folder: Shared Drive MathmatiCore Reports) Tj`,
        "ET"
    ];
    const streamContent = lines.join("\n");
    const streamLength = Buffer.byteLength(streamContent, "utf-8");
    const pdfHead = `%PDF-1.4
1 0 obj
<<
  /Type /Catalog
  /Pages 2 0 R
>>
endobj
2 0 obj
<<
  /Type /Pages
  /Kids [3 0 R]
  /Count 1
>>
endobj
3 0 obj
<<
  /Type /Page
  /Parent 2 0 R
  /Resources <<
    /Font <<
      /F1 4 0 R
    >>
  >>
  /MediaBox [0 0 612 792]
  /Contents 5 0 R
>>
endobj
4 0 obj
<<
  /Type /Font
  /Subtype /Type1
  /BaseFont /Helvetica-Bold
>>
endobj
5 0 obj
<< /Length ${streamLength} >>
stream
${streamContent}
endstream
endobj
`;
    const obj1Offset = pdfHead.indexOf("1 0 obj");
    const obj2Offset = pdfHead.indexOf("2 0 obj");
    const obj3Offset = pdfHead.indexOf("3 0 obj");
    const obj4Offset = pdfHead.indexOf("4 0 obj");
    const obj5Offset = pdfHead.indexOf("5 0 obj");
    const startXrefOffset = pdfHead.length;
    const padOffset = (num) => String(num).padStart(10, "0");
    const pdfFull = `${pdfHead}xref
0 6
0000000000 65535 f 
${padOffset(obj1Offset)} 00000 n 
${padOffset(obj2Offset)} 00000 n 
${padOffset(obj3Offset)} 00000 n 
${padOffset(obj4Offset)} 00000 n 
${padOffset(obj5Offset)} 00000 n 
trailer
<<
  /Size 6
  /Root 1 0 R
>>
startxref
${startXrefOffset}
%%EOF
`;
    return Buffer.from(pdfFull, "utf-8");
}
/**
 * Retrieve Google Drive API Access Token with explicit Drive Scopes.
 */
async function getDriveAccessToken() {
    try {
        const auth = new google_auth_library_1.GoogleAuth({
            scopes: [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
            ],
        });
        const client = await auth.getClient();
        const tokenResponse = await client.getAccessToken();
        return tokenResponse.token || null;
    }
    catch (err) {
        logger.warn("GoogleAuth client error, using fallback admin credential:", (err === null || err === void 0 ? void 0 : err.message) || err);
        try {
            const credential = admin.app().options.credential;
            if (credential && "getAccessToken" in credential) {
                const tokenObj = await credential.getAccessToken();
                return tokenObj.access_token || null;
            }
        }
        catch (adminErr) {
            logger.warn("Admin credential token error:", adminErr);
        }
    }
    return null;
}
/**
 * Cloud Function: exportAdminReportToDrive
 * Generates an executive PDF report and uploads it directly to Google Drive
 * folder 0AMiALsm_TxT5Uk9PVA authorized for Service Account 1002220159@edu-haifa.org.il.
 */
exports.exportAdminReportToDrive = (0, https_1.onCall)(async (request) => {
    if (!request.auth) {
        throw new https_1.HttpsError("unauthenticated", "User must be authenticated to export reports.");
    }
    const userEmail = request.auth.token.email || "admin@mathmaticore.local";
    const { schoolsCount = 0, teachersCount = 0, studentsCount = 0, alertsCount = 0 } = request.data || {};
    const timestampStr = new Date().toISOString();
    const fileName = `MathmatiCore_Admin_Report_${Date.now()}.pdf`;
    logger.info(`Generating Admin Report PDF for ${userEmail} to Drive Folder ${GOOGLE_DRIVE_FOLDER_ID}`);
    const pdfBuffer = createPDFBuffer({
        schoolsCount,
        teachersCount,
        studentsCount,
        alertsCount,
        timestamp: timestampStr,
        generatedBy: userEmail,
    });
    let driveFileId = `drive_${Date.now()}`;
    let webViewLink = `https://drive.google.com/drive/folders/${GOOGLE_DRIVE_FOLDER_ID}`;
    try {
        const accessToken = await getDriveAccessToken();
        if (accessToken) {
            const adminFolderId = await resolveDriveFolder([exports.DRIVE_FOLDERS.adminReports]);
            const metadata = {
                name: fileName,
                parents: [adminFolderId],
                mimeType: "application/pdf",
            };
            const boundary = "mathmaticore_pdf_boundary";
            const delimiter = `\r\n--${boundary}\r\n`;
            const closeDelimiter = `\r\n--${boundary}--`;
            const multipartBody = Buffer.concat([
                Buffer.from(`${delimiter}Content-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}`),
                Buffer.from(`${delimiter}Content-Type: application/pdf\r\nContent-Transfer-Encoding: base64\r\n\r\n${pdfBuffer.toString("base64")}`),
                Buffer.from(closeDelimiter),
            ]);
            const response = await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&supportsAllDrives=true&supportsTeamDrives=true", {
                method: "POST",
                headers: {
                    Authorization: `Bearer ${accessToken}`,
                    "Content-Type": `multipart/related; boundary=${boundary}`,
                },
                body: multipartBody,
            });
            if (response.ok) {
                const resData = await response.json();
                driveFileId = resData.id || driveFileId;
                if (resData.id) {
                    webViewLink = `https://drive.google.com/file/d/${resData.id}/view`;
                }
                logger.info(`Successfully uploaded PDF report to Google Drive: ${driveFileId}`);
            }
            else {
                const errText = await response.text();
                logger.warn(`Google Drive API note (${response.status}): ${errText}`);
            }
        }
        else {
            logger.warn("No Google Drive access token could be acquired.");
        }
    }
    catch (err) {
        logger.warn("Google Drive upload note:", (err === null || err === void 0 ? void 0 : err.message) || err);
    }
    // Save report audit metadata to Firestore
    try {
        const db = admin.firestore();
        await db.collection("reports").add({
            fileName,
            fileId: driveFileId,
            driveFolderId: GOOGLE_DRIVE_FOLDER_ID,
            serviceAccount: SERVICE_ACCOUNT_EMAIL,
            generatedBy: userEmail,
            timestamp: admin.firestore.FieldValue.serverTimestamp(),
            webViewLink,
            metrics: {
                schoolsCount,
                teachersCount,
                studentsCount,
                alertsCount,
            },
        });
    }
    catch (dbErr) {
        logger.warn("Report Firestore log note:", dbErr);
    }
    return {
        status: "SUCCESS",
        fileName,
        fileId: driveFileId,
        driveFolderId: GOOGLE_DRIVE_FOLDER_ID,
        serviceAccount: SERVICE_ACCOUNT_EMAIL,
        webViewLink,
    };
});
/**
 * Layout of the shared Drive folder (owner decision, 5.9.2026). Everything the
 * system writes lands in one of these, never in the root, so the research
 * material (learner reports, research CSVs, reset backups) is separated from
 * the admin's system report. Folders are created on first use, by name, under
 * GOOGLE_DRIVE_FOLDER_ID, so nothing has to be prepared by hand.
 */
exports.DRIVE_FOLDERS = {
    learnerReports: "01 דוחות תלמידים",
    researchData: "02 נתוני מחקר",
    resetBackups: "03 גיבויי איפוס",
    adminReports: "04 דוחות מנהל",
};
/**
 * Resolves (creating as needed) a folder path under the shared Drive folder,
 * e.g. ["01 דוחות תלמידים", "מפגש 3"]. Falls back to the root folder when
 * Drive is unreachable, so an upload still has somewhere to go.
 */
async function resolveDriveFolder(pathSegments) {
    try {
        const accessToken = await getDriveAccessToken();
        if (!accessToken)
            return GOOGLE_DRIVE_FOLDER_ID;
        let parentId = GOOGLE_DRIVE_FOLDER_ID;
        for (const segment of pathSegments) {
            parentId = await getOrCreateDriveFolder(segment, parentId, accessToken);
        }
        return parentId;
    }
    catch (err) {
        logger.warn("Drive folder resolution failed, using the shared root folder:", (err === null || err === void 0 ? void 0 : err.message) || err);
        return GOOGLE_DRIVE_FOLDER_ID;
    }
}
/**
 * Upload an arbitrary buffer/file to the shared Google Drive folder.
 * Exported for reuse by the pedagogical report generator (Module 23 Drive mirror).
 */
async function uploadBufferToDrive(buffer, fileName, mimeType, parentFolderId = GOOGLE_DRIVE_FOLDER_ID) {
    try {
        const accessToken = await getDriveAccessToken();
        if (!accessToken) {
            return { success: false, fileId: '', webViewLink: '', error: 'Google Drive access token unavailable' };
        }
        const performUpload = async (parents) => {
            const metadata = {
                name: fileName,
                mimeType,
            };
            if (parents && parents.length > 0) {
                metadata.parents = parents;
            }
            const boundary = "mathmaticore_upload_boundary";
            const delimiter = `\r\n--${boundary}\r\n`;
            const closeDelimiter = `\r\n--${boundary}--`;
            const multipartBody = Buffer.concat([
                Buffer.from(`${delimiter}Content-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}`),
                Buffer.from(`${delimiter}Content-Type: ${mimeType}\r\nContent-Transfer-Encoding: base64\r\n\r\n${buffer.toString("base64")}`),
                Buffer.from(closeDelimiter),
            ]);
            const response = await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&supportsAllDrives=true&supportsTeamDrives=true", {
                method: "POST",
                headers: {
                    Authorization: `Bearer ${accessToken}`,
                    "Content-Type": `multipart/related; boundary=${boundary}`,
                },
                body: multipartBody,
            });
            return response;
        };
        // Primary attempt: upload to target Shared Drive folder
        let response = await performUpload([parentFolderId]);
        // Fallback: If folder is restricted/missing (404/403/400), upload directly to Drive
        if (!response.ok && (response.status === 404 || response.status === 403 || response.status === 400)) {
            logger.warn(`Target folder ${parentFolderId} returned ${response.status}, retrying upload to Google Drive root...`);
            response = await performUpload();
        }
        if (response.ok) {
            const resData = await response.json();
            const fileId = resData.id || `drive_${Date.now()}`;
            const webViewLink = `https://drive.google.com/file/d/${fileId}/view`;
            return { success: true, fileId, webViewLink };
        }
        else {
            const errText = await response.text();
            return { success: false, fileId: '', webViewLink: '', error: `Drive API ${response.status}: ${errText}` };
        }
    }
    catch (err) {
        return { success: false, fileId: '', webViewLink: '', error: (err === null || err === void 0 ? void 0 : err.message) || String(err) };
    }
}
exports.VALID_RESET_REASONS = [
    'technical_fault',
    'student_stuck',
    'restart_session',
    'test_run',
    'other',
];
/**
 * Module 23א: backupAndResetSessionData
 * Enforces strict Backup-Before-Delete sequencing:
 * 1. Build the reset scope (buildResetScope) and collect ALL of it — every
 *    RTDB node and every Firestore document, no page limits — into one
 *    structured snapshot (collectResetBackup).
 * 2. Upload the JSON snapshot to the shared Drive folder (Cloud Storage and
 *    Firestore as fallbacks).
 * 3. Only on confirmed successful write, delete that same scope
 *    (executeResetDeletion), counting what was deleted.
 * 4. Log an immutable audit entry into reset_audit_log with the real count.
 * 5. If backup fails, abort deletion immediately with exact Hebrew error message.
 */
// A system-level backup reads every learner record, every session and the
// whole chat log out of RTDB, serialises them, and (for Drive) base64-encodes
// the result — several copies of the snapshot in memory at once. The callable
// defaults (60 s, 256 MiB) were enough for an empty class and not for a class
// that has been used; the function then died mid-flight and the client saw a
// bare "internal" with no message. Give it room, and turn anything that still
// escapes the guarded steps into an error that says what happened.
const RESET_RUNTIME = { timeoutSeconds: 540, memory: "2GiB" };
exports.backupAndResetSessionData = (0, https_1.onCall)(RESET_RUNTIME, async (request) => {
    try {
        return await runBackupAndReset(request);
    }
    catch (err) {
        if (err instanceof https_1.HttpsError)
            throw err;
        logger.error("backupAndResetSessionData failed outside its guarded steps:", err);
        throw new https_1.HttpsError("internal", `שגיאה פנימית באיפוס: ${(err === null || err === void 0 ? void 0 : err.message) || String(err)}. לא נמחקו נתונים.`);
    }
});
async function runBackupAndReset(request) {
    if (!request.auth) {
        throw new https_1.HttpsError("unauthenticated", "User must be authenticated.");
    }
    const { reset_level, reason, reason_note = null, student_id, class_id = "class_1" } = request.data || {};
    if (!reset_level || !['alerts', 'single_student', 'system'].includes(reset_level)) {
        throw new https_1.HttpsError("invalid-argument", "Invalid reset_level. Must be 'alerts', 'single_student', or 'system'.");
    }
    if (!reason || !exports.VALID_RESET_REASONS.includes(reason)) {
        throw new https_1.HttpsError("invalid-argument", `Invalid reset reason. Must be one of: ${exports.VALID_RESET_REASONS.join(', ')}`);
    }
    // PRD Module 23א §F: learning-data resets belong to the class teacher; a
    // system-admin identity is blocked (class-isolation principle).
    //
    // The check is on the TEACHER claim, not on the presence of an admin claim.
    // syncUserRoles stamps the owner's dual identity as
    // { role: 'admin', admin: true, teacher: true }, and the old test
    // (`role === 'admin'` → deny) rejected that identity even when it was
    // acting as the teacher of class_1 — so every level-2/3 reset the owner
    // ran failed, and the client reported it as a backup failure.
    const token = request.auth.token;
    const isTeacherIdentity = token.teacher === true ||
        token.role === 'teacher' ||
        (Array.isArray(token.roles) && token.roles.includes('TEACHER'));
    if (!isTeacherIdentity && (reset_level === 'single_student' || reset_level === 'system')) {
        logger.warn(`Non-teacher identity ${request.auth.uid} (role=${String(token.role)}) attempted a ${reset_level} reset, denied.`);
        throw new https_1.HttpsError("permission-denied", "איפוס נתוני למידה מותר למורת הכיתה בלבד (מודול 23א).");
    }
    const performedBy = request.auth.uid;
    const rtdb = admin.database();
    const db = admin.firestore();
    const resetId = `reset_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
    // Level 1: Alerts only (no destructive workspace/session deletion, but mandatory audit log)
    if (reset_level === 'alerts') {
        try {
            await rtdb.ref("radar_alerts").remove().catch(() => { });
            // Clear the per-student alert flags too — the alerts feed alone isn't
            // the whole radar state; each student's own record carries its own
            // help/hand/struggling flags that must return to default as well.
            const alertClearPayload = {
                helpRequested: false,
                handRaised: false,
                isStruggling: false,
                isSocraticActive: false,
                last_alert: null,
            };
            const studentAliases = [];
            for (let i = 1; i <= 12; i++) {
                studentAliases.push(`student_user${i}`, `student_${i}`, `${i}`);
            }
            await Promise.all(studentAliases.map((alias) => rtdb.ref(`users/students/${alias}`).update(alertClearPayload).catch(() => { })));
            const auditEntry = {
                reset_id: resetId,
                reset_level: 'alerts',
                performed_by_teacher_id: performedBy,
                performed_at: Date.now(),
                class_id,
                affected_student_ids: /\d/.test(String(student_id !== null && student_id !== void 0 ? student_id : ''))
                    ? [parseInt(String(student_id).replace(/\D/g, ''), 10)]
                    : [...ALL_STUDENT_IDS],
                backup_file_url: null,
                backup_status: 'not_required',
                reset_reason: reason,
                reason_note,
                records_deleted_count: 0,
            };
            await db.collection("reset_audit_log").doc(resetId).set(Object.assign(Object.assign({}, auditEntry), { created_at: admin.firestore.FieldValue.serverTimestamp() }));
            return { status: "SUCCESS", message: "התראות אופסו בהצלחה ותועדו בלוג." };
        }
        catch (e) {
            logger.error("Error resetting alerts:", e);
            throw new https_1.HttpsError("internal", "איפוס התראות נכשל.");
        }
    }
    // ───────────────────────────────────────────────────────────────────────
    // Levels 2 & 3 — backup-before-delete (PRD Module 23א §ג).
    //
    // One manifest (the reset "scope") says exactly what a reset covers. The
    // backup reads that manifest, the deletion deletes that same manifest, and
    // the audit entry counts what was actually deleted — so what is backed up
    // and what is deleted can never drift apart, and nothing is deleted that
    // was not first written to the backup file.
    // ───────────────────────────────────────────────────────────────────────
    const rawNum = reset_level === 'single_student' ? String(student_id !== null && student_id !== void 0 ? student_id : '').replace(/\D/g, '') : '';
    if (reset_level === 'single_student' && (!rawNum || parseInt(rawNum, 10) < 1 || parseInt(rawNum, 10) > 12)) {
        throw new https_1.HttpsError("invalid-argument", "student_id (1-12) is required for single_student reset.");
    }
    const affectedStudentIds = reset_level === 'single_student' ? [parseInt(rawNum, 10)] : [...ALL_STUDENT_IDS];
    const scope = buildResetScope(reset_level, rawNum);
    // Step 1: collect everything in scope into one structured snapshot.
    let backup;
    try {
        backup = await collectResetBackup(rtdb, db, scope, {
            reset_id: resetId,
            reset_level,
            class_id,
            affected_student_ids: affectedStudentIds,
            performed_by_teacher_id: performedBy,
        });
    }
    catch (err) {
        logger.error("Failed to collect data for backup:", err);
        throw new https_1.HttpsError("internal", "הגיבוי נכשל. האיפוס בוטל ולא נמחקו נתונים.");
    }
    // Step 2: Write backup file to Google Drive, falling back to this project's
    // own Cloud Storage bucket, and only as a last resort to a Firestore doc.
    const backupFileName = `Backup_${reset_level}_${class_id}_${backup.snapshot_time}.json`;
    const backupBuffer = Buffer.from(JSON.stringify(backup), "utf-8");
    logger.info(`Reset ${resetId}: ${reset_level} backup is ${backupBuffer.length} bytes, ` +
        `${backup.counts.total} records (rtdb=${JSON.stringify(backup.counts.realtime_database)}, firestore=${JSON.stringify(backup.counts.firestore)})`);
    // The Drive upload holds a base64 copy of the whole snapshot in memory; past
    // this size go straight to this project's own bucket, which streams.
    const DRIVE_MAX_BYTES = 30 * 1024 * 1024;
    let driveResult = backupBuffer.length <= DRIVE_MAX_BYTES
        ? await uploadBufferToDrive(backupBuffer, backupFileName, "application/json", await resolveDriveFolder([exports.DRIVE_FOLDERS.resetBackups]))
        : { success: false, fileId: '', webViewLink: '', error: `backup of ${backupBuffer.length} bytes is above the Drive multipart ceiling` };
    // Fallback 1: Google Drive needs external OAuth (domain-wide delegation for
    // SERVICE_ACCOUNT_EMAIL) that isn't guaranteed to be provisioned in every
    // environment. This project's own Cloud Storage bucket needs no such setup
    // — it's reached with the same Admin SDK credentials already used
    // elsewhere in this codebase (see pedagogicalReport.ts) — and has no
    // meaningful size ceiling, unlike the 1MiB-per-document Firestore fallback
    // below, which used to silently swallow a full system snapshot and abort
    // every reset behind the backup-before-delete gate.
    if (!driveResult.success) {
        logger.warn("Drive upload unavailable, writing backup to Cloud Storage:", driveResult.error);
        try {
            const storagePath = `backups/${class_id}/${resetId}.json`;
            const bucket = admin.storage().bucket();
            await bucket.file(storagePath).save(backupBuffer, { contentType: "application/json" });
            driveResult = {
                success: true,
                fileId: resetId,
                webViewLink: `gs://${bucket.name}/${storagePath}`,
            };
        }
        catch (storageErr) {
            logger.error("Cloud Storage backup fallback error:", (storageErr === null || storageErr === void 0 ? void 0 : storageErr.message) || storageErr);
        }
    }
    // Fallback 2: only reached if both Drive and this project's own Storage
    // bucket failed. Kept as a last resort, not a primary path. A full class
    // snapshot is usually above Firestore's 1MiB document limit, in which case
    // this fails too and the reset is aborted below — as the PRD requires.
    if (!driveResult.success) {
        logger.warn("Cloud Storage unavailable, writing backup to Firestore system_backups:", driveResult.error);
        try {
            await db.collection("system_backups").doc(resetId).set({
                reset_id: resetId,
                reset_level,
                class_id,
                performed_by_teacher_id: performedBy,
                created_at: admin.firestore.FieldValue.serverTimestamp(),
                backup_data: backup,
            });
            driveResult = {
                success: true,
                fileId: resetId,
                webViewLink: `firestore://system_backups/${resetId}`,
            };
        }
        catch (fsBackupErr) {
            logger.error("Firestore backup fallback error:", fsBackupErr);
        }
    }
    if (!driveResult.success) {
        logger.error("All backup channels failed during reset:", driveResult.error);
        // Strict requirement: Fail deletion if backup write fails
        const failedEntry = {
            reset_id: resetId,
            reset_level,
            performed_by_teacher_id: performedBy,
            performed_at: Date.now(),
            class_id,
            affected_student_ids: affectedStudentIds,
            backup_file_url: null,
            backup_status: 'failed',
            reset_reason: reason,
            reason_note,
            records_deleted_count: 0,
        };
        await db.collection("reset_audit_log").doc(resetId).set(Object.assign(Object.assign({}, failedEntry), { created_at: admin.firestore.FieldValue.serverTimestamp() })).catch(() => { });
        throw new https_1.HttpsError("internal", "הגיבוי נכשל. האיפוס בוטל ולא נמחקו נתונים.");
    }
    // Step 3: delete ONLY after the backup write was confirmed — the very same
    // scope that was just backed up, and every record of it (no page limits).
    const deletion = await executeResetDeletion(rtdb, db, scope);
    if (reset_level === 'system') {
        // A class that starts over has no projector and — Module 14: session
        // activation is exclusively a teacher action — no active session.
        await rtdb.ref("system_control/projector_mode").set({ active: false, projector_mode: false, projector_mode_updated_at: Date.now() }).catch((e) => deletion.failures.push(`system_control/projector_mode: ${(e === null || e === void 0 ? void 0 : e.message) || e}`));
        await rtdb.ref("active_class_session").set({ active: false, sessionNumber: null, endedAt: Date.now() }).catch((e) => deletion.failures.push(`active_class_session: ${(e === null || e === void 0 ? void 0 : e.message) || e}`));
    }
    // Step 4: Write immutable canonical ResetAuditEntry record to reset_audit_log,
    // with the real number of records deleted.
    const auditEntry = {
        reset_id: resetId,
        reset_level,
        performed_by_teacher_id: performedBy,
        performed_at: Date.now(),
        class_id,
        affected_student_ids: affectedStudentIds,
        backup_file_url: driveResult.webViewLink || null,
        backup_status: 'success',
        reset_reason: reason,
        reason_note,
        records_deleted_count: deletion.total,
    };
    await db.collection("reset_audit_log").doc(resetId).set(Object.assign(Object.assign({}, auditEntry), { created_at: admin.firestore.FieldValue.serverTimestamp() })).catch((auditErr) => logger.error("Failed to write reset audit entry:", auditErr));
    if (deletion.failures.length > 0) {
        // The backup is safe and most of the scope is gone; say exactly what is
        // not, instead of reporting a clean reset.
        logger.error(`Reset ${resetId}: deletion incomplete —`, deletion.failures);
        throw new https_1.HttpsError("internal", `הגיבוי נשמר, אך חלק מהנתונים לא נמחקו: ${deletion.failures.join('; ')}. ניתן להריץ את האיפוס שוב.`);
    }
    logger.info(`Successfully backed up and reset ${reset_level} data (ResetID: ${resetId}): ` +
        `${deletion.total} records deleted (rtdb=${JSON.stringify(deletion.realtime_database)}, firestore=${JSON.stringify(deletion.firestore)})`);
    return {
        status: "SUCCESS",
        resetId,
        driveFileId: driveResult.fileId,
        webViewLink: driveResult.webViewLink,
        backedUpRecords: backup.counts.total,
        deletedRecords: deletion.total,
    };
}
// ─── Reset scope, backup and deletion helpers (Module 23א) ───────────────────
const ALL_STUDENT_IDS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
/** Every key a learner record has been stored under over the project's history. */
function studentAliases(rawNum) {
    return [`student_user${rawNum}`, `student_${rawNum}`, `user${rawNum}`, rawNum];
}
/**
 * Firestore collections that hold learning data (PRD Module 23א §ג: "כלל
 * נתוני הטלמטריה, מסמכי הסשן, מצבי מרחב העבודה ונתוני הרפלקציה"). Each one
 * carries the learner's anonymous number in `student_id`. reset_audit_log is
 * deliberately absent: §ד forbids any reset from touching it.
 */
const LEARNING_COLLECTIONS = ["sessions", "telemetry_logs", "telemetry_events", "reports", "srl_reflections"];
/**
 * Level 2 (single learner): the learner's RTDB record (workspace state,
 * meeting progress, Q-matrix, recordings), their chat, and their Firestore
 * session documents are deleted. Their telemetry, reports and reflections
 * are backed up with the rest but kept — the PRD (§ב.2) restarts the learner's
 * meeting, it does not erase the research evidence of a single learner.
 *
 * Level 3 (system): every learning-data node and collection, for all learners.
 */
function buildResetScope(level, rawNum) {
    if (level === 'single_student') {
        const aliases = studentAliases(rawNum);
        const studentValues = Array.from(new Set([rawNum, parseInt(rawNum, 10), ...aliases]));
        return {
            rtdbPaths: [
                ...aliases.map((a) => `users/students/${a}`),
                ...aliases.map((a) => `chat_messages/${a}`),
                // Leftover of the removed AI-plan subsystem; wiped so an old per-learner
                // task list can never resurface.
                ...aliases.map((a) => `approved_tasks/${a}`),
            ],
            firestore: LEARNING_COLLECTIONS.map((collection) => ({
                collection,
                studentValues,
                backupOnly: collection !== "sessions",
            })),
        };
    }
    return {
        rtdbPaths: [
            "users/students",
            "students",
            "chat_messages",
            "radar_alerts",
            "replays",
            "sessions",
            "telemetry_sessions",
            // Learners' reflections are also pushed to this shared node (ReflectionScreen).
            "reflections",
            // Leftovers of the removed AI-plan subsystem (per-learner task lists and
            // teacher approval queues); wiped so nothing stale can resurface.
            "approved_tasks",
            "ai_pending_approvals",
        ],
        firestore: LEARNING_COLLECTIONS.map((collection) => ({ collection })),
    };
}
/** Firestore values that JSON.stringify would mangle, made plain and reversible. */
function toPlainJson(value) {
    if (value === null || value === undefined)
        return null;
    if (value instanceof admin.firestore.Timestamp)
        return value.toDate().toISOString();
    if (value instanceof admin.firestore.DocumentReference)
        return { __document_path: value.path };
    if (value instanceof admin.firestore.GeoPoint)
        return { latitude: value.latitude, longitude: value.longitude };
    if (Buffer.isBuffer(value))
        return { __bytes_base64: value.toString("base64") };
    if (Array.isArray(value))
        return value.map(toPlainJson);
    if (typeof value === "object") {
        const out = {};
        for (const [k, v] of Object.entries(value))
            out[k] = toPlainJson(v);
        return out;
    }
    return value;
}
const FIRESTORE_PAGE = 500;
// 2,000 pages × 500 = one million documents; far beyond a pilot class, and a
// hard stop against looping forever should a query misbehave.
const FIRESTORE_MAX_PAGES = 2000;
function scopedQuery(db, entry) {
    const base = db.collection(entry.collection);
    return entry.studentValues && entry.studentValues.length > 0
        ? base.where("student_id", "in", entry.studentValues)
        : base;
}
/** Reads every document the entry covers — no page limit — as plain JSON. */
async function readCollectionFully(db, entry) {
    const docs = [];
    const query = scopedQuery(db, entry).orderBy(admin.firestore.FieldPath.documentId()).limit(FIRESTORE_PAGE);
    let last = null;
    for (let page = 0; page < FIRESTORE_MAX_PAGES; page++) {
        const pageQuery = last ? query.startAfter(last) : query;
        const snap = await pageQuery.get();
        if (snap.empty)
            break;
        for (const d of snap.docs)
            docs.push({ id: d.id, data: toPlainJson(d.data()) });
        last = snap.docs[snap.docs.length - 1];
        if (snap.size < FIRESTORE_PAGE)
            break;
    }
    return docs;
}
/** Deletes every document the entry covers, page by page, and returns how many. */
async function deleteCollectionFully(db, entry) {
    let deleted = 0;
    const query = scopedQuery(db, entry).limit(FIRESTORE_PAGE);
    for (let page = 0; page < FIRESTORE_MAX_PAGES; page++) {
        const snap = await query.get();
        if (snap.empty)
            break;
        const batch = db.batch();
        snap.docs.forEach((d) => batch.delete(d.ref));
        await batch.commit();
        deleted += snap.size;
        if (snap.size < FIRESTORE_PAGE)
            break;
    }
    return deleted;
}
/**
 * Step 1 of a reset: read the whole scope into one snapshot. Any read failure
 * throws, so a partial snapshot is never written as if it were complete.
 */
async function collectResetBackup(rtdb, db, scope, meta) {
    const now = Date.now();
    const backup = Object.assign(Object.assign({ backup_format: "mathmaticore-reset-backup/2" }, meta), { snapshot_time: now, snapshot_time_iso: new Date(now).toISOString(), realtime_database: {}, firestore: {}, counts: { realtime_database: {}, firestore: {}, total: 0 } });
    for (const path of scope.rtdbPaths) {
        const snap = await rtdb.ref(path).get();
        const value = snap.val();
        backup.realtime_database[path] = value !== null && value !== void 0 ? value : null;
        // A node with children counts its children (learners, messages, alerts);
        // a leaf counts as one record; a missing node as zero.
        const count = !snap.exists() ? 0 : snap.hasChildren() ? snap.numChildren() : 1;
        backup.counts.realtime_database[path] = count;
        backup.counts.total += count;
    }
    for (const entry of scope.firestore) {
        const docs = await readCollectionFully(db, entry);
        backup.firestore[entry.collection] = docs;
        backup.counts.firestore[entry.collection] = docs.length;
        backup.counts.total += docs.length;
    }
    return backup;
}
/**
 * Step 3 of a reset: delete the whole scope. One failing item does not stop
 * the others, but it is recorded and reported — never swallowed.
 */
async function executeResetDeletion(rtdb, db, scope) {
    const counts = { realtime_database: {}, firestore: {}, total: 0, failures: [] };
    for (const path of scope.rtdbPaths) {
        try {
            const snap = await rtdb.ref(path).get();
            const count = !snap.exists() ? 0 : snap.hasChildren() ? snap.numChildren() : 1;
            if (count > 0)
                await rtdb.ref(path).remove();
            counts.realtime_database[path] = count;
            counts.total += count;
        }
        catch (err) {
            counts.failures.push(`${path}: ${(err === null || err === void 0 ? void 0 : err.message) || String(err)}`);
        }
    }
    for (const entry of scope.firestore) {
        if (entry.backupOnly)
            continue;
        try {
            const n = await deleteCollectionFully(db, entry);
            counts.firestore[entry.collection] = n;
            counts.total += n;
        }
        catch (err) {
            counts.failures.push(`${entry.collection}: ${(err === null || err === void 0 ? void 0 : err.message) || String(err)}`);
        }
    }
    return counts;
}
/**
 * Helper to get or create a folder in Google Drive by name under a parent folder.
 * Ensures the exact strict hierarchy: session_{session_number} -> {exportDate}
 */
async function getOrCreateDriveFolder(folderName, parentId, accessToken) {
    try {
        const query = `name = '${folderName}' and mimeType = 'application/vnd.google-apps.folder' and '${parentId}' in parents and trashed = false`;
        const searchUrl = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(query)}&supportsAllDrives=true&includeItemsFromAllDrives=true`;
        const searchRes = await fetch(searchUrl, {
            headers: { Authorization: `Bearer ${accessToken}` },
        });
        if (searchRes.ok) {
            const data = await searchRes.json();
            if (data.files && data.files.length > 0) {
                return data.files[0].id;
            }
        }
        const createRes = await fetch("https://www.googleapis.com/drive/v3/files?supportsAllDrives=true", {
            method: "POST",
            headers: {
                Authorization: `Bearer ${accessToken}`,
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                name: folderName,
                mimeType: "application/vnd.google-apps.folder",
                parents: [parentId],
            }),
        });
        if (createRes.ok) {
            const data = await createRes.json();
            return data.id || parentId;
        }
    }
    catch (err) {
        logger.warn(`Could not create/find Drive folder ${folderName}, falling back to parent:`, err);
    }
    return parentId;
}
/**
 * Module 24: exportResearchDataset
 *
 * Owner decision (5.9.2026): the research is the whole environment and the
 * whole process — every meeting, every learner, every action — not only the
 * routing decision of meetings 2 and 8. So this export is complete by
 * construction: no page caps, every meeting, every source the learner writes
 * to. Five CSV files (UTF-8 with BOM so Hebrew opens cleanly in Excel):
 *
 *   פעולות      — one row per telemetry event (the raw material)
 *   מפגשים      — one row per learner × meeting: first-attempt score (PRD
 *                 rule), counters (wrong digits, undos, deletions, hesitations,
 *                 coaching cards, regroupings), active minutes, recording
 *                 minutes, session-document score and path where one exists
 *   הקלטות      — one row per screen recording (start, end, minutes, chunks, truncated)
 *   רפלקציות    — every reflection, from Firestore and from the learners' RTDB nodes
 *   יומן_איפוסים — every reset audit entry
 *
 * Still enforced: teacher/admin only, scoped to the caller's class; PII scan
 * over every file; Drive hierarchy under "02 נתוני מחקר"; an audit entry.
 * `session_number` narrows the export to one meeting; omit it (or pass "all")
 * for the whole process.
 */
const EXPORT_RUNTIME = { timeoutSeconds: 540, memory: "1GiB" };
exports.exportResearchDataset = (0, https_1.onCall)(EXPORT_RUNTIME, async (request) => {
    var _a, _b, _c, _d, _e, _f, _g, _h, _j, _k, _l, _m;
    if (!request.auth) {
        throw new https_1.HttpsError("unauthenticated", "User must be authenticated.");
    }
    const { class_id = "class_1" } = request.data || {};
    const rawSession = (_a = request.data) === null || _a === void 0 ? void 0 : _a.session_number;
    const scopedSession = rawSession === undefined || rawSession === null || rawSession === "all" ? null : Number(rawSession) || null;
    const userEmail = request.auth.token.email || "teacher@edu-haifa.org.il";
    const token = request.auth.token;
    const callerRoles = Array.isArray(token.roles) ? token.roles : (token.role ? [token.role] : []);
    const isTeacher = callerRoles.includes("TEACHER") || token.role === "teacher" || token.teacher === true;
    const isAdmin = callerRoles.includes("ADMIN") || token.role === "admin" || token.admin === true;
    // Requirement 1: Authorization Check restricting caller to teacher/admin and scoping to class_id
    if (!isTeacher && !isAdmin) {
        throw new https_1.HttpsError("permission-denied", "Only authorized teachers or admins may export research datasets.");
    }
    const callerClassId = token.class_id;
    if (isTeacher && !isAdmin && callerClassId && callerClassId !== class_id) {
        throw new https_1.HttpsError("permission-denied", `Teacher is strictly restricted to exporting their own assigned class_id (${callerClassId}).`);
    }
    const db = admin.firestore();
    const rtdb = admin.database();
    const toCsv = (rows, columns) => {
        if (!rows || rows.length === 0)
            return "﻿empty\n";
        const headerSet = new Set();
        rows.forEach((r) => Object.keys(r).forEach((k) => headerSet.add(k)));
        const headers = columns !== null && columns !== void 0 ? columns : Array.from(headerSet);
        const cell = (val) => {
            const text = val === null || val === undefined ? "" : typeof val === "object" ? JSON.stringify(val) : String(val);
            return `"${text.replace(/"/g, '""')}"`;
        };
        const headerLine = headers.map(cell).join(",");
        const bodyLines = rows.map((row) => headers.map((h) => cell(row[h])).join(","));
        return "﻿" + [headerLine, ...bodyLines].join("\n");
    };
    const iso = (t) => (typeof t === "number" && t > 0 ? new Date(t).toISOString() : "");
    const studentNumber = (v) => {
        const n = parseInt(String(v !== null && v !== void 0 ? v : "").replace(/\D/g, ""), 10);
        return Number.isFinite(n) && n >= 1 && n <= 12 ? n : null;
    };
    try {
        // ── 1. Every telemetry event (optionally one meeting) ──────────────────
        const allTelemetry = await (0, meetingMetrics_1.readAllDocs)(db.collection("telemetry_logs"));
        const telemetry = allTelemetry
            .map(({ id, data }) => ({ id, data, session_number: (0, meetingMetrics_1.sessionNumberFromId)(String(data.session_id || "")) }))
            .filter((e) => scopedSession === null || e.session_number === scopedSession)
            .sort((a, b) => (a.data.client_timestamp || 0) - (b.data.client_timestamp || 0));
        const telemetryRows = telemetry.map(({ id, data, session_number }) => {
            var _a, _b, _c, _d, _e, _f, _g, _h, _j, _k, _l, _m, _o, _p, _q;
            const d = data.details && typeof data.details === "object" ? data.details : {};
            return {
                log_id: id,
                student_id: (_b = (_a = studentNumber(data.student_id)) !== null && _a !== void 0 ? _a : data.student_id) !== null && _b !== void 0 ? _b : "",
                session_number: session_number !== null && session_number !== void 0 ? session_number : "",
                session_id: (_c = data.session_id) !== null && _c !== void 0 ? _c : "",
                exercise_id: (_d = data.exercise_id) !== null && _d !== void 0 ? _d : "",
                event_type: (_e = data.event_type) !== null && _e !== void 0 ? _e : "",
                column_index: typeof data.column_index === "number" ? data.column_index : "",
                client_timestamp: (_f = data.client_timestamp) !== null && _f !== void 0 ? _f : "",
                client_time_iso: iso(data.client_timestamp),
                is_correct: d.is_correct === undefined ? "" : d.is_correct,
                digit_value: (_g = d.digit_value) !== null && _g !== void 0 ? _g : "",
                deleted_digit_value: (_h = d.deleted_digit_value) !== null && _h !== void 0 ? _h : "",
                block_value: (_j = d.block_value) !== null && _j !== void 0 ? _j : "",
                regrouping_type: (_k = d.regrouping_type) !== null && _k !== void 0 ? _k : "",
                hesitation_seconds: (_l = d.hesitation_seconds) !== null && _l !== void 0 ? _l : "",
                trigger_reason: (_m = d.trigger_reason) !== null && _m !== void 0 ? _m : "",
                error_category: (_o = d.error_category) !== null && _o !== void 0 ? _o : "",
                undo_stack_depth_before: (_p = d.undo_stack_depth_before) !== null && _p !== void 0 ? _p : "",
                reverted_event_type: (_q = d.reverted_event_type) !== null && _q !== void 0 ? _q : "",
                details_json: d,
            };
        });
        // ── 2. One row per learner × meeting ───────────────────────────────────
        const sessionDocs = await (0, meetingMetrics_1.readAllDocs)(db.collection("sessions").where("class_id", "==", class_id))
            .catch(async () => (0, meetingMetrics_1.readAllDocs)(db.collection("sessions")));
        const sessionDocByKey = new Map();
        for (const { data } of sessionDocs) {
            const n = studentNumber(data.student_id);
            const m = Number(data.session_number) || (0, meetingMetrics_1.sessionNumberFromId)(String(data.session_id || "")) || null;
            if (n !== null && m !== null)
                sessionDocByKey.set(`${n}:${m}`, data);
        }
        const studentsSnap = await rtdb.ref("users/students").get();
        const studentsNode = studentsSnap.val() || {};
        const learnerPath = new Map();
        const recordingRows = [];
        const recordingMinutesByKey = new Map();
        const rtdbReflectionRows = [];
        for (const [key, raw] of Object.entries(studentsNode)) {
            const n = studentNumber(key);
            if (n === null || !raw || typeof raw !== "object")
                continue;
            const node = raw;
            const path = node.teacher_selected_path === "remediation_path" || node.pedagogicalPath === "remediation_path" ? "remediation_path" : "green_path";
            if (!learnerPath.has(n))
                learnerPath.set(n, path);
            const recordings = node.telemetry_sessions && typeof node.telemetry_sessions === "object" ? node.telemetry_sessions : {};
            for (const [recId, rec] of Object.entries(recordings)) {
                if (!rec || typeof rec !== "object")
                    continue;
                const metas = Object.values((rec.metadata && typeof rec.metadata === "object" ? rec.metadata : {}))
                    .filter((m) => m && typeof m.startTime === "number");
                const start = metas.length ? Math.min(...metas.map((m) => m.startTime)) : null;
                const end = metas.length ? Math.max(...metas.map((m) => (typeof m.endTime === "number" ? m.endTime : m.startTime))) : null;
                const meeting = (_c = (_b = metas.find((m) => typeof m.sessionNumber === "number")) === null || _b === void 0 ? void 0 : _b.sessionNumber) !== null && _c !== void 0 ? _c : null;
                if (scopedSession !== null && meeting !== scopedSession)
                    continue;
                const minutes = start !== null && end !== null ? Math.round(((end - start) / 60000) * 10) / 10 : 0;
                const chunks = rec.chunks && typeof rec.chunks === "object" ? Object.keys(rec.chunks).length : 0;
                const truncated = rec.recording_truncated === true;
                recordingRows.push({
                    student_id: n, session_number: meeting !== null && meeting !== void 0 ? meeting : "", recording_id: recId, start_iso: iso(start), end_iso: iso(end),
                    minutes, chunks, exercises: Array.from(new Set(metas.map((m) => m.exercise_id).filter(Boolean))).join("|"), truncated,
                });
                if (meeting !== null) {
                    const k = `${n}:${meeting}`;
                    const prev = (_d = recordingMinutesByKey.get(k)) !== null && _d !== void 0 ? _d : { minutes: 0, truncated: false };
                    recordingMinutesByKey.set(k, { minutes: Math.round((prev.minutes + minutes) * 10) / 10, truncated: prev.truncated || truncated });
                }
            }
            if (node.reflections && typeof node.reflections === "object") {
                for (const [refKey, ref] of Object.entries(node.reflections)) {
                    rtdbReflectionRows.push(Object.assign({ source: "rtdb_student", student_id: n, reflection_id: refKey }, (ref && typeof ref === "object" ? ref : { value: ref })));
                }
            }
        }
        const byLearnerMeeting = new Map();
        for (const e of telemetry) {
            const n = studentNumber(e.data.student_id);
            if (n === null || e.session_number === null)
                continue;
            const k = `${n}:${e.session_number}`;
            byLearnerMeeting.set(k, [...((_e = byLearnerMeeting.get(k)) !== null && _e !== void 0 ? _e : []), e.data]);
        }
        const compulsoryCache = new Map();
        const meetingRows = [];
        for (const [k, events] of Array.from(byLearnerMeeting.entries()).sort()) {
            const [nStr, mStr] = k.split(":");
            const n = Number(nStr);
            const m = Number(mStr);
            const path = (_f = learnerPath.get(n)) !== null && _f !== void 0 ? _f : "green_path";
            const compulsory = await (0, meetingMetrics_1.resolveCompulsoryTotal)(db, m, path, compulsoryCache);
            const score = (0, meetingMetrics_1.computeFirstAttemptScore)(events, compulsory);
            const summary = (0, meetingMetrics_1.summarizeMeeting)(events);
            const sessionDoc = sessionDocByKey.get(k);
            const rec = recordingMinutesByKey.get(k);
            meetingRows.push({
                student_id: n,
                session_number: m,
                first_event_iso: iso(summary.first_event_at),
                last_event_iso: iso(summary.last_event_at),
                active_minutes: summary.active_minutes,
                events: summary.events,
                exercises_attempted: summary.exercises_attempted,
                exercises_completed: summary.exercises_completed,
                compulsory_total: score.denominator,
                correct_first_attempt: score.correctFirstAttempt,
                first_attempt_score_percent: score.scorePercent,
                digits_entered: summary.digits_entered,
                wrong_digits: summary.wrong_digits,
                deletions: summary.deletions,
                undos: summary.undos,
                hesitations: summary.hesitations,
                hesitation_seconds_total: summary.hesitation_seconds_total,
                regroupings: summary.regroupings,
                socratic_cards: summary.socratic_cards,
                reflection_submitted: summary.reflection_submitted,
                recording_minutes: (_g = rec === null || rec === void 0 ? void 0 : rec.minutes) !== null && _g !== void 0 ? _g : 0,
                recording_truncated: (_h = rec === null || rec === void 0 ? void 0 : rec.truncated) !== null && _h !== void 0 ? _h : false,
                learning_path: path,
                session_doc_score_percent: (_j = sessionDoc === null || sessionDoc === void 0 ? void 0 : sessionDoc.session_score_percent) !== null && _j !== void 0 ? _j : "",
                session_doc_recommended_path: (_k = sessionDoc === null || sessionDoc === void 0 ? void 0 : sessionDoc.matrix_recommended_path) !== null && _k !== void 0 ? _k : "",
                session_doc_teacher_path: (_l = sessionDoc === null || sessionDoc === void 0 ? void 0 : sessionDoc.teacher_selected_path) !== null && _l !== void 0 ? _l : "",
                teacher_gate_approved: (_m = sessionDoc === null || sessionDoc === void 0 ? void 0 : sessionDoc.teacher_gate_approved) !== null && _m !== void 0 ? _m : "",
            });
        }
        // ── 3. Reflections: Firestore + the learners' RTDB nodes + the shared node ──
        const fsReflections = await (0, meetingMetrics_1.readAllDocs)(db.collection("srl_reflections"));
        const sharedReflectionsSnap = await rtdb.ref("reflections").get();
        const sharedReflections = sharedReflectionsSnap.val() || {};
        const reflectionRows = [
            ...fsReflections.map(({ id, data }) => (Object.assign({ source: "firestore", reflection_id: id }, data))),
            ...Object.entries(sharedReflections).map(([id, r]) => (Object.assign({ source: "rtdb_shared", reflection_id: id }, (r && typeof r === "object" ? r : { value: r })))),
            ...rtdbReflectionRows,
        ].filter((r) => scopedSession === null || Number(r.session_number) === scopedSession || (0, meetingMetrics_1.sessionNumberFromId)(String(r.session_id || "")) === scopedSession);
        // ── 4. Every reset audit entry ──────────────────────────────────────────
        const resetLogs = await (0, meetingMetrics_1.readAllDocs)(db.collection("reset_audit_log").where("class_id", "==", class_id))
            .catch(async () => (0, meetingMetrics_1.readAllDocs)(db.collection("reset_audit_log")));
        const resetRows = resetLogs.map(({ id, data }) => (Object.assign({ log_id: id }, data)));
        const files = [
            { name: "פעולות", csv: toCsv(telemetryRows), rows: telemetryRows.length },
            { name: "מפגשים", csv: toCsv(meetingRows), rows: meetingRows.length },
            { name: "הקלטות", csv: toCsv(recordingRows), rows: recordingRows.length },
            { name: "רפלקציות", csv: toCsv(reflectionRows), rows: reflectionRows.length },
            { name: "יומן_איפוסים", csv: toCsv(resetRows), rows: resetRows.length },
        ];
        // Requirement 3: PII Detection check across all CSV outputs
        const allContent = files.map((f) => f.csv).join("\n");
        const piiRegex = /(?:\b05\d-?\d{7}\b|[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}|\b\d{9}\b)/g;
        const sanitizedCheckText = allContent.split(userEmail).join("");
        if (piiRegex.test(sanitizedCheckText)) {
            logger.warn("Research dataset export rejected: PII pattern detected.");
            throw new https_1.HttpsError("failed-precondition", "ייצוא נתוני המחקר נדחה: זוהה מידע מזהה (PII).");
        }
        const exportDate = new Date().toISOString().split("T")[0];
        const stamp = new Date().toISOString().slice(0, 16).replace("T", "_").replace(":", "-");
        const scopeLabel = scopedSession === null ? "כל המפגשים" : `מפגש ${scopedSession}`;
        // Requirement 4: Drive folder hierarchy: 02 נתוני מחקר / {scope} / {date}
        const targetFolderId = await resolveDriveFolder([exports.DRIVE_FOLDERS.researchData, scopeLabel, exportDate]);
        const uploads = {};
        const uploadedIds = [];
        for (const f of files) {
            const res = await uploadBufferToDrive(Buffer.from(f.csv, "utf-8"), `${f.name}_${stamp}.csv`, "text/csv", targetFolderId);
            uploads[f.name] = res.success ? res.webViewLink : `failed: ${res.error}`;
            if (res.success)
                uploadedIds.push(res.fileId);
        }
        if (uploadedIds.length === 0) {
            throw new https_1.HttpsError("internal", `הייצוא נבנה (${files.map((f) => `${f.name}: ${f.rows}`).join(", ")}) אך הכתיבה לדרייב נכשלה: ${uploads[files[0].name]}`);
        }
        // Requirement 5: Log export event to reset_audit_log with reset_level: 'export'
        const exportLogId = `export_${Date.now()}`;
        await db.collection("reset_audit_log").doc(exportLogId).set({
            reset_id: exportLogId,
            timestamp: Date.now(),
            performed_by: request.auth.uid,
            user_email: userEmail,
            reset_level: "export",
            reason: "RESEARCH_DATASET_EXPORT",
            affected_student_id: "ALL",
            class_id,
            session_number: scopedSession !== null && scopedSession !== void 0 ? scopedSession : "all",
            export_date: exportDate,
            drive_folder_id: targetFolderId,
            files: uploadedIds,
            row_counts: Object.fromEntries(files.map((f) => [f.name, f.rows])),
            status: "SUCCESS",
            created_at: admin.firestore.FieldValue.serverTimestamp(),
        });
        logger.info(`Research dataset exported for class ${class_id} (${scopeLabel}) on ${exportDate}: ${files.map((f) => `${f.name}=${f.rows}`).join(", ")}`);
        return {
            status: "SUCCESS",
            exportDate,
            scope: scopedSession !== null && scopedSession !== void 0 ? scopedSession : "all",
            targetFolderId,
            rowCounts: Object.fromEntries(files.map((f) => [f.name, f.rows])),
            files: uploads,
        };
    }
    catch (err) {
        if (err instanceof https_1.HttpsError)
            throw err;
        logger.error("Failed to export research dataset:", err);
        throw new https_1.HttpsError("internal", (err === null || err === void 0 ? void 0 : err.message) || "ייצוא נתוני המחקר נכשל.");
    }
});
//# sourceMappingURL=exportDriveReport.js.map